### ISSUE TITLE
Notify to analytics that the user has moved onto the cross-device flow

### ISSUE THREAD

**Issue by pablobm** [onfido/onfido-sdk-ui#1008]
Since 5.8.0, we are able to track the user's progress through the Onfido flow, and report it to our analytics.

Now that we have this capability, we would like to measure the performance of the cross-device flow, compared to the desktop-only flow. However, the current analytics do not appear to signal in any way that the user crossed over from desktop to smartphone.

### What was the expected behaviour?

We would expect something like one of these:

* A dedicated event signalling that the user is crossing over from desktop to smartphone.
* An argument to existing events indicating that it's taking place in the smartphone part of the cross-device flow.

### What happened instead?

There doesn't appear to be a way to tell that the user has crossed over.

### Version info:

- Onfido SDK 9.5.0
- Google Chrome 81

### Demo

https://jsfiddle.net/pablobm/a0ko478u/3/

For some reason, `console.log` doesn't work (perhaps an issue with the frames?), so I have resorted to `alert` in the example.

**Comment by stefaniacardenas** [comment]
This issue has been fixed in version [5.13.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.13.0).
