### ISSUE TITLE
Chrome for Android not prompted to enable camera or fallback to file upload when permission is denied

### ISSUE THREAD

**Issue by j--w** [onfido/onfido-sdk-ui#1009]
### What was the expected behaviour?

When prompted for Camera access in Chrome for Android if the user ticks the box "Do not ask again" and clicks "deny" and returns to the site later they should be falling back to file upload when clicking the "Take Photo" button

### What happened instead?
They are not shown any kind of message nor do they fallback to file upload if they return to try again.

In Firefox for Android it falls back to file upload as expected.

### Version info:

- Onfido SDK - 5.8.0
- OS - Android 8.1.0
- Browser - Chrome 81.0.4044.138
- Device - Oneplus A6003
- Node
- Framework or relevant dependencies (if applicable)

### Integration configuration:

```json

{
  "useModal": false,
  "token": ...,
  "steps": [
    {
      "type": "welcome",
      "options": {
        "title": "Submit identity document",
        "descriptions": [
          "To finish verifying your identity, we need an identity document.",
          "Please follow these steps to upload a document."
        ]
      }
    },
    "document",
    {
      "type": "complete",
      "options": {
        "message": "Upload complete!"
      }
    }
  ]
}
```

### Steps to reproduce:
This is how I discovered it, there may be an easier entrypoint:
Precondition: Chrome is set to prompt for camera access when requested, camera access to chrome is turned off at the android app permissions level

1. Initialize onfido SDK on computer
2. Select document
3. Select "Continue on Phone"
4. Go to generated link on Android device with Chrome
5. Click the "Take Photo" button on onfidos page
6. When prompted to "Allow Chrome to tkae pictures and record video?" tick the "Don't ask again" button and click "Deny"

* At this point I would expect to be directed to the file browser to upload a file. If I click Take photo again I would expect to be directed to the file browser to upload file.

7. Close your session and repeat steps 1 - 5 again
At this point I would also expect it to fallback to the file browser but it does not, you're just stuck on the "Take Photo" page.

**Comment by stefaniacardenas** [comment]
Hi @j--w, thanks for reporting this issue. In general, we are trying prevent users from selecting an image from the gallery because we want to enforce live captures. This implementation explicitly requests live camera images, although we are aware that Firefox still allows the user to pick a file from the camera, and that's probably the reason why Firefox fallbacks on the gallery file input while Chrome does not. Having said that, I understand that the current experience on Chrome when the users denies the native camera permissions is not ideal. I will discuss this issue with the team and try to provide a better user experience to guide the user toward taking a live photo.

**Comment by Lechus** [comment]
any update, fixes?

**Comment by wlm14566** [comment]
Hi, 

We are facing this issue with our customers who use chrome for iOS 14 as well. Can this issue be prioritized as its been in open status for the past 6 months.

**Comment by osolliec** [comment]
Hello. We've fixed this issue over the years. Can't pinpoint exactly which version, but our latest LTS (6.15.6) has the feature for camera "recovery"

See the following screens (easily reproducible by testing in incognito mode).

![Screenshot_2022-10-28-10-33-32-37_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/22033728/198543166-8bbc0a38-8ea8-432e-ba98-78b435ae9912.jpg)
![Screenshot_2022-10-28-10-33-40-60_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/22033728/198543172-355086cd-34fd-4771-8e1d-b83a22684b53.jpg)
![Screenshot_2022-10-28-10-33-35-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/22033728/198543176-52ba9a1c-2484-4087-bd62-55f73d17ba7a.jpg)

**Comment by artiomchi** [comment]
@osolliec could this issue be re-opened, and could someone confirm this is a problem again?

**Comment by osolliec** [comment]
@artiomchi Could you please upload a video to describe your issue ? 
Also which phone do you use, which android version, which browser. 
On my phone, the permission gets asked and if you ignore it, it just goes to show the permission error screen.
