### ISSUE TITLE
Supplying one document type

### ISSUE THREAD

**Issue by lloydrhodes87** [onfido/onfido-sdk-ui#1010]
### What was the expected behaviour?

According to the readme supplying one doctype should take you straight to the capture screen. 

". If documentTypes only includes one document type, users will not see the document selection screen and instead will be taken to the capture screen directly."

### What happened instead?

It takes me to the doc selection screen with one document. 

### Version info:

Ionic 
Onfido SDK 5.9.2
Android 8.1
Chrome Browser

### Integration configuration:

 containerId: 'onfido-mount',
      steps: [
        'document'
       
      ],
      documentTypes: {passport: true},
      useLiveDocumentCapture: true,
      uploadFallback: true,
      onComplete: function(data) {

### Steps to reproduce:

Add one item in documentType object.

**Comment by dainiust** [comment]
Hi,

Did you solve this issue? if so what was the problem? Because currently I am having same issue.

**Comment by lloydrhodes87** [comment]
Hi, 

I was doing it with the incorrect format. It needs to be 

```
  async handleOnfidoCheck() {
   
    const documentTypes = this.getDocType();

    let self = this
    this.documentUploadCheck =  await Onfido.init({
      token: this.token,
      containerId: 'onfido-mount',
      steps: [
        {
          type: 'document',
          options: {
             {'passport': true}
          }
        },
      ],
      
      useLiveDocumentCapture: true,
        uploadFallback: true,
      
      onComplete: function(data) {
        self.navCtrl.push('OnfidoCompletePage', 
          { 
            documentData: data, 
            applicantId: self.applicantId, 
            fromApplyPage: self.fromApplyPage
          });
        self.documentUploadCheck.tearDown();
      }
    })

  }

}
```

In the end the SDK wasnt the right choice for me but this solution, fixed my problem above. 

Hope it helps

**Comment by dainiust** [comment]
Yep it helped, thanks. I was setting `documentTypes` not in `steps`, that was my issue :)
