### ISSUE TITLE
Send userAnalyticsEvent when the user has moved onto the "document type selection" page  

### ISSUE THREAD

**Issue by mansona** [onfido/onfido-sdk-ui#1011]
This issue is very similar to https://github.com/onfido/onfido-sdk-ui/issues/1008 in that we would like to be able to react when the user clicks the "verify identity" button on the first page. Essentially there is no way to tell using the `userAnalyticsEvent` that they have moved from the first `WELCOME` page to the next page where they select the document type.

### What was the expected behaviour?

When the user clicks the `verify identity` button on the `WELCOME` page we expect to have some event sent to the `userAnalyticsEvent` such as `DOCUMENT_TYPE_SELECT`.

### What happened instead?

No events are triggered during this transition.

### Version info:

- Onfido SDK 5.9.2
- Browser Chrome 81

### Demo:

You can use the same demo that https://github.com/onfido/onfido-sdk-ui/issues/1008 is using as it is just console.log()-ing the event names 👍 

https://jsfiddle.net/pablobm/a0ko478u/3/

**Comment by stefaniacardenas** [comment]
This issue has been fixed in version [5.13.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.13.0).
