### ISSUE TITLE
Image capture crashes inside of cordova in app browser.

### ISSUE THREAD

**Issue by JohnathanWhite** [onfido/onfido-sdk-ui#1013]
Hey there! In our ionic app we are using the sdk inside of a cordova in app browser. Intermittently, when capturing an image the SDK suddenly freezes then closes. This seems isolated to older iphones as we have only been able to reproduce on iphone 6s and 8. 

- Onfido SDK 5.5
- OS 13.4.1
- Browser cordova in app browser 3.2.0
- Device iphone 6s and 8
- Ionic 4.14.0

Steps to reproduce:
Inside of cordova in app browser summon the SDK UI. Try to take a picture of a document or selfie. Randomly, SDK UI will crash after image capture.

Thank you!

**Comment by JohnathanWhite** [comment]
I will try and increment the version and see if that helps.

**Comment by stefaniacardenas** [comment]
Hi @JohnathanWhite, are you still facing this issue after upgrading? The SDK is not tested to work inside a Cordova app, would you be able to share a demo or a repo where I can try to reproduce the issue?

**Comment by stefaniacardenas** [comment]
I will close this issue for inactivity.
