### ISSUE TITLE
Users unable to submit photo during Selfie step

### ISSUE THREAD

**Issue by ctrlaltdylan** [onfido/onfido-sdk-ui#1029]
### What was the expected behaviour?

Our users should be able to capture their selfie during the selfie step.

### What happened instead?

Still trying to get details from our users, but the cases we have are "I'm unable to take my selfie photo", "It doesn't let me take the selfie photo", " I try to upload selfie but it kicks me out", "Screen frozen after taking a picture of the back of my ID"

We've confirmed this issue on Internet Explorer specifically.

### Anecdotes from customers

> I was uploading them from my PC. After I would submit the back of the license the screen would go blank and nothing else happened. I did not try my phone.

>Hello ! My platform is google chrome! I have tried multiple times to upload and send ID and it says I have to have the latest Safari platform! I don’t know what to do!

Will share as I learn more.

### Version info:

- Onfido SDK - 5.9.2
- OS - not sure yet
- Browser - not sure yet
- Device - Desktops 
- Framework or relevant dependencies (if applicable) - React

### Affected Onfido Applicants

`87240589-d949-40d5-9463-795acfafd930`
`12581015-aba7-4b73-b2e0-b2cb829ed954`
`83a9ed4d-3757-4afa-9379-aa0ac8051cd5`
`2d864273-11a1-4582-834c-1154850a979d`
`f11511bd-855f-4e4a-822f-1c14f03ccb80`
`d84a9bbe-4bb4-4a08-abbf-fce849f4df4d`
`437d232f-16fb-4148-8c2e-9ca12185652b`
`2cd5e1b5-66d5-4559-9290-ff270ee825b4`
`8347a5b7-5fc3-400a-9741-9c0760fbc785`
`2cd5e1b5-66d5-4559-9290-ff270ee825b4`
`3f2d7618-44a9-4bda-803d-97a41916df68`
`03d33630-bbe7-464f-b504-b08e625d7453`
`4ffc2547-715b-4f7d-8cc7-3abbe847729a`
`490b4fd5-9e5a-4448-8f17-da1be336ff1a`
`26959438-b437-49f4-baf0-b49d62a36eb2`

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan, are you using `uploadFallback: false`? If they are on a desktop with no camera or no `getUserMedia` support, there is a fix coming up in the next release. Is there any way you could find out the browser/device they are using?

**Comment by ctrlaltdylan** [comment]
Hi there @stefaniacardenas I'm still sorting through responses from yesterday but yes `uploadFallback: false` is what our configuration is set to.

I'm updating the main issue description with more info as I go along, the first case is definitely where the user was using their desktop to upload the photos.

It's very difficult to get details from our customers, but I'm asking.

In the meantime do you recommend we rollback to `uploadFallback: true` for the selfie step?

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan, if it's affecting a large number of users then I would suggest to use `uploadFallback: true`, otherwise you could upgrade to the next SDK version once it goes live next week.

**Comment by ctrlaltdylan** [comment]
@stefaniacardenas can you clarify for our QA team on how setting `uploadFallback: true` fixes this issue?

We've tried using a browser that doesn't provide `getMedia` support (IE) and once we reach the selfie step, we expect to be greeted with the ability to upload our own selfie. Instead we're presented the only option of continuing on our phone.

What's the actual functionality of `uploadFallback: true`?

![image (20)](https://user-images.githubusercontent.com/2694734/84159860-8cc90c80-aa3b-11ea-8dd2-3236100c4491.png)

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan, that's the expected behaviour. If a browser does not support getUserMedia or a camera is not present, the first thing we will attempt is guiding the user towards using their phone via the SMS/QR code feature. Once they open the link on their phone, if they are using a phone with a camera and the browser supports `getUserMedia` they will be able to take a photo using the camera stream inside the browser. If `uploadFallback` is true, and there is no camera or no `getUserMedia` support, they will be able to take a photo using their native camera (note: some browsers gives access to the user gallery, which would allow the user to upload a photo). If `uploadFallback` is false, and there is no camera or no `getUserMedia` support, the user is blocked and needs to restart the process on a different browser.
I hope that makes sense.

**Comment by ctrlaltdylan** [comment]
Thanks @stefaniacardenas I see what you mean. `uploadFallback` is shorthand for `uploadFallbackOnMobile` essentially. We took it to mean `uploadFallbackOnDesktop` or originating device when you elect to go through manually uploading photos instead of completing on mobile.

**Comment by ctrlaltdylan** [comment]
@stefaniacardenas does the latest release include this fix? https://github.com/onfido/onfido-sdk-ui/releases/tag/5.10.0

**Comment by stefaniacardenas** [comment]
Yes, it does. You can upgrade to 5.10.0 and start using `uploadFallback: false` again.

**Comment by ctrlaltdylan** [comment]
Thanks. I think after these last couple of cases I don't think the risk of an outage is worth the reward. We'll keep `uploadFallback: true`. We were swamped with cases and had to manually upload each one.

**Comment by stefaniacardenas** [comment]
I'm sorry to hear that. Unfortunately, we had to deal with multiple bugs introduced in the latest Safari version and we had to release fixes to work around them. Not great.

**Comment by stefaniacardenas** [comment]
I will close this issue as a fix has been released in version 5.10.0.
