### ISSUE TITLE
Onfido back button is not in sync with the browser history anymore

### ISSUE THREAD

**Issue by aoumiri** [onfido/onfido-sdk-ui#1051]
### What was the expected behaviour?

Prior to the 5.10.0 release, clicking on the browser's back button was doing the same thing than clicking on Onfido's back button.

### What happened instead?

Since the `5.10.0` and the migration to `MemoryRouter`, this is not the case anymore.

This is a breaking change since clicking on the browser's back button will now take users to the last page he visited before doing anything in the onfido widget.

In short: if the user was on the last step of the Onfido flow, they will be taken back to the page before the one that loads the Widget, thus they will have to initiate the whole flow from the start. Which results in a poor user experience, and the risk of having people dropping out of the onfido flow is higher.

PS: obviously, doing `window.history.back()` will result in the same issue.

### Version info:

- Onfido SDK: 5.10.0

### Integration configuration:

This can be reproduced with the default configuration and without any customization.

### Steps to reproduce:

Let's say you have two URLs in your webapp:

- home: contains a link to `onfido` page
- onfido: loads the onfido plugin

Go to `home`, click on the link of the `onfido`. Follow as much step in the onfido flow, then randomly click on the browser's back button: you will be redirected to `home`.
You will lose everything that you uploaded.

### Demo:

Edit: 
- here is a demo of what I'm experiencing with the 5.10.0 vs the 5.9.2: https://dxnm0.sse.codesandbox.io/
- and a recording on how to reproduce: https://www.loom.com/share/e37f201ccced47febd5f076a18f4f406

**Comment by stefaniacardenas** [comment]
Hi @aoumiri, that's a valid feedback. I'm discussing with the team a possible solution. Will keep you posted. Thank you!

**Comment by aoumiri** [comment]
One solution would be to expose the back function, by returning it in the init function?

Also another idea would be to make it configurable in the init options.

**Comment by stefaniacardenas** [comment]
Hi @aoumiri, this issue has been fixed in version [5.11.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.11.0). We added the option to use `history/createMemoryHistory` by passing the configuration option `useMemoryHistory: true` to the SDK, in case history/createBrowserHistory does not behave as expected. I will close this issue now, thank you for reporting it.

**Comment by aoumiri** [comment]
Thank you so much :-)
