### ISSUE TITLE
dose "requestedVariant: video" work on browsers?

### ISSUE THREAD

**Issue by FEhao** [onfido/onfido-sdk-ui#1056]
Just want to know if any browsers support video check like the image below, 
and how to set the options.
On Chrome and Safari, what { requestedVariant: 'video' } get is still an static image
![image](https://user-images.githubusercontent.com/22510802/85530024-30bbd600-b640-11ea-8dbd-ef7ef55acd6c.png)

**Comment by andra-radu** [comment]
Hi @FEhao, 

Liveness availability on browsers: 
Desktop Chrome and Firefox
Android Chrome
iOS any browser: liveness not supported 
Browser compatibility can also be checked here: https://github.com/onfido/onfido-sdk-ui#browser-compatibility 
You can read more about requestedVariant: 'standard' | 'video' in our documentation here: https://github.com/onfido/onfido-sdk-ui
 Unfortunately, Safari does not support video recording functionalities yet, therefore on Safari we will always fallback to the standard variant. Our SDK team will add more details about the fallback get included in the documentation in the next releases. Many thanks!
