### ISSUE TITLE
How to style the onfido

### ISSUE THREAD

**Issue by RezaRahmati** [onfido/onfido-sdk-ui#1124]
Hi there

I want to apply styles to onfido to look like our company brand based on below mock. I didn't want to reinvent the wheel, so was wondering may be there is a known solution for that.

I appreciate any help

p.s it's not only this page, seems all pages should be styled

![image](https://user-images.githubusercontent.com/10086092/87791036-93ebf300-c80f-11ea-9423-32e4e98bbcad.png)

**Comment by andra-radu** [comment]
Hi @RezaRahmati, Thank you for getting in touch with us.
Mobile SDKs support style customisation, while Web SDK does not offer a way of overriding the style, but you can still use CSS to override classes. All the colours we use are stored as variables in this file
https://github.com/onfido/onfido-sdk-ui/blob/master/src/components/Theme/constants.css 
The SDK is open source so you can just find the variable for the colour you need (if that's the case) and see all the class where it’s used. 
So for example, let’s say the want to change the primary blue which is assigned to this variable @color-primary-500, you can then search all the classes that use that colour @color-primary-500.

**Comment by RezaRahmati** [comment]
@andra-radu 
Got it thanks
