### ISSUE TITLE
iOS 13 impose requestedVariant video not selfie

### ISSUE THREAD

**Issue by tiamen** [onfido/onfido-sdk-ui#1128]
### What was the expected behaviour?

On your documentation you have:
https://github.com/onfido/onfido-sdk-ui#face

> If the requestedVariant is video, we will try to fulfil this request depending on camera availability and device/browser support. In case a video cannot be taken the face step will fallback to the standard option.

But if I don't want to allow the user to use the standard option selfie. How can I disable the fallback and just show error message saying something like "iOS does not support liveness video".

```
                             {
    				    type: 'face',
    				    options: {
    				        requestedVariant: 'video',
    				        uploadFallback: false //upload photo
    				    }
    				},
```

### Version info:

- Onfido SDK
5.12
- OS
13.4
- Browser
safari
- Device
iPhone XS

**Comment by andra-radu** [comment]
Hi @tiamen 
I'm afraid this is not possible at the moment because without falling back to selfie the user would be stuck.

**Comment by tiamen** [comment]
Let's see if Onfido can change this especially if you have a requirement to prove liveness and you just return one selfie is not the same.

**Comment by andra-radu** [comment]
Hi @tiamen, I have provided your feedback to our Product team. If you have any questions or concerns please do not hesitate to contact us. We would be more than glad to assist you.

**Comment by anttilbc** [comment]
We also have this same problem. In some cases it is a requirement to get liveness. We worked around this by first testing if the device supports some of the required features to complete liveness and if not, we will show error message instead of starting Onfido. This is not ideal, but better than nothing. I would like to see this as an option for the onfido-sdk-ui

**Comment by tiamen** [comment]
@anttilbc but if you start the process using PC and then the user uses the QR Code or the SMS to change to the phone you can't control that right?

**Comment by anttilbc** [comment]
@tiamen That is true. We also have check after the mobile flow that it returned the variant we expected and if not, let the user know that it did not work. That is FAR from ideal as the user completes the wrong flow fully at this point. But it is better than telling the user that "check completed" or whatever when that is not the case.

**Comment by stefaniacardenas** [comment]
Hi @anttilbc, I would suggest discussing this issue with your account manager, who will liaise with the Product team about the possibility of introducing this feature.
