### ISSUE TITLE
Passport picture set by default to poa

### ISSUE THREAD

**Issue by pferayferrand** [onfido/onfido-sdk-ui#1132]
### What was the expected behaviour?

I expected to upload / take a picture of my poa (on mobile)

### What happened instead?

I see the passport image already filled instead of the option to take / upload my poa

### Version info:

- Onfido SDK: 5.12.0
- OS: iOS
- Browser: Safare
- Device: iPhone 10

### Integration configuration:

```
{
    token: res.data.onfido_token,
    containerId: 'onfido-mount',
    onComplete: () => {
        confirmOnfido(userID)
        .then((res) => {
            res.status === 200 && navigate('/onboarding')
        })
        .catch((err) => window.Sentry.captureException(err))
    },
    onError: (err) => {
        // eslint-disable-next-line no-console
        console.log('Onfido Err', err)
        window.Sentry.captureException(err)
    },
    steps: [
        {
        type: 'welcome',
        options: {
            title: 'Before you get started',
            descriptions: [
            'Have your passport and proof of address (e.g., utility bill or bank statement) or scans/photos thereof ready',
            'Your proof of address MUST be dated within the last 3 months',
            ],
            nextButton: 'Start ID Check',
        },
        },
        {
        type: 'document',
        options: {
            documentTypes: {
            passport: true,
            driving_licence: false,
            national_identity_card: false,
            },
        },
        },
        {
        type: 'poa',
        options: {
            country: 'SGP',
        },
        },
        'face',
        'complete',
    ]
}
```
Plus a very lengthy language config...

### Steps to reproduce:

Start the Onfido check
Select the mobile option to upload documents
Upon passport step, take a picture of the passport
Validate the passport picture
Select any of the 3 available poa: (bill / government letter / bank letter)
Click on the button to take a picture
Passport image is already 

### Demo:
![onfido-issue](https://user-images.githubusercontent.com/7931138/88397849-6fb68600-cdbc-11ea-8008-617239eebca6.gif)

**Comment by ramprasad-parajuli** [comment]
@pferayferrand Thank you for reaching out to us.

The Proof of Address document capture is currently a BETA feature, and it cannot be used in conjunction with the document and face steps as part of a single SDK flow. That is the reason you are experiencing the behavior you mentioned.
