### ISSUE TITLE
Unable to get property 'hideOnfidoLogo' of undefined or null reference

### ISSUE THREAD

**Issue by tbuteler** [onfido/onfido-sdk-ui#1160]
### What was the expected behaviour?

Upon loading the Onfido SDK, we don't expect errors in the console.

### What happened instead?

The Onfido SDK throws an error:
> Unable to get property 'hideOnfidoLogo' of undefined or null reference

Seems to happen [here](https://github.com/onfido/onfido-sdk-ui/blob/5.13.0/src/components/App/index.js#L115), according to the trace.

### Version info:

- Onfido SDK: 5.13.0
- OS: macOS 10.14.6
- Browser: Chrome 84.0.4147 (and all others tested)
- Framework: Vue 2.6.11

### Integration configuration:

These are the options I think might be relevant. Some were omitted for brevity:

```js
{
    containerId: 'onfido-mount',
    useModal: false,
    enterpriseFeatures: {
        hideOnfidoLogo: true
    },
    useMemoryHistory: true,
    language: {
        //...
    }
    // ...
}
```

We're not setup as an enterprise customer, but we tried passing the `enterpriseFeatures.hideOnfidoLogo` property to see if it fixed the issue, but it hasn't.

### Steps to reproduce:

Merely load a 5.13.0 SDK and the error will be thrown. The relevant bit might be the token that's granted by Onfido to our team, which as far as I can tell has the payload that [this method](https://github.com/onfido/onfido-sdk-ui/blob/5.13.0/src/components/App/index.js#L115) is using the determine enterprise features.

Please let me know if you need more info, I'd be glad to submit it privately.

**Comment by andra-radu** [comment]
Hi @tbuteler  If you are looking to have 'hideOnfidoLogo' undefined or null you'll need to get in touch with you account manager as it is a paid premium feature and it is not available to all customers. If you have any questions or concerns please do not hesitate to contact me. I would be more than glad to assist you. Kind regards,

**Comment by tbuteler** [comment]
I'm not looking to hide the Onfido logo. I just don't want an error to be thrown _because_ I don't pay for that premium feature. As I said above we're only defining `enterpriseFeatures.hideOnfidoLogo` as an attempt to fix the issue, but it has no effect on whether the error is thrown or not.

**Comment by kopijunkie** [comment]
Thank you for clarifying the issue you're facing @tbuteler 

In this case, because you have set `hideOnfidoLogo` to `true` it would result in that error at the line you've indicated. But you've also mentioned you were seeing the error already without that being set originally so it may be an issue with the token generated. If you're able to continue this conversation privately on Zendesk then we can look further into what's happening for your integration.

**Comment by tbuteler** [comment]
@kopijunkie Thanks for your response. Turns out not defining `enterpriseFeatures.hideOnfidoLogo` on our current SDK version _does_ fix the issue. My apologies, it was a miscommunication issue on our part. I'll close this issue.
