### ISSUE TITLE
Image quality guide for all document types?

### ISSUE THREAD

**Issue by anttilbc** [onfido/onfido-sdk-ui#1164]
The image quality guide for passport is quite neat so it would be nice to have it with the other document types as well. Why only passports get the special treatment? :slightly_smiling_face: 

### Version info:
- Onfido SDK 5.11.3

**Comment by andra-radu** [comment]
Hi @anttilbc - Thank you so much for your feedback. We really appreciate it and I have forwarded it to the concerned team.

In the meantime, please find below the detailed image quality requirements which will help your clients/users to provide an acceptable document:

Include all 4 corners of your document and make sure the edges of the document are not cropped or cut off.
Take the image in natural daylight and avoid camera flashes or light glare that can obscure data
Lay the document on a flat surface, holding it open and take the image from a birds-eye view
Make sure no objects (hands/fingers/pieces of paper etc) are covering any parts of the document
If the document has information on two sides, we need to see an image of both the front and back of this document. The image of the front and back must be uploaded as separate files and not placed together into one file with any photo editing software or apps.
We only accept original documents. Screenshots (including from your mobile camera roll), photocopies, prints, etc are not acceptable.
The image must be in colour as we do not accept black and white or greyscale documents. 
If you have any questions or concerns please do not hesitate to contact me. I would be more than glad to assist you. 
Kind regards,

**Comment by seewah** [comment]
Hi, we have reviewed this request, and decided that the value of the end-users is not significant enough. The guide is useful for passport primarily because of cut-off image issues, which are not as prevalent on card-format documents. Thanks for the suggestion, but I am afraid we are not going to add this for non-passports
