### ISSUE TITLE
Error in consuming sdk javascript

### ISSUE THREAD

**Issue by SwatiGour16** [onfido/onfido-sdk-ui#1175]
Onfido ui should get rendered without any error.

I am getting below error.

"TypeError: Cannot read property 'Symbol' of undefined

    at Object.eval (Onfido/onfido.min.js:46:25060)

    at Object.eval (Onfido/onfido.min.js:46:25224)

    at i (Onfido/onfido.min.js:2:587)

    at Object.eval (Onfido/onfido.min.js:22:85415)

    at i (Onfido/onfido.min.js:2:587)

    at Object.eval (Onfido/onfido.min.js:33:3147)

    at i (Onfido/onfido.min.js:2:587)

    at Object.eval (Onfido/onfido.min.js:46:24900)

    at i (Onfido/onfido.min.js:2:587)

    at Object.eval (Onfido/onfido.min.js:22:119891)"

Please detail what the actual behaviour was

### Version info:

- Onfido SDK
Using javascript min file.
- OS: Windows 10
- Browser: Chrome 83
- Device: Desktop 
- Node
- Framework or relevant dependencies (if applicable)

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.
We are trying to consume it in Salesforce, we can't install sdk module, so we are using javascript file.

### Steps to reproduce:

Please describe in as much detail as possible how to reproduce the problem

### Demo:

If possible, please share a URL or public repository where the issue can be reproduced

https://lrdev-b2clrdev.cs126.force.com/test/s/

**Comment by stefaniacardenas** [comment]
Hi @SwatiGour16, could you try to install version 5.11.3 and see if you are still facing the same issue? I suspect that this issue might be related to issue #1178.

**Comment by stefaniacardenas** [comment]
Hi, could you try updating to the latest version `6.0.0` and let me know if you are still facing this issue?

**Comment by SwatiGour16** [comment]
Hi Stefania,

Issue is coming due to Salesforce locker services which works in a secure
manner.

This is locker console which evaluate thirdparty javascript for Salesforce.
If you copy party onfido.min.js, you will see error.

https://developer.salesforce.com/docs/component-library/tools/locker-service-console

Onfido.min.js is giving error when salesforce rum eval function on it.
https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_js_eval.htm


Please let me know if you need more details.

Thanks,
Swati

**Comment by nvasseur** [comment]
Hello @SwatiGour16 , we are trying to implement the WebSDK into a Salesforce Community but have the same issue as yourself. Have you been able to make it work? Thank you,
Nico.

**Comment by SwatiGour16** [comment]
@nvasseur we haven't got it fixed. Onfido team is working on this issue with salesforce and for now they recommend us to use visualforce page approach.

**Comment by kushal-onfido** [comment]
We have fixed this issue in the latest release [6.19.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.19.0). Please let us know if you still see any issue with this while using the latest version of the SDK. 

We thank you for your patience while we were working on this fix.
