### ISSUE TITLE
Version 5.13.0 has invalid CSS in distribution

### ISSUE THREAD

**Issue by stefanmaric** [onfido/onfido-sdk-ui#1178]
### What was the expected behaviour?

Valid CSS
### What happened instead?

The dist files include SASS variables like `$$unit-rrui`.

See: https://github.com/onfido/onfido-sdk-ui/blob/7be961909dfbe8b1bc4bdd26c9416efffee75710/dist/style.css

### Version info:

- Onfido SDK: 5.13.0

### Integration configuration:

N/A

### Steps to reproduce:

It is part of the build.

### Demo:

https://github.com/onfido/onfido-sdk-ui/blob/7be961909dfbe8b1bc4bdd26c9416efffee75710/dist/style.css

**Comment by kopijunkie** [comment]
Hi @stefanmaric 

Thanks for raising this issue and the PR to address this. We'll review the PR and get it merged in our next release.

**Comment by badikumar** [comment]
@stefanmaric 5.13.0 is un-usable without a fix to this issue.
