### ISSUE TITLE
SMS_BODY changes have no effect

### ISSUE THREAD

**Issue by maralm** [onfido/onfido-sdk-ui#1185]
### What was the expected behaviour?

Setting [the `SMS_BODY` text key](https://github.com/onfido/onfido-sdk-ui/blob/master/src/locales/en_US/en_US.json#L450) should change the text content of the SMS.

### What happened instead?

The `SMS_BODY` text key seemingly has no effect, regardless of locale.

The following setup results in English default SMS text:

```
Onfido.init({
    // omitted for brevity
    language: {
        "locale": "en_US",
        "phrases": {
            // omitted for brevity
            "SMS_BODY": "My SMS body text in English: "
        }
    }
});
```

and the following results in Dutch default SMS text:

```
Onfido.init({
    // omitted for brevity
    language: {
        "locale": "nl_NL",
        "phrases": {
            // omitted for brevity
            "SMS_BODY": "My SMS body text in Dutch: "
        }
    }
});
```

but the [README.md](https://github.com/onfido/onfido-sdk-ui/blob/master/README.md) seems to indicate that one or both of the examples above should in fact work:

> The locale tag is also used to override the language of the SMS body for the cross device feature.

The expected behavior is that one or both of the examples above would have an effect on the sms body text.

### Version info:

- Onfido SDK
Onfido SDK 5.11.0

- OS
Any desktop OS

- Browser
Any desktop browser

- Device
Any mobile phone

- Node
- Framework or relevant dependencies (if applicable)

### Integration configuration:

Please see above for configuration and reproduction instructions

### Steps to reproduce:

Please see above for configuration and reproduction instructions

**Comment by gurpreetburmi** [comment]
Hello there!

Thank you for bringing this up. The SMS_BODY is not customizable, since it is set on the back end unlike the rest of the SDK UI.

We have raised an engineering ticket to have it removed from the locale JSON files in our next release to avoid confusion.

Let us know if there is anything else we can assist you with. 

Kind regards,
Gurpreet Singh
