### ISSUE TITLE
Onfido loaded in modal should not tinker with history state

### ISSUE THREAD

**Issue by afkatja** [onfido/onfido-sdk-ui#1209]
### What was the expected behaviour?
When loaded in a modal, Onfido component should not impact history state

### What happened instead?
History state is set to `{flow: "captureSteps", step: 0}`

### Version info:

- Onfido SDK
5.13.0
- OS
Mac OS X
- Browser
Chrome 86.0.4240.75 (Official Build) (x86_64)
- Device
- Node
- Framework or relevant dependencies (if applicable)
React 16.13.1
React Router Dom 4.3.1

### Integration configuration:
````
this.onfido.init({
        ...
        token: this.onfidoToken,
        containerId: "onfido-mount",
        useModal: showModal,
        isModalOpen: showModal,
        onModalRequestClose: () => {
          this.onfido.setOptions({ isModalOpen: false });
          if (onModalClose) onModalClose();
        },
        steps,
        onComplete: data => {
          try {
            const requestData = { facialReportVariant: data.face.variant };
            ...
          } catch (err) {
            ...
          }
        },
      });
````
in the parent project we set `showModal` to initialize Onfido component.

**Comment by stefaniacardenas** [comment]
Hi @afkatja, if my understanding is correct you might be having the issue described in the troubleshooting part of our docs.
> In rare cases, the SDK back button might not work as expected within the application history. This is due to the interaction of history/createBrowserHistory with the browser history API. If you notice that by clicking on the SDK back button, you get redirected to the page that preceeded the SDK initialisation, you might want to consider using the following configuration option when initialising the SDK: useMemoryHistory: true. This option allows the SDK to use the history/createMemoryHistory function, instead of the default history/createBrowserHistory. This option is intended as workaround, while a more permanent fix is implemented.

Example:

```
Onfido.init({
  useMemoryHistory: true,
})

Does the suggestion fix your issue? If not, could you share a demo?

**Comment by afkatja** [comment]
hi @stefaniacardenas 
Thank you, this setting seems to help.
