### ISSUE TITLE
Limit upload file types

### ISSUE THREAD

**Issue by FEhao** [onfido/onfido-sdk-ui#1210]
### What was the expected behaviour?

With certain config, user can only upload image file. 
Is this feature supported?

### What happened instead?

PDF file can be uploaded and previewed.

### Version info:

- Onfido SDK
- OS
- Browser
- Device
- Node
- Framework or relevant dependencies (if applicable)

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

Please describe in as much detail as possible how to reproduce the problem

### Demo:

If possible, please share a URL or public repository where the issue can be reproduced

**Comment by andra-radu** [comment]
Hi @FEhao,

Thank you for getting in contact with us. 

Valid file formats for documents are jpg, png and pdf. The file size must be between 32KB and 10MB. This information can be found on our documentation here: https://documentation.onfido.com/#upload-document 
If you have any questions or concerns please do not hesitate to contact me. I would be more than glad to assist you. 

Kind regards, 
Andra

**Comment by FEhao** [comment]
> Hi @FEhao,
> 
> Thank you for getting in contact with us.
> 
> Valid file formats for documents are jpg, png and pdf. The file size must be between 32KB and 10MB. This information can be found on our documentation here: https://documentation.onfido.com/#upload-document
> If you have any questions or concerns please do not hesitate to contact me. I would be more than glad to assist you.
> 
> Kind regards,
> Andra

Hi @andra-radu 
Thanks for your quick reply, so is there any config option that can restrict file format? For example, with { limit: ['png', 'jpg'] }, users will not be enabled to upload PDF files, or there'll be error tips after uploading.

**Comment by andra-radu** [comment]
Hi @FEhao,

You are always welcome. Unfortunately, there is no way to restrict file format, but what you can do is to use consider “forcing x-device” so that applicant always end up using the phone to take pictures of their documents. 
If you have any questions or concerns please do not hesitate to contact me. I would be more than glad to assist you.

Kind regards,
Andra

**Comment by FEhao** [comment]
> Hi @FEhao,
> 
> You are always welcome. Unfortunately, there is no way to restrict file format, but what you can do is to use consider “forcing x-device” so that applicant always end up using the phone to take pictures of their documents.
> If you have any questions or concerns please do not hesitate to contact me. I would be more than glad to assist you.
> 
> Kind regards,
> Andra

👌 thanks
