### ISSUE TITLE
Onfido back button umounts the app in react

### ISSUE THREAD

**Issue by EFXPROMedia** [onfido/onfido-sdk-ui#1231]
### What was the expected behaviour?

Within the Onfido sdk ui when clicking the back button we should go back one step in the process.

e.g Asked to do ID check, clicked on "Passport" and on the passport upload we click back (onfido-sdk-ui-NavigationBar-back onfido-sdk-ui-NavigationBar-backHoverDesktop) in the top left of the app (onfido-sdk-ui-Modal-inner) it clears the containerId html entirely.

### What happened instead?

it clears the target **containerId** html entirely.

### Version info:

- Onfido SDK 6.2.0
- OS Mac
- Browser Chrome & all others
- Device Macbook Pro
- Node v10.15.1
- Framework or relevant dependencies (if applicable) React

### Integration configuration:

In React initiated in an useEffect:

  ```javascript
const initOnfido = async () => {
    // setLoading(true);  // breaks the init call and nothing loads in the onfido-target
    const {
      name,
      surname,
      dob,
      address,
    } = values(provider);
    // setLoading(true);
    const token = await generateOnfidoToken(name, surname, dob, address);

    const { init } = await import('onfido-sdk-ui'); // v6.2.0

    init({
      useModal: false,
      token,
      steps,
      containerId: 'onfido-target',
      onComplete: onfidoOnComplete({
        addressCheckRequired,
        identityCheckRequired,
        setLoadingModalOpen,
        setTimeoutModalOpen,
        setRedirectCode,
        history,
      }),
    });
    // setLoading(false); // doesn't work
  };
  ```

### Steps to reproduce:
1. The back button once clicked unmount the "containerId" content from the DOM.

2. The Onfido content should execute inside the specified "containerId" but currently failing if added an event before it is executed, just like the code example above if I call setLoader(), init() doesn't seem to execute.

**Comment by ethan605** [comment]
Hi @EFXPROMedia, thanks for raising the issue to us.

We've tried to reproduce this scenario but unable to get the bug you said. Some extra questions to clarify:
- What exactly `setLoading` does? At our end, we tried with `console.log`, `setState` hook and other normal logic and it seems to work normally.
- Can you provide the code inside `useEffect()` that you loaded the SDK?
- Where did you put the div with `#onfido-target` inside the React DOM?

Thanks for your cooperation!

**Comment by EFXPROMedia** [comment]
Hi @ethan605,

We managed to fix the problem adding, `useMemoryHistory: true`, to the init({...options});

Still we get an alert saying that only one useHistory should be used, I cant say for sure this is related to the Onfido SDK.
