### ISSUE TITLE
Migration guide does not match the actual locales

### ISSUE THREAD

**Issue by bear-in-a-box** [onfido/onfido-sdk-ui#1234]
### What was the expected behavior?

Migration guide's sections _Added strings_ and _Changed strings_ match existing locales.

### What happened instead?

Terms mentioned in the migration guide do not exist in e.g. en_US.json file, making their meaning unclear.

Examples:
- there is no `country_selection` context
- there is no `document_selector` context

### Version info:

- Onfido SDK 5.1.0 -> 6.x.x (migration)
- OS N/A
- Browser N/A
- Device N/A
- Node N/A
- Framework or relevant dependencies (if applicable) N/A

### Integration configuration:

N/A

### Steps to reproduce:

See the links attached.

### Demo:

EN-US locale: https://github.com/onfido/onfido-sdk-ui/blob/6.2.0/src/locales/en_US/en_US.json
Migration guide: https://github.com/onfido/onfido-sdk-ui/blob/6.2.0/MIGRATION.md

**Comment by ethan605** [comment]
Hi @bear-in-a-box, thanks for your question.

In fact, we had [a breaking change in `v6.1.0`](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.1.0), which means you need to consume the [`migrate_locales` script](https://github.com/onfido/onfido-sdk-ui/blob/6.2.0/MIGRATION.md#introduce-migrate_locales-script) first, then you can upgrade to `v6.2.0` without problems.

**Comment by bear-in-a-box** [comment]
Hi, thank you for your reply.
So, just to be clear, all the missing definitions are added by the script automatically? I have a custom solution for creating JSON files because of the workflow with translators. It'd be easier to look up the definitions before migrating.

**Comment by ethan605** [comment]
Hi @bear-in-a-box, yes, the migration script will automatically update the key names for you.
If you have customised locale translations, please follow [the instruction](https://github.com/onfido/onfido-sdk-ui/blob/6.2.0/MIGRATION.md#introduce-migrate_locales-script) to migrate them. All questions are welcome.

Thanks!
