### ISSUE TITLE
Contributors guidelines

### ISSUE THREAD

**Issue by swervo** [onfido/onfido-sdk-ui#1260]
### What was the expected behaviour?

That I would be able to see something when I follow the contributors guidelines here:

https://github.com/onfido/onfido-sdk-ui/blob/master/CONTRIBUTING.md

My objective is to get it running to I can get to grips with the architecture and see what options I have for creating a bespoke branded version for a customer. I notice that the jsfiddle version works without requiring any tokens.

### What happened instead?

There is a blank screen at https://localhost:8080 and if I look in the console there is a message:

`response: "{"message":"Something went wrong"}`

This appears to be coming from `demoUtils.js` and I suspect this is because I don't have an `SDK_TOKEN_FACTORY_SECRET` set. Maybe this is obvious but I can't see how to get any further forward with this.

I don't have an account and, looking at the Onfido site here: https://onfido.com/ it's not obvious how to create one.

If I could get a little help on how to get started here I would really appreciate it.

### Version info:

- Onfido SDK = 6.3
- OS = Mac OS 10.15.7
- Browser = Chrome
- Device = MacBook Pro
- Node = v14.15
- Framework or relevant dependencies (if applicable) N/A

### Integration configuration:

N/A

### Steps to reproduce:

Clone the repo, run `npm i`, run `npm run dev`, open localhost:8080

### Demo:

N/A

**Comment by kopijunkie** [comment]
Hi @swervo 

We're reviewing our documentation and sample app internally to make it easier/clearer for external contributors to get up & running locally, particularly with the SDK token generation step. 

For help on how to generate an SDK token for your own integration, please refer to the API reference documentation here https://documentation.onfido.com/#generate-sdk-token

**Comment by dominic-butlerSFDC** [comment]
@stefaniacardenas understood. Thank-you. You may close the issue if you wish.

**Comment by stefaniacardenas** [comment]
Thank you. Closing this now.
