### ISSUE TITLE
Proof of Address as single step causes onfido-sdk-ui to display blank screen.

### ISSUE THREAD

**Issue by blackjable-waracle** [onfido/onfido-sdk-ui#1261]
### What was the expected behaviour?

Proof of Address UI displayed to user

### What happened instead?

OnFido container displays blank screen and there is a javascript null reference exception

### Version info:

- Onfido SDK: 6.3.0
- OS: macOS Catalina 10.15.7 (19H2)
- Browser: Chrome Version 86.0.4240.111 (Official Build) (x86_64)
- Device: MacBook Pro
- Node: v12.14.1
- Framework or relevant dependencies (if applicable): React 16.10.2

### Integration configuration:

`const step = {
    type: 'poa',
    options: {
      documentTypes: {
        bank_building_society_statement: true,
        council_tax: true,
        utility_bill: true,
        benefit_letters: false,
      },
    },
  };`

### Steps to reproduce:

Launch SDK with steps that do not include either:

- welcome
- document

### Demo:

No demo possible

### Additional

If i'm reading the code correctly, then from v6.2.0 to v6.3.0 there was (in amongst other things) the following block of code:

https://github.com/onfido/onfido-sdk-ui/blob/master/src/components/Router/index.js#L516-L534

When this code executes the attempt to find a 'document' step will fail if the only supplied step is of type 'poa'.

Line of code we think is causing failure (actual runtime exception being thrown by next line):

https://github.com/onfido/onfido-sdk-ui/blob/master/src/components/Router/index.js#L518

On my local build of onfido-sdk-ui, i've added 'poa' as an additional predicate, which appears to avoid the null reference being thrown.

Alternatively, it might be possible to void changing the predicate by adding an optional chaining operator to line https://github.com/onfido/onfido-sdk-ui/blob/master/src/components/Router/index.js#L519

Hope this is enough information.

**Comment by kopijunkie** [comment]
Thank you for the detailed information @blackjable-waracle 

Was investigating this separately before seeing this & I agree that is block of code that is causing the error. Have raised an internal ticket to have this issue fixed.

**Comment by kopijunkie** [comment]
Hi @blackjable-waracle 

We have just released [6.4.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.4.0) which includes the fix for this issue. I'll close this issue for now, but do re-open & let us know if you are still having issues after upgrading.
