### ISSUE TITLE
Country selection not displaying

### ISSUE THREAD

**Issue by EFXPROMedia** [onfido/onfido-sdk-ui#1262]
### What was the expected behaviour?

Onfido check object format:

`type: 'document',
    options: {
      documentTypes: {
        passport: true,
        driving_licence: true,
        national_identity_card: false,
      },
    },`

I also tried adding `showCountrySelection: true` to the options object but the behaviour still remains the same.

# Should provide a a list of addresses to select.

### What happened instead?

No dropdown displayed.

### Version info:

- Onfido SDK 6.3.0
- OS mac Catalina
- Browser Chrome 70
- Device
- Node 11
- Framework or relevant dependencies (if applicable) React

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

Initiate the Onfido "document" type check, click driver's license (country selection)

### Demo:

Not possible.

**Comment by ethan605** [comment]
Hi @EFXPROMedia we've already addressed this issue and will fix it soon.

**Comment by NTag** [comment]
We had the same issue…

**Comment by gurpreetburmi** [comment]
Hi all, we have rolled out a patch release containing the fix. Please upgrade to this latest release: https://github.com/onfido/onfido-sdk-ui/releases/tag/6.3.1 and this should resolve the issue.

Thank you so much for your time and cooperation, we appreciate it.

**Comment by lortabac** [comment]
Hello, I have the same bug in 6.7.0 and 6.8.0. I haven't tested on previous versions.
If the document-type property is set to `true` (ex. `{ documentTypes: { driving_licence: true, national_identity_card: true }`) the country-selection screen does not appear (it does appear if I set invalid values such as `null` or `1`).

**Comment by kopijunkie** [comment]
Hi @lortabac 

Thank you for raising this. It looks like it is a recent regression introduced in 6.6.0, I will raise a ticket internally to have this fixed. Feel free to open a separate issue for this if you'd like to be able to track when the fix is released.

**Comment by lortabac** [comment]
@kopijunkie I opened a new issue here: https://github.com/onfido/onfido-sdk-ui/issues/1444
