### ISSUE TITLE
Proof of Address - Final Release?

### ISSUE THREAD

**Issue by KarunaGovind** [onfido/onfido-sdk-ui#1265]
Hi. Is there an ETA for when POA is supposed to come out of beta?

Thanks.

**Comment by stefaniacardenas** [comment]
Hi @KarunaGovind, we don't have a date for a final release yet. I can keep this ticket open and let you know once we decide to release the PoA feature as stable.

**Comment by ravinpatel** [comment]
@stefaniacardenas are there any updates on the release for POA?

**Comment by ravinpatel** [comment]
Any updates on this?
