### ISSUE TITLE
Issuing country for non-passport documents always asked 

### ISSUE THREAD

**Issue by krimsz** [onfido/onfido-sdk-ui#1272]
### What was the expected behaviour?

When configuration states that for some documents the country is set either for a specific country or null, the country selection step should be skipped as indicated in the documentation

### What happened instead?

The country selection screen is always shown

### Version info:
- Onfido SDK 6.3.1 (installed through NPM)
- Google Chrome 87.0.4280.67
- MacBook Pro. Catalina 10.15.7 

### Steps to reproduce:

initialize the plugin with 
```
init({
      ....
        documentTypes: { 
          passport: true, 
          national_identity_card: {
            country: null
          },
          driving_licence: {
            country: null
          }
        },
     ....
}
```

**Comment by krimsz** [comment]
If it helps, this was already not working in previous versions. We were waiting for the fix for country selection not showing at all to see if this could have been a related issue.

The versions we tried and could reproduce this in the past were
```
6.2.0
6.3.0
6.3.1
```

**Comment by stefaniacardenas** [comment]
Hi @krimsz, are you passing those configuration inside the document step? From the code you copy pasted it looks like you added those configuration outside of the document options. Please use the following snippet as an example
```
Onfido.init({
  steps: [
    'welcome',
    {
      type: 'document',
      options: {
        documentTypes: {
          passport: true,
          national_identity_card: {
            country: null,
          },
          driving_licence: {
            country: null,
          },
        },
      },
    },
    'face',
    'complete'
  ]
})

**Comment by krimsz** [comment]
Hey sorry for the late reply here.  Thanks a lot, indeed the issue was with the level of nesting of the configuration for this, confirmed it skips the screen in the latest version

Thanks a lot for the help and sorry for my misunderstanding
