### ISSUE TITLE
Onfido gets stuck and for passport document three times rather than passport, ID, driving_licence

### ISSUE THREAD

**Issue by fadisdh** [onfido/onfido-sdk-ui#1307]
Using the below as `steps` in the configuration:

```
[{"type":"welcome","options":{"title":"Verify your BitOasis account","description":["To open BitOasis account for trading, we will need to verify your identity.","It will only take a couple of minutes."]}},{"type":"document","options":{"documentTypes":{"passport":true}}},{"type":"document","options":{"documentTypes":{"national_identity_card":true}}},{"type":"document","options":{"documentTypes":{"driving_licence":true}}},"face","complete"]
```

### What was the expected behaviour?

ASk for a passport in step 2, ID in step 3, and driving_licence is step 4.

### What happened instead?

ASked for passport three times

Please detail what the actual behaviour was

### Version info:

- Onfido SDK: 6.4.0
- OS: Mac 11.0.1
- Browser: Google Chrome
- Device: Desktop / Using the mobile link (iOS 14)
- Node: NA
- Framework or relevant dependencies (if applicable): on Angular 7 application

### Integration configuration:

Using the below steps in configration:

```
[{"type":"welcome","options":{"title":"Verify your BitOasis account","description":["To open BitOasis account for trading, we will need to verify your identity.","It will only take a couple of minutes."]}},{"type":"document","options":{"documentTypes":{"passport":true}}},{"type":"document","options":{"documentTypes":{"national_identity_card":true}}},{"type":"document","options":{"documentTypes":{"driving_licence":true}}},"face","complete"]
```

**Comment by kopijunkie** [comment]
@fadisdh The SDK is designed to only handle 1 document step per IDV flow. If you would like to have the user submit 3 document types you will need to reset the SDK after each document step. Please refer to the `README` section for [Removing the SDK](https://github.com/onfido/onfido-sdk-ui#removing-the-sdk) for how to teardown the SDK. Then reinitialise the SDK configured for the next document type step.
