### ISSUE TITLE
Minor typo in en_US localisation (maybe)

### ISSUE THREAD

**Issue by wijnbladh** [onfido/onfido-sdk-ui#1309]
Just browsing the code and comparing with previous versions, this happened to catch my eye in _en_US.json_

`...`
`"info": "Make sure§",`
`...`

Not sure but that might look like a translator-induced typo.

Cheers!

-V-

**Comment by gurpreetburmi** [comment]
Hello there!

Thank you for bringing this up. 

I will share this feedback with the team and we will get this addressed. 

Kind regards,
Gurpreet Singh

**Comment by gurpreetburmi** [comment]
Hello there!

A fix for the same has now developed and we will fix it in the next release.

Kind regards,
Gurpreet Singh

**Comment by stefaniacardenas** [comment]
Hi @wijnbladh, the issue has been fixed in version [6.5.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.5.0). Thanks for reporting it.
