### ISSUE TITLE
Serving over HTTP on local network shows Unsupported browser error

### ISSUE THREAD

**Issue by wijnbladh** [onfido/onfido-sdk-ui#1318]
### What was the expected behaviour?

- Onfido JS client deployed as part of a template rendered by a web server in local area network (http/8000)
- Open the Onfido powered page, served by the above server, in a mobile device in the same network (i.e. directly, no cross-device)
- (expected) Onfido client loads and verification process can be started

### What happened instead?

- Onfido client shows an error about an unsupported browser (iOS14/Safari, Android10/Chrome, Android9/Chrome&Firefox, among others)
- Apparently this happens because the page is served via http rather than https
- Please check, because if this is the case, the error message is kinda misleading

### Version info:

- Onfido SDK: 6.4.0
- OS: See above
- Browser: See above
- Device: See above
- Node
- Framework or relevant dependencies (if applicable)

### Integration configuration:

Seems to depend on `uploadFallback: false` option. Setting it to true removes the problem.

### Steps to reproduce:

See above

### Demo:

n/a

**Comment by wijnbladh** [comment]
Yeah it's ok prod-wise, the problem is that this might confuse developers during the SDK integration. Anyways, maybe it's something that cannot be remedied. Cheers.

**Comment by stefaniacardenas** [comment]
Good point, I will add a note on the documentation to make it clear. Thank you for the feedback. Will close this issue now.
