### ISSUE TITLE
Onfido.init is not a function

### ISSUE THREAD

**Issue by ldco2016** [onfido/onfido-sdk-ui#1322]
### What was the expected behaviour?

Was expecting Onfido.init() to be recognized as a function inside my Onfido component.

### What happened instead?

I continue to get an error in console that says `Onfido.init is not a function`

### Version info:

- Onfido SDK: 6.4.0
- OS: Windows 10
- Browser: Google Chrome
- Device: N/A
- Node: v12.18.0
- Framework or relevant dependencies (if applicable): React v17

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

```
import React, { useEffect } from 'react';
import Button from '@material-ui/core/Button';

const onfidoToken = <my-onfido-jwt>;

export default function Onfido() {
  useEffect(() => {
     if(onfidoToken) {
        Onfido.init({
           token: onfidoToken,
           containerEl: <div id="root"></div>,
           onComplete: function(data) {
               console.log('everything is complete');
           }
        });
     }
  }, []);

   return (
       <React.Fragment>
           <Button>Press here if you like Onfido</Button>
       </React.Fragment>
   );
}
```

### Steps to reproduce:

Create a boilerplate React application and then add `Onfido.js` to `components/` folder and add the following code above.

**Comment by josokinas** [comment]
Your function name matches the `Onfido` library name, that's why it tries to look up for `init` within your local function.

You should rename it to something else.

See this playground: https://stackblitz.com/edit/onfido-sdk-ui-react

Or [Onfido sample React app](https://github.com/onfido/onfido-sdk-web-sample-app/tree/master/src/react).

**Comment by ldco2016** [comment]
Thanks Justin, this is helpful.

Before I close this out. I wanted to trouble you with something else. I am working on an unfamiliar architecture where Onfido SDK UI captures images and sends to Onfido along with SDK token which has the applicant_id embedded in it.

Does that mean I have to add the property of `applicant_id` into `OnfidoSDK.init()` like so:

```
useEffect(() => {
  if (onfidoToken) {
    OnfidoSDK.init({
       token: onfidoToken,
       applicant_id: onfidoApplicantId
       containerId: "_marketing=dev-root",
    });
  }
}, []);
```

Or does that mean it is already included in that `onfidoToken`, the `applicant_id` that is?

**Comment by josokinas** [comment]
I do not work with this library TBH, but to my understanding you _do not need_ to include applicant ID, the JWT token is associated with the applicant that is being created (probably on your backend).

I don't understand your CORB issue, that sounds like something a browser specific, maybe you will find answer here: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

Best of luck!

**Comment by ldco2016** [comment]
@josokinas , thank you for all your help.

**Comment by stefaniacardenas** [comment]
For future reference, I just want to confirm what @joninvski mentioned. You don't need to pass `applicant_id` to the SDK initialisation function. You need to create the JWT token from your back-end server and pass the token to the SDK.

Are you still getting the CORB issue? If so, could you screenshot the errors?

**Comment by ldco2016** [comment]
I am getting the CORB warning, but it does not seem to be blocking my ability to send documents. At this point, our blocker is not getting any kind of confirmation that we can use to send a subsequent request to another API. I shared more detail with you here: https://github.com/onfido/onfido-sdk-ui/issues/1331
