### ISSUE TITLE
401 Unauthorized when submitting drivers license

### ISSUE THREAD

**Issue by ldco2016** [onfido/onfido-sdk-ui#1327]
### What was the expected behaviour?

I was expecting to get back some data structure after submitting a practice UK drivers license.

### What happened instead?

Instead I got a prompt saying "Make sure your license details are clear to read, with no blur or glare" and in console I got the following errors:

POST https://edge.api.us.onfido.com/v3/documents - 401 Unauthorized
POST https://sentry.io/api/109946/store/?sentry_key=6e3dx0.... - 429 Too many requests.

And this happens inside of Firefox, when I submit the same UK fake drivers license inside of Chrome, I get a CORB error.

### Version info:

- Onfido SDK - version 6.4.0
- OS - Windows 10
- Browser - Chrome 83 / Firefox
- Device
- Node - v12.18.0
- Framework or relevant dependencies (if applicable) - React 17

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

```
import React, { useEffect } from 'react';
import * as OnfidoSDK from 'onfido-sdk-ui/dist/onfido.min.js';

useEffect(() => {
  if (onfidoToken) {
    OnfidoSDK.init({
       token: onfidoToken,
       applicant_id: onfidoApplicantId
       containerId: "_marketing=dev-root",
    });
  }
}, []);
```

### Steps to reproduce:

you can manually create a react app by creating a folder then running, `npm init -y` and adding the following packages:

```
"onfido-sdk-ui": "6.4.0",
"react": "17.0.1",
"react-router-dom": "5.2.0",
"onfido-sdk-ui": "6.4.0",
"onfido-sdk-ui": "6.4.0",
"onfido-sdk-ui": "6.4.0",
```

devDependencies:

```
"@babel/core": "7.12.13",
"@babel/plugin-transform-runtimei": "7.12.1",
"@babel/preset-env": "7.12.1",
"@babel/preset-react": "7.12.1",
"@webpack-cli/serve": "1.2.2",
"babel-loader": "8.1.0",
"clean-webpack-plugin": "3.0.0",
"css-loader": "5.0.0",
"html-webpack-plugin": "4.5.0",
"style-loader": "2.0.0",
"webpack": "5.4.0",
"webpack-cli": "4.4.0",
"webpack-dev-server": "3.11.0",
"webpack-merge": "5.2.0",
```

The start script will be as follows:

`"start": "webpack serve --config config/webpack.dev.js"`

Then in `webpack.dev.js` you will add the following:

```
const {merge}  = require('webpack-merge');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');
const commonConfig = require('../webpack.common');
const packageJson = require('../package.json');

const devConfig = {
  mode: 'development',
  devServer: {
     port: 8081,
     historyApiFallback: true,
  },
  plugins: [
     new ModuleFederationPlugin({
       name: 'marketing',
       filename: 'remoteEntry.js',
       exposes: {
          './MarketingApp': './src/bootstrap'
       },
       shared: packageJson.dependencies,
     }),
     new HtmlWebpackPlugin({
       template: './public/index.html'
     }),
  ],
};

module.exports = merge(commonConfig, devConfig);
```

The `webpack.common.js` file will look as follows:

```
module.exports = {
   module: {
      rules: [
         {
             test: /\.m?js$/,
             exclude: /node_modules/,
             use: {
                  loader: 'babel-loader',
                  options: {
                     presets: ['@babel/preset-react', '@babel/preset-env'],
                     plugins: ['@babel/plugin-transform-runtime']
                  },
             },
         },
     ],
   },
};
```

You then run `npm start` in the terminal. Please let me know if there is any missing information to reproduce.

### Demo:

If possible, please share a URL or public repository where the issue can be reproduced

**Comment by andra-radu** [comment]
Hi @ldco2016,

401 unauthorised is received when there's is a problem with the token. Can you please check that you've entered a valid application ID when generating the SDK token? 
429 is received when the number of requestes per minute was reached. The maximum rate is 400 requests per minute for live  and 30 requests per minute for sandbox. 
Are you encountering the issue for all documents or just for a specific UK driver license?
Could you please share with us the email address associated with your Onfido account at api@onfidol.com referencing https://github.com/onfido/onfido-sdk-ui/issues/1327? This will help us investigate the logs. 

Thank you,

**Comment by ldco2016** [comment]
@andra-radu , do I need to create a new `applicant_id` everytime I generate a new `sdk_token`? I have been using the same `applicant_id`, but generating a new `sdk_token`.

**Comment by andra-radu** [comment]
@ldco2016, you can use the same applicant but please make sure that you use the same API token for applicant creation as well as for the SDK token.

**Comment by ldco2016** [comment]
@andra-radu , okay so I am using the same applicant id and the same API token for applicant creation and I am still getting that 401 unauthorized.

**Comment by andra-radu** [comment]
@ldco2016 Could you please share with us the applicant id so that I can analyse  the logs?

**Comment by ldco2016** [comment]
`Id: "66ceec5e-3d99-4480-9391-ge17b5b9ce7f"`

**Comment by andra-radu** [comment]
@ldco2016 I have checked in our database and there is no applicant associated with the id "66ceec5e-3d99-4480-9391-ge17b5b9ce7f"
Could you please try double check the applicant id or try to create a new one? Also what referrer are you using when generating the SDK token?

**Comment by ldco2016** [comment]
@andra-radu ,

I created a new `applicant_id`, It is:

`d8fc2188-8ef5-4dd0-b78e-dd92999e01f5`, please try checking this one.

**Comment by andra-radu** [comment]
@ldco2016 

I was able to find applicant_id: 66ceec5e-3d99-4480-9391-9e17b5b9ce7f for which I can see some 422 ApiError::ValidationError when generating the SDK token and then you were able to successfully generate the SDK token.
On the 02/02/2021 22:57:39.235 The quality of the doc was checked and was good but after that I'm unable to see the check creation in the logs. 

For applicant id 'd8fc2188-8ef5-4dd0-b78e-dd92999e01f5'  I can see the  applicant creation and the SDK token generation but no documents uploaded. 

I was unable to find in the logs any 401 authorization errors.

I can see that you are using the referrer http://localhost:8081/, you can always try to use the following regex `*://*/*` as the referrer. 

Can you please share with us the code where you are uploading the docs and creating the check?

Also, have you tried our sample app https://github.com/onfido/onfido-sdk-web-sample-app/ ? Are you encountering the same issue?

**Comment by ldco2016** [comment]
@andra-radu ,

When I used your Regex, I no longer got your 401 Unauthorized, but I was also expecting to get back some data structure although I am aware I might not get anything back. Anyway, I used `applicant_id` of `d8fc2188-8ef5-4dd0-b78e-dd92999e01f5`, could you check on that?

**Comment by andra-radu** [comment]
@ldco2016

For applicant_id d8fc2188-8ef5-4dd0-b78e-dd92999e01f5 I can see that you've successfully created a check containing a document report. Initially, you've received a 422 because you've tried two create a check with two reports, document report and facial similarity photo, but you haven’t provided a selfie, therefore the 422.

**Comment by stefaniacardenas** [comment]
Closing the issue for inactivity. If you are still facing problems with the above, feel free to get in touch at client-support@onfido.com.
