### ISSUE TITLE
onComplete function not working

### ISSUE THREAD

**Issue by ldco2016** [onfido/onfido-sdk-ui#1331]
### What was the expected behaviour?

I was hoping that upon implementing this:

```
export default function() {
   useEffect(() => {
    if (onfidoToken)
      OnfidoSDK.init({
        token: onfidoToken,
        containerId: "root",
        onComplete: function(data) {
           console.log('everything is complete');
        }
      });
  }, []);
}
```

I would get a console log of everything is complete. Eventually I want to throw in the request to this other third party API there.

### What happened instead?

Instead, what happened is I submitted the drivers license example photo and thats it. I did not get a console log or anything indicating it was successfully submitted.

Please detail what the actual behaviour was

### Version info:

- Onfido SDK - 6.4.0
- OS - Windows 10
- Browser - Chrome 83
- Device
- Node - 12.18.0
- Framework or relevant dependencies (if applicable) - React v17

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

```
import React, { useEffect } from 'react';
import * as OnfidoSDK from 'onfido-sdk-ui/dist/onfido.min.js';
import "onfido-sdk-ui/dist/style.css";

export default function() {
   useEffect(() => {
    if (onfidoToken)
      OnfidoSDK.init({
        token: onfidoToken,
        containerId: "root",
        onComplete: function(data) {
           console.log('everything is complete');
        }
      });
  }, []);
}
```

Steps to reproduce:

you can manually create a react app by creating a folder then running, npm init -y and adding the following packages:

```
"onfido-sdk-ui": "6.4.0",
"react": "17.0.1",
"react-router-dom": "5.2.0",
"onfido-sdk-ui": "6.4.0",
"onfido-sdk-ui": "6.4.0",
"onfido-sdk-ui": "6.4.0",
devDependencies:

"@babel/core": "7.12.13",
"@babel/plugin-transform-runtimei": "7.12.1",
"@babel/preset-env": "7.12.1",
"@babel/preset-react": "7.12.1",
"@webpack-cli/serve": "1.2.2",
"babel-loader": "8.1.0",
"clean-webpack-plugin": "3.0.0",
"css-loader": "5.0.0",
"html-webpack-plugin": "4.5.0",
"style-loader": "2.0.0",
"webpack": "5.4.0",
"webpack-cli": "4.4.0",
"webpack-dev-server": "3.11.0",
"webpack-merge": "5.2.0",
```

The start script will be as follows:

`"start": "webpack serve --config config/webpack.dev.js"`

Then in `webpack.dev.js`  for both `container/` and `marketing/` you will add the following:

```
const {merge}  = require('webpack-merge');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');
const commonConfig = require('../webpack.common');
const packageJson = require('../package.json');

const devConfig = {
  mode: 'development',
  devServer: {
     port: 8081,
     historyApiFallback: true,
  },
  plugins: [
     new ModuleFederationPlugin({
       name: 'marketing',
       filename: 'remoteEntry.js',
       exposes: {
          './MarketingApp': './src/bootstrap'
       },
       shared: packageJson.dependencies,
     }),
     new HtmlWebpackPlugin({
       template: './public/index.html'
     }),
  ],
};

module.exports = merge(commonConfig, devConfig);
```

The `webpack.common.js` file for `marketing/` will look as follows:

```
module.exports = {
   module: {
      rules: [
         {
             test: /\.m?js$/,
             exclude: /node_modules/,
             use: {
                  loader: 'babel-loader',
                  options: {
                     presets: ['@babel/preset-react', '@babel/preset-env'],
                     plugins: ['@babel/plugin-transform-runtime']
                  },
             },
         },
         {
             test: /\.(css)$/,
             use: ['style-loader', 'css-loader']
         }
     ],
   },
};
```

While for `container/` it will look as follows:

```
module.exports = {
   module: {
      rules: [
         {
             test: /\.m?js$/,
             exclude: /node_modules/,
             use: {
                  loader: 'babel-loader',
                  options: {
                     presets: ['@babel/preset-react', '@babel/preset-env'],
                     plugins: ['@babel/plugin-transform-runtime']
                  },
             },
         },
     ],
   },
};

```

**Comment by stefaniacardenas** [comment]
Hi, I can see you are not passing the array of steps so you are using the default steps array. The `onComplete` callback is returned at the end of the flow, so in this case it will be triggered after you upload both the document and face capture and you reach the `'complete'` step. If you are expecting the callback after you uploaded the document then you should only include the document step within the array. You can reinitialise the SDK with a different step afterwards. I hope this helps.

**Comment by ldco2016** [comment]
@stefaniacardenas , can you direct me to the documentation that illustrates the array of steps you are referring to?

**Comment by stefaniacardenas** [comment]
Sure, go to the [Customising the SDK](https://github.com/onfido/onfido-sdk-ui#customising-the-sdk) under `steps`.

**Comment by ldco2016** [comment]
@stefaniacardenas ,

So based on what you shared I put this together just as a boilerplate:

```
export default function() {
  useEffect(() => {
     if (onfidoToken) {
        console.log('this is working');
        OnfidoSDK.init({
           token: onfidoToken,
           containerId: "root",
           steps: [
                {
                    type: 'welcome',
                    options: {
                        title: 'Open your new bank account',
                    },
                },
                'document'
           ],
           onComplete: function(data) {
                console.log('is this working?');
           }
        });
     }
  }, []);
}
```

Unfortunately, once the document is successfully submitted I get no console log from that `onComplete`. What I am trying to do here is get some kind of confirmation back that the sent document was successful because I have to then make a follow request to another API.

**Comment by stefaniacardenas** [comment]
Your code works fine for me. Check out [this example](https://stackblitz.com/edit/onfido-sdk-ui-react-6zc33q?embed=1&file=onfido.js).

**Comment by ldco2016** [comment]
@stefaniacardenas , so you are getting back that console log from `onComplete`? I ask because I have tried it again and I am not getting anything in console once the document is submitted. I get that pulsating circle that shows it is processing the submitted document and then it stops, not even something that says your document has been successfully submitted, no console log no indication except that cookie I can see when I go into network requests.

**Comment by ldco2016** [comment]
Oh interesting behavior. If I refresh my app launch Onfido and submit document, I get nothing back as I have been reported, but if I click submit document again without refreshing my app. I do get the console log of everything is complete.

**Comment by stefaniacardenas** [comment]
> I get that pulsating circle that shows it is processing the submitted document and then it stops, not even something that says your document has been successfully submitted, no console log no indication except that cookie I can see when I go into network requests.

This is because you don't have any step after the 'document' step. If you put the 'complete' step at the end of the array you will see the complete screen. 

> I also tried your sample app and on that one I keep getting connection lost.

You need to assign a valid token to the `onfidoToken` variable.

> I want to say the problem could be having it inside that useEffect hook, but that same logic has been working for you guys

How are you importing the function where you initialise the SDK?

**Comment by ldco2016** [comment]
@stefaniacardenas , the issue was. I had banner blindness, meaning after I would upload the front of the drivers license, I did not realize it was then asking for the back of the drivers license. Once I would upload the back of the drivers license then I would see the `onComplete` function console log.

Thank you so much for your help, patience and time. I will close this out.
