### ISSUE TITLE
Typescript + local language

### ISSUE THREAD

**Issue by javlund** [onfido/onfido-sdk-ui#1338]
Hi there,

Just updated the SDK from 6.0.0 to 6.5.0 and I see that TypeScript is now supported, which is really nice. However, we're using a custom locale (Danish) and are supplying our own phrases file. That doesn't work out as expected:

### What was the expected behaviour?

I could choose some value in `locale` for non-default languages.

I would see my phrases being throughout the flow.

### What happened instead?

I can only choose default locales as a value for `locale`, or `undefined` - otherwise it won't compile.

When choosing `undefined` for `locale`, the welcome page is translated, but further pages are in English.

### Version info:

- Onfido SDK: 6.5.0
- OS: Win10
- Browser: Chrome
- Device: PC

### Integration configuration:

```js
      language: {
        phrases,
      },
      smsNumberCountryCode: 'DK',
      steps: [
        'welcome',
        {
          type: 'document',
          options: {
            documentTypes: {
              passport: true,
              driving_licence: true,
              national_identity_card: false,
            },
          },
        },
        {
          type: 'face',
          options: {
            requestedVariant: 'video',
          },
        },
        'complete',
      ],
      onComplete: function (data) {
        console.log(JSON.stringify(data));
        callback();
      }
```

First screen:
![image](https://user-images.githubusercontent.com/1478337/107976590-1dd48800-6fba-11eb-847f-f26aea68a0fd.png)

Next screen:
![image](https://user-images.githubusercontent.com/1478337/107976621-26c55980-6fba-11eb-99ff-52690d72ca95.png)

Bonus question: is it possible to pre-select a default country for proof of identity (but still make it possible for users to select another)? 95+% of our customers are from Denmark, so it would make sense if they didn't have to find Denmark as a country to proceed.

**Comment by ethan605** [comment]
Hi @javlund, can you provide your `phrases` configuration?

> I can only choose default locales as a value for `locale`, or `undefined` - otherwise it won't compile.

What configs worked for you previously?

**Comment by javlund** [comment]
> Hi @javlund, can you provide your `phrases` configuration?
> 
> > I can only choose default locales as a value for `locale`, or `undefined` - otherwise it won't compile.
> 
> What configs worked for you previously?

I just used `da` to symbolize it was Danish. Of course it shouldn't have a real effect, but at least the translation kicked in on all pages, although I got a console error (described by someone else in another issue, which apparently should be resolved now).

**Comment by javlund** [comment]
Oh, and the `phrases` file is basically the original JSON file for English with the phrases that we use translated to Danish. Do you want it pasted in here? It's somewhat lengthy and I can't upload it as a file as it's an unsupported file type.

**Comment by javlund** [comment]
... I see now that the format of the phrases file has been changed. That of course makes sense now. My apologies, should have checked.

Still interested in knowing if `undefined` is the correct value for `locale` if the language is custom, though.

**Comment by ethan605** [comment]
> if `undefined` is the correct value for `locale` if the language is custom
Yes, basically it'll fallback to `en_US` if `locale` isn't defined.

> I see now that the format of the phrases file has been changed
I recommend that you could check the [migration script](https://github.com/onfido/onfido-sdk-ui/blob/master/MIGRATION.md#introduce-migrate_locales-script) out to see if it helps.

Btw I'll keep this issue open until you fully resolve your problem with DK locales.

**Comment by javlund** [comment]
OK, great! I wasn't aware of that script.

I've made the file and run the script.

The file I end up with both have a `locale` (which I've set to `da_DK`) and a `phrases` property. In theory I should be able to just import the file as a const named `language` and use like this:
```ts
import { init } from 'onfido-sdk-ui';
import language from 'da_dk.json';

//...

init({
  language,
  // ...
})
```
However, TS won't let me do that of course as the `locale` value of 'da_DK' is not part of its union type. Instead I have to do this:
```ts
import { init } from 'onfido-sdk-ui';
import {phrases} from 'da_dk.json';

//...

init({
  language: {
    phrases
  },
  // ...
})
```
Is this correct or am I missing something? And does that mean that the `locale` value in the JSON file only serves as reference/documentation?

Thanks for helping me out here!

**Comment by ethan605** [comment]
Hi @javlund, does this work for you (in terms of displaying correct localised strings)?

```javascript
init({
  language: {
    phrases
  },
  // ...
})
```

**Comment by javlund** [comment]
> Hi @javlund, does this work for you (in terms of displaying correct localised strings)?
> 
> ```js
> init({
>   language: {
>     phrases
>   },
>   // ...
> })
> ```

Hi @ethan605 - yup, it works for me, thanks for your help! Just curious about whether the `locale` part of the JSON file is usable for anything.

Also, did you see this part?

> Bonus question: is it possible to pre-select a default country for proof of identity (but still make it possible for users to select 
> another)? 95+% of our customers are from Denmark, so it would make sense if they didn't have to find Denmark as a country 
> to proceed.

**Comment by ethan605** [comment]
Hi @javlund, it's nice to hear that it works for you now.

To be clear, the `locale` field is primarily used for _extending_ an already supported set of localisation keys, ie. `en`, `fr`, `de`, `es`. So unless you're intending to reuse one of them and provide a subset of customisation, the `locale` field can be safely omitted.

For your bonus question: we're planning to support that feature in the near future (maybe Q2 or Q3 2021). Please stay updated on the latest announcements.

**Comment by javlund** [comment]
Awesome Ethan, thanks for that answer and your help in solving this. I'll close this issue now then.
