### ISSUE TITLE
pkg manager: "WARN" missing peer dependencies for "@babel/preset-typescript" when upgrading

### ISSUE THREAD

**Issue by tdeedlesATX** [onfido/onfido-sdk-ui#1374]
### What was the expected behaviour?

No package manager warnings around `@babel/preset-typescript` when upgrading to @latest.

### What happened instead?

Many "missing peer" warnings due to `@babel/preset-typescript` .

With the new version I am seeing the following warnings with my dependency manager around the `@babel/preset-typescript` dependency of onfido-sdk-ui

![image](https://user-images.githubusercontent.com/10747365/111183819-51d1a780-857e-11eb-8df4-c0c112f971b9.png)

See [line of diff](https://github.com/onfido/onfido-sdk-ui/pull/1336/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R212)

Was this intentional? Docs mention installation should be a devDependency: https://babeljs.io/docs/en/babel-preset-typescript

### Version info:

- Onfido SDK: 6.6.0
- OS: n/a
- Browser: n/a
- Device: n/a
- Node: 10 
- Framework or relevant dependencies (if applicable): `yarn`

### Integration configuration:

n/a: just when adding onfido-sdk-ui via `yarn add onfido-sdk-ui` 

### Steps to reproduce:

In a terminal:
`yarn add onfido-sdk-ui@latest` 
See install warnings list in terminal

### Demo:

n/a

**Comment by ethan605** [comment]
Hi @tdeedlesATX, thanks for pointing this. Yes it was a mistake. We'll work to move this to `devDependencies` in the next patch fix.

**Comment by ethan605** [comment]
Hi @tdeedlesATX, good news: #1380 has been merged, we're targeting to release `6.7.0` next week.

**Comment by stefaniacardenas** [comment]
Hi @tdeedlesATX, the issue has been fixed in version `6.7.0`.
