### ISSUE TITLE
Typescript error on country: null, to remove country selector

### ISSUE THREAD

**Issue by BoOwnrs** [onfido/onfido-sdk-ui#1379]
### What was the expected behaviour?

In the documentation:
![image](https://user-images.githubusercontent.com/67312358/111603341-88a0fb00-87d4-11eb-8fa8-8e6cc30099c5.png)

But typescript requires a string, so null is no good:
![image](https://user-images.githubusercontent.com/67312358/111603455-aa9a7d80-87d4-11eb-93c1-59d596971f55.png)

### What happened instead?

Either the type should be updated to accept null or the documentation should specify that null is not an option.

### Version info:

- Onfido SDK 6.6.0

### Integration configuration:

options: {
            documentTypes: {
              passport: true,
              driving_licence: { country: null },
              national_identity_card: false,
              residence_permit: false,
            },
          },

### Steps to reproduce:

use the sdk with typescript  :-D

**Comment by ethan605** [comment]
Hi @BoOwnrs, thanks for raising this problem. We already identified it and had [a fix in a feature branch](https://github.com/onfido/onfido-sdk-ui/blob/feature/tsconfig-enable-strict/src/types/steps.ts#L31-L35). We'll try our best to roll out a new release (patch or minor) to fix this.

To quickly get over this error as a workaround, I suggest casting `null as string` temporarily.

**Comment by ethan605** [comment]
Hi @BoOwnrs, the PR to fix this issue has been merged: #1367. We're targeting to release version `6.7.0` next week.

**Comment by stefaniacardenas** [comment]
Hi @BoOwnrs, the issue has been fixed in version `6.7.0`
