### ISSUE TITLE
Missing SA national ID in supported-docs-national_identity_card.json

### ISSUE THREAD

**Issue by foowie** [onfido/onfido-sdk-ui#1401]
Saudi Arabia should be in the https://github.com/onfido/onfido-sdk-ui/blob/master/src/supported-documents/supported-docs-national_identity_card.json as it is presented as available in https://onfido.com/supported-documents

**Comment by ethan605** [comment]
Hi @foowie, thanks for raising this. We're inspecting and will get back to you as possible.

**Comment by kopijunkie** [comment]
@foowie we will be looking to include the updated supported documents country options in a coming release. I'll update you again here once this is done.

**Comment by kopijunkie** [comment]
We've released [`6.8.0`](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.8.0) last week which includes the latest supported documents data as of the time of release and this includes Saudi Arabia national ID card. 

I'll close this ticket for now.
