### ISSUE TITLE
Authorization Failed, Bad Application ID

### ISSUE THREAD

**Issue by doubleprincez** [onfido/onfido-sdk-ui#1405]
### Description of problem
When i'm uploading a new driver's license in sandbox using this package in laravel js folder using
```
    Onfido.init({
            // the JWT token from the PHP laravel layer
            token:  onfidoToken,
            applicant_id:  applicantId,
            // ID of the element you want to mount the component on
            containerId: 'onfidoMount',
            onComplete: (data) => { 
                $.ajax({
                    url: url,
                    type: 'post',
                    data: {data: data},
                    success: function (data) {
                        console.log(data)
                    }
                })
            },
            steps: [
                'welcome',
                'document',
                'face',
                'complete'
            ],
            onError: (exception) => {
                console.log("Onfido error", exception);
            },
            onUserExit: function (userExitCode) {
                console.log(userExitCode)
            },
        });
```
### End result
The api sents a request to this endpoint 
Request URL: https://edge.api.onfido.com/v3/documents
Request Method: POST
Status Code: 401 
Remote Address: #############
Referrer Policy: strict-origin-when-cross-origin

but returns :
``` error:{
fields: {}
message: "Unexpected application_id: , please check the application_id used when generating the token"
type: "bad_application_id"
}
 ```
### Reproduce 
Create a new laravel application and install just this sdk. This is just  a test app on laravel 8 using the onfido api-php-client package as the backend which returns the required results when using postman but will always return bad application Id in this api. 
My package.json only contains these
```
 "devDependencies": {
        "axios": "^0.21",
        "bootstrap": "^4.0.0",
        "jquery": "^3.2",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "popper.js": "^1.16.1",
        "postcss": "^8.2.10",
        "resolve-url-loader": "^3.1.2",
        "sass": "^1.15.2",
        "sass-loader": "^8.0.0"
    },
    "dependencies": {
        "@popperjs/core": "^2.9.2",
        "bootstrap": "^5.0.0-beta2",
        "onfido-sdk-ui": "^6.6.0"
    }
``` 

### Version info:

- Onfido SDK :  6.7.1
- OS:  windows 10
- Browser :chrome
- Device :  laptop
- Node : 6.14.6
- Framework or relevant dependencies (if applicable)
- onfido/api-php-client": "^5.2.0"
- Php 8.0.3

**Comment by doubleprincez** [comment]
checking my console i could see

``` {type: "exception", message: "Unexpected application_id: , please check the application_id used when generating the token"} ```

**Comment by gurpreet-onfido** [comment]
Hello there!

The error message states that there is a problem with the application ID:

{"error":{"type":"bad_application_id","message":"Unexpected application_id: , please check the application_id used when generating the token","fields":{}}}

If you are using the Web SDK, can you please check you are using a referrer and that it is declared properly?

More information can be found here: https://documentation.onfido.com/#generate-sdk-token

Kind regards,
Gurpreet Singh
