### ISSUE TITLE
Broken ES modules import behaviour

### ISSUE THREAD

**Issue by ivmel-ca** [onfido/onfido-sdk-ui#1422]
The package should be imported without errors;

The native import (ES modules) of the package causes an error:
```Uncaught SyntaxError: The requested module '/_snowpack/pkg/custom-event-polyfill.v1.0.7.js' does not provide an export named 'default'```

This indicates that one of your dependencies doesn't provide an 'export default' value, hence the error

### Version info:

- onfido-sdk-ui@6.7.2
- MacOS
- Chrome, Safari , etc.
- MacBook Pro 15 2016
- Node: 10.16.0
- Snowpack + React

### Integration configuration:

```import { init } from 'onfido-sdk-ui';```

### Steps to reproduce:
- install package and try to import init with ES module import.

**Comment by kopijunkie** [comment]
Hi @ivmel-ca 

I was able to reproduce it locally with a simple Snowpack app. Unfortunately I've not found a solution yet and will need to investigate further to find a resolution for this issue for this IE11 polyfill that we are using. I have raised a ticket internally for us to work on a fix for this.

**Comment by ocZio** [comment]
any updates on this?

**Comment by nulrich** [comment]
Hello @ivmel-ca, a [fix](https://github.com/onfido/onfido-sdk-ui/pull/1707) as been released in `6.19.0`. 

I'm closing the issue, but don't hesitate to re-open it if needed.

**Comment by ivmel-ca** [comment]
Hey @andra-radu , @nulrich I have tested out and the error persists. The exact error is:
`The requested module '../_snowpack/pkg/onfido-sdk-ui.v6.19.0.js' does not provide an export named 'init'`

- onfido-sdk-ui@6.19.0
- MacOS
- Chrome, Safari , etc.
- MacBook Pro 15 2016
- Node: 10.16.0
- Snowpack + React

It worth mentioning that default export is working:

`import onfido from 'onfido-sdk-ui';`

but the named export remains broken:
`import {init} from 'onfido-sdk-ui';`
then comes the error

**Comment by stefaniacardenas** [comment]
Hi, have you tried importing the SDK asynchronously?
```
useEffect(() => {
    Onfido = await import('onfido-sdk-ui')
}, [])

```
or
```
async componentDidMount () {
    this.Onfido = await import('onfido-sdk-ui')
}
```

Then 
```
Onfido.init({...}) // or this.Onfido.init({...})

**Comment by stefaniacardenas** [comment]
I see, thanks for clarifying that @ivmel-ca. I can see this issue is mentioned in the [snowpack documentation](https://www.snowpack.dev/reference/common-error-details#uncaught-syntaxerror-the-requested-module-xxxxxxjs-does-not-provide-an-export-named-yyyyyy). I will open a ticket to fix this on our side. In the meanwhile, I would suggest to use the default import as that would only import the IDV library that exports `init`, nothing else, so there shouldn't be any size impact.

**Comment by DannyvanderJagt** [comment]
We've upgraded to webpack 5 internally which should fix this issue. All versions from 6.20.0 and above use webpack 5.

Please upgrade and reopen to issue if it persists.
