### ISSUE TITLE
Security vulnerability on socket.io-client@2.2.0

### ISSUE THREAD

**Issue by ayanozturk** [onfido/onfido-sdk-ui#1424]
https://app.snyk.io/test/npm/onfido-sdk-ui/6.4.0

Vulnerable module: xmlhttprequest-ssl
Introduced through: socket.io-client@2.2.0
Detailed paths
Introduced through: onfido-sdk-ui@6.4.0 › socket.io-client@2.2.0 › engine.io-client@3.3.2 › xmlhttprequest-ssl@1.5.5
Remediation: Upgrade to socket.io-client@4.0.0.
Overview
xmlhttprequest-ssl is a fork of xmlhttprequest.

Affected versions of this package are vulnerable to Access Restriction Bypass. The package disables SSL certificate validation by default, because rejectUnauthorized (when the property exists but is undefined) is considered to be false within the https.request function of Node.js. In other words, no certificate is ever rejected.

**Comment by kopijunkie** [comment]
Hi @ayanozturk 

Thank you for raising this. We also just spotted this security vulnerability & are working to address it in our coming release.

**Comment by kickboxer** [comment]
Have the same problem
![image](https://user-images.githubusercontent.com/7815336/117124544-23639200-ada1-11eb-836e-cc87526f4548.png)

**Comment by kopijunkie** [comment]
We've just release [6.8.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.8.0) which includes the fix to resolve this dependency vulnerability. I will close this for now.
