### ISSUE TITLE
Broken useLiveDocumentCapture

### ISSUE THREAD

**Issue by pedrotorchio** [onfido/onfido-sdk-ui#1442]
### What was the expected behaviour?

Camera is properly centered and takes pictures successfully when useLiveDocumentCapture is true. 

### What happened instead?!

On most of our Android phones (mine is a Pocophone F1, Android 9 PKQ1) the video stream appeared zoomed in and distorted and the final capture was be dislocated/decentralised. The fallback for native camera mode works fine, but decreases our success rates.

On my phone

<img width="337" alt="Screen Shot 2021-05-19 at 14 17 04" src="https://user-images.githubusercontent.com/18075966/118757861-3ef68e80-b8b1-11eb-8f43-be27e67fd639.jpg">
<img width="337" alt="Screen Shot 2021-05-19 at 14 17 04" src="https://user-images.githubusercontent.com/18075966/118757868-3f8f2500-b8b1-11eb-9c15-6198e1c13611.jpg">
<img width="337" alt="Screen Shot 2021-05-19 at 14 17 04" src="https://user-images.githubusercontent.com/18075966/118757857-3dc56180-b8b1-11eb-8107-195b46e3631e.jpg">

On desktop (mobile view)
<img width="337" alt="Screen Shot 2021-05-19 at 14 17 04" src="https://user-images.githubusercontent.com/18075966/118756779-fe961100-b8ae-11eb-873a-84fada94bb22.png">

[Screenshot_2021-05-18-18-21-50-665_com android chrome](https://user-images.githubusercontent.com/18075966/118756696-d4445380-b8ae-11eb-8ed9-bba94b656f64.jpg)

### Version info:

- Onfido SDK 6.8.0
- OS Android 9
- Browser Chrome
- Device Pocophone F1
- Node
- Framework or relevant dependencies (if applicable) VueJs

### Integration configuration:
snippet:

> useModal: false,
> steps: [
>   type: "document",
>   options: {
>     documentTypes: ...,
>     forceCrossDevice: true,
>     **useLiveDocumentCapture: true,**
>     uploadFallback: true
>   },
> ],
> disableAnalytics: true,
> smsNumberCountryCode: this.getConfigValue("smsCountryCode"),

### Steps to reproduce:

Initialise the web sdk with a document with useLiveDocumentCapture set to true and open it on an Android phone

**Comment by aaronchipper** [comment]
Seeing the same behaviour on a number of Android phones.

We're also seeing that the SDK will refuse to accept the image, saying that there is no ID detected in the image. If however we take a picture that does allow for the distorted and off centre preview, then the ID is considered to be detected and it moves on to the selfie capture process.

This is a significant issue for us as it's a blocker for production use. Is there any update on this from @Onfido?

**Comment by kushal-onfido** [comment]
Hi @aaronchipper 

I see that this issue is already known to the SDK team and they are working on its fix. I will let you know once the fix is released. 

Thanks!

**Comment by VanessaFierens** [comment]
@kushal-onfido do you have an update on this?

**Comment by kushal-onfido** [comment]
Hi @VanessaFierens The fix for this issue is in review currently and is expected to be implemented in the next release of the SDK. I will let you know here once the new version is available with the fix of this issue. 

Thanks!

**Comment by dylandamsma** [comment]
I have the same issue here - Android 11 / Oneplus Nord / Brave Browser version 1.26.77 (Chromium 91.0.4472.164)

Using SDK Version 6.10.0

**Comment by kushal-onfido** [comment]
Hello @pedrotorchio @aaronchipper @VanessaFierens @dylandamsma This issue has been fixed in the latest release [6.12.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.12.0). Please upgrade the SDK to 6.12.0 and it should fix the issue.
