### ISSUE TITLE
Country selection is skipped unexpectedly

### ISSUE THREAD

**Issue by lortabac** [onfido/onfido-sdk-ui#1444]
### What was the expected behaviour?

Given the options `documentTypes: { driving_licence: true, national_identity_card: true}` I expected to see the country-selection screen.

### What happened instead?

The country-selection screen was skipped (as if I had set the country property to `{country:null}`).
However setting this property to any other value makes the selection screen appear again.

### Version info:

- 6.7.0/6.8.0
- Linux
- Firefox
- Node 12

### Steps to reproduce:

Start the Onfido document check and click on "driver license".

**Comment by kopijunkie** [comment]
Hi @lortabac 

Just to update you, we have released [6.10.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.10.0) earlier this week which includes the fix for this. 

I'll close this ticket now, but feel free to reopen if it is still an issue.
