### ISSUE TITLE
Black camera screen at document capture step when using Chrome for iOS

### ISSUE THREAD

**Issue by robertatcd** [onfido/onfido-sdk-ui#1456]
### What was the expected behaviour?

User should have been able to use their iPhone camera to capture their ID document.

### What happened instead?

User received a completely black screen, with the usual camera buttons.

### Version info:

- Onfido SDK: onfido-sdk-ui 6.7.2
- OS: iOs 14.4
- Browser: Chrome for iOS
- Device: iPhone 7
- Framework or relevant dependencies (if applicable): ReactJS.

### Integration configuration:

N/A

### Steps to reproduce:

- User went to ID-verify using driver's licence.
- When they selected to use the camera to capture an image of the document, they got the camera screen (with usual buttons), but entirely black.
- Using the front/back camera button did not result in any change.

User was able to complete the process OK after switching from Chrome to Safari.

### Demo:

N/A - under development.

**Comment by andra-radu** [comment]
@robertatcd - Is there only one affected user? 
Were you able to reproduce the issue on your side? 
Could you please share with us a link to your integration / implementation at api@onfido.com, so that we could test it and try to reproduce the error?

**Comment by seewah** [comment]
Closing it now. Please reopen if the problem persists. Thanks
