### ISSUE TITLE
CROSS_DEVICE_START event is missing

### ISSUE THREAD

**Issue by ValentinH** [onfido/onfido-sdk-ui#1481]
### What was the expected behaviour?
the `CROSS_DEVICE_START` event is reported when "User reached the "document capture" screen on mobile after visiting the cross device link" (from [the documentation](https://documentation.onfido.com/sdk/web/#tracked-events))

### What happened instead?

Since version 6.8.0 (still in 6.9.0), the `CROSS_DEVICE_START` event is not reported anymore. This was working properly with 6.7.2.

### Version info:

- Onfido SDK: 6.8.0 or 6.9.0
- OS: MacOS / Android
- Browser: Brave
- Device: OnePlus 7T
- Node: N/A
- Framework or relevant dependencies (if applicable): React

### Integration configuration:

```ts
onfidoSdk.init({
  token: initData.sdkToken,
  containerId: 'onfido-mount',
  steps: ['document'],
  language: {
    locale: onfidoLocale,
    phrases: translations,
  },
  smsNumberCountryCode: 'CH',
  useMemoryHistory: true,
  disableAnalytics: true,
  userDetails: {
    smsNumber: `${phone.prefix}${phone.number}`,
  },
  onComplete() {
    onComplete({
      applicantId: initData.applicantId,
      reportNames: ['document'],
    })
  },
})
```

### Steps to reproduce:
Do the verification using the cross-device feature.

### Demo:

We are not yet live and this is actually a blocker for our release.

**Comment by dethspikee** [comment]
Hi @ValentinH,

We have a fix already in development. I'll try to get ETA for it.

Best

**Comment by TobbeLundberg** [comment]
We're seeing this too, but sometimes we actually do get the event.

@dethspikee Do you know if this is affecting other events too? Are there other events that only work sometimes?

**Comment by kopijunkie** [comment]
@ValentinH FYI [6.12.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.12.0) was released last week which includes the fix for this issue. Could you update to that version and let us know if you can now see the `CROSS_DEVICE_START` event as expected?

**Comment by ValentinH** [comment]
Thanks, I confirm that this is fixed.
