### ISSUE TITLE
Sandbox process taking more then 5 minutes and the dashboard is getting status AWAITING DATA

### ISSUE THREAD

**Issue by tnmendes** [onfido/onfido-sdk-ui#1484]
### What was the expected behaviour?
Sandbox results are always immediate with fake results.

### What happened instead?

Sandbox results taking 5 minutes and getting the status "AWAITING DATA"
When finally I get the result no document data information is shown, not even in the PDF from the dashboard (just the selfie match results)

### Version info:

- Onfido API is v2

### Steps to reproduce:

- Create process document + selfie
- Set the first name ANA
- Set the last name silva
- Upload random photos
- Start process

Go to the dashboard and check the result

### Demo:

Example of one Applicant ID that is happing this:
6f1fcd16-9321-481f-99d1-b9122a5824e9

**Comment by ramprasad-parajuli** [comment]
@tnmendes, the above issue mentioned is not related to Onfido Web SDK, as it is regarding the document report.
I have created a ticket on your behalf with our Product Support Team and I will reach out to you there directly with my findings.
