### ISSUE TITLE
geckodriver dependency?

### ISSUE THREAD

**Issue by gapipro** [onfido/onfido-sdk-ui#1485]
### What was the expected behaviour?

geckodriver package is currently listed under dependencies. It should be listed under devDependencies because its used for development purposes only. Currently we are forced to download Gecko webdriver for no reason at all when adding your SDK to our project.

Hint: Current workaround for this problem is to add **geckodriver_skip_download** when running install, but still, this is not acceptable as a general solution.

**Comment by kopijunkie** [comment]
Hi @gapipro 

Thank you for raising this. We'll be raising a PR to fix this to be included in the next release.

**Comment by kopijunkie** [comment]
Just to update that this has been fixed in version [6.11.1](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.11.1) that was just released yesterday. I'll close this ticket for now.
