### ISSUE TITLE
Highlight box for id photo misaligned 

### ISSUE THREAD

**Issue by TobbeLundberg** [onfido/onfido-sdk-ui#1501]
### What was the expected behaviour?

The resulting photo should show what was in the preview box

### What happened instead?

![onfido_photo_hightlight](https://user-images.githubusercontent.com/87008627/125064286-c80b9400-e0b0-11eb-8fa9-8f6a0367c5db.jpg)
![onfido_photo_missaligned](https://user-images.githubusercontent.com/87008627/125064300-cc37b180-e0b0-11eb-8340-2e90aa17f621.jpg)

### Version info:

- Onfido SDK 6.9.0
- OS iOS, don't know what version
- Browser Safari
- Device iPhone, not sure what model
- Node N/A
- Framework or relevant dependencies (if applicable) React 17

### Integration configuration:

Can share in email if needed.

### Steps to reproduce:

Chose to identify using German ID
Take photo of ID

### Demo:

Nothing publicly available. Can provide link in email if needed.

**Comment by dylandamsma** [comment]
I have the same issue here - Android 11 / Oneplus Nord / Brave Browser version 1.26.77 (Chromium 91.0.4472.164)

**Comment by kopijunkie** [comment]
@TobbeLundberg @dylandamsma we've released [6.12.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.12.0) last week that includes a fix to address this issue. Could you both upgrade to that version and let us know if you are still seeing it happening for you on your respective devices?

**Comment by TobbeLundberg** [comment]
Work for me now, thank you!
