### ISSUE TITLE
Too much whitespace on selfie confirmation page

### ISSUE THREAD

**Issue by TobbeLundberg** [onfido/onfido-sdk-ui#1502]
### What was the expected behaviour?

Just a small amount of whitespace around the selfie

### What happened instead?

A full screen worth of whitespace both above and below selfie

![IMG_0021](https://user-images.githubusercontent.com/87008627/125105198-81cd2980-e0de-11eb-8fb4-b4267432bc6a.PNG)
![IMG_0022](https://user-images.githubusercontent.com/87008627/125105221-872a7400-e0de-11eb-9059-86b71edbd259.PNG)

The selfie is between those two scroll positions

### Version info:

- Onfido SDK 6.9.0
- OS iOS 14.3
- Browser Safari
- Device iPhone 8
- Node N/A
- Framework or relevant dependencies (if applicable) React

### Integration configuration:

Can provide on email if needed

### Steps to reproduce:

Take a selfie. Go to next screen to verify

### Demo:

Can provide on email if needed

**Comment by ramprasad-parajuli** [comment]
@TobbeLundberg I was unable to reproduce the issue on our test environment on an iPhone SE 2nd gen (iOS 14.6) or iPhone 12 (14.1). Trying to see if anyone on my team has an iPhone 8 on iOS 14.3.

In the meantime, it would be useful if you could share an integration link, configuration via email so that we can investigate further.

**Comment by TobbeLundberg** [comment]
> In the meantime, it would be useful if you could share an integration link, configuration via email so that we can investigate further.

Absolutely. What email do you want me to send to?

**Comment by ramprasad-parajuli** [comment]
@TobbeLundberg please provide the details you shared here by emailing api@onfido.com in addition to the integration link and configuration. Someone from the Onfido Support team will respond back to you accordingly.

**Comment by TobbeLundberg** [comment]
Email sent. Thanks for helping push this forward.

**Comment by TobbeLundberg** [comment]
With the latest version of onfido I can no longer reproduce this
