### ISSUE TITLE
Please don't publish /dist/reports/statistics.html

### ISSUE THREAD

**Issue by chrisEff** [onfido/onfido-sdk-ui#1505]
I noticed that your npm bundle contains a VERY large "Webpack Visualizer" file called `/dist/reports/statistics.html`.
It was 18,9MB in version 6.5.0 and now (in 6.10.2) it's 34MB already.
Every time someone installs your package as a dependency, this monstrosity has to be downloaded and I doubt that anyone can/will ever make any good use of it. With the growing number of weekly downloads, this might even have a small impact on climate change. So please, do us all a favor and put it on `.npmignore`.

**Comment by chrisEff** [comment]
Hello,
it's been a month already. Any response would be appreciated...

**Comment by kopijunkie** [comment]
Hi @chrisEff 

Thank you for highlighting this. I've raised a ticket internally on our backlog for us to address.

**Comment by chrisEff** [comment]
Hey @kopijunkie,
ok, I've taken this into my own hands and created a PR.
Would you be so kind review it?
Thanks in advance!

**Comment by chrisEff** [comment]
...just noticed that there's another such file in the lib folder.
Added that one to `.npmignore` as well.
