### ISSUE TITLE
Errors when going back from photo taking screen

### ISSUE THREAD

**Issue by TobbeLundberg** [onfido/onfido-sdk-ui#1509]
### What was the expected behaviour?

Should be able to go back and select a different document type

### What happened instead?

![image](https://user-images.githubusercontent.com/87008627/125970485-09cf7ae4-645c-4222-b365-d1b4001e116f.png)

index.js:371 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at k (index.js:371)
    at h (index.js:180)
    at index.js:26
    at index.js:26
    at d.Jt [as constructor] (index.js:26)
    at d.M [as render] (index.js:524)
    at $ (index.js:196)
    at m (children.js:143)
    at H (index.js:415)

### Version info:

- Onfido SDK 6.9.0
- OS Win 10
- Browser Chrome
- Device Laptop
- Node N/A
- Framework or relevant dependencies (if applicable) React 17

Also tried on an actual iPhone 8, Safari, with same results

### Integration configuration:

```
    const onfido = OnfidoSdk.init({
      useModal: false,
      steps: getSteps(),
      token,
      containerId: "onfido-mount",
      language: {
        locale: locale as OnfidoSdk.SupportedLanguages,
        phrases: JSON.parse(comparablePhrases),
      },
      smsNumberCountryCode: country,
      onComplete: confirm,
      onError: onError,
    });
```

`steps` will be an array built like this

```
    stepConfigurations.push({
      type: STEP_DOCUMENT,
      options: {
        forceCrossDevice: true,
        useLiveDocumentCapture: true,
        uploadFallback: true,
        documentTypes: getAllowedDocumentTypes(allowedDocuments), // passport and national id
      },
    });

    stepConfigurations.push({
      type: STEP_FACE,
      options: {
        requestedVariant: "standard",
        uploadFallback: true,
        useMultipleSelfieCapture: true,
      },
    });
```

### Steps to reproduce:

Select passport on document selection screen
Click the onfido back arrow (top left)
You'll see an error in the console, and if you close the error overlay in the browser you'll see the document selection buttons, but nothing happens when clicking on them

### Demo:

I can do that on email if needed

**Comment by TobbeLundberg** [comment]
This only happens with `useLiveDocumentCapture: true`.
Happens on both Android and iPhone (and chrome device emulation mode)

**Comment by kopijunkie** [comment]
Hi @TobbeLundberg 

We were still unable to replicate this in your test environment. But I also saw in the other ticket you raised that you have upgraded the SDK version. Is this still an issue on the newer version?

**Comment by stefaniacardenas** [comment]
Hi @TobbeLundberg, I'm going to close this issue for inactivity, but please feel free to re-open if you are still facing this issue.
