### ISSUE TITLE
Add HTML element in phrase attribute

### ISSUE THREAD

**Issue by GwenC14** [onfido/onfido-sdk-ui#1511]
### What was the expected behavior?

Is it possible to add an HTML element in the phrase attribute?

### What happened instead?

In my translation, I want to have a bold word, not the entire phrase, but I have the `<b>...</b>` instead.

**Comment by kopijunkie** [comment]
Hi @GwenC14 including HTML elements in the `phrase` attribute is not supported and only strings are allowed. HTML elements will be escaped to prevent executing any code that might intentionally or unintentionally be included in the phrase strings.
