### ISSUE TITLE
401 Bad referrer

### ISSUE THREAD

**Issue by xlerida** [onfido/onfido-sdk-ui#1523]
### What was the expected behaviour?

When the "Upload" button is clicked, the document is send for validation:

![image](https://user-images.githubusercontent.com/65079206/127874906-dc5028d6-48e0-4957-aebc-c05d01fe7cdd.png)

### What happened instead?

When the "Upload" button is clicked, an error is thrown:

![image](https://user-images.githubusercontent.com/65079206/127874107-aa5b36e0-3ade-45e8-adfa-04d6a954a6f7.png)

![image](https://user-images.githubusercontent.com/65079206/127874238-42306009-590d-422b-95e4-4febdd4b17be.png)

Referrer used to generate the token:

![image](https://user-images.githubusercontent.com/65079206/127874300-d7353ca4-c27a-4eef-b111-ec5deed5d315.png)

### Version info:

- Onfido SDK 6.11.1
- Windows 10
- Chrome Version 92.0.4515.107 (64-bit)
- PC
- Node v14.17.3
- Vue 3

### Integration configuration:

````
init({
  token,
  useModal: true,
  isModalOpen: true,
  language: locale.value,
  onComplete(data: any) {
    console.log(data);
  },
  onError(error: any) {
    console.log(error.message);
  },
  steps: [
    {
      type: 'document',
      options: {
        documentTypes: onfidoDocumentTypes,
      },
    },
    'complete',
  ],
});
````

### Steps to reproduce:

1. `yarn add onfido-sdk-ui`
2. Generate a token passing a referrer "`*://*/*`"
3. Initialize Onfido using the retrieved token
4. Try to upload a document

**Comment by ethan605** [comment]
Hi @xlerida, can you please try again with an SDK token generated without the `referrer` field?

**Comment by xlerida** [comment]
Thanks for replying @ethan605 , turns out a filter in our micro service was causing the bug. Sorry, closing issue.
