### ISSUE TITLE
Safari 14.0.1 & 14.0.2 - QR Code is not loading properly

### ISSUE THREAD

**Issue by devang-wise** [onfido/onfido-sdk-ui#1527]
### What was the expected behaviour?

QR code should be fully visible

### What happened instead?

Half or broken QR code displayed

### Version info:

- Onfido SDK: Latest
- OS: macOS Big Sur (11.0.1)
- Browser: Safari 14.0.1 & 14.0.2. (Version 14.0.1 (16610.2.11.51.8))
- Device:
- Node
- Framework or relevant dependencies (if applicable)

### Integration configuration:

Safari browser: https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/master/demo/fiddle/

### Steps to reproduce:

Issue happens on your demo also in Safari browser: https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/master/demo/fiddle/

Attaching screenshot for reference. 
![Screen Shot 2021-08-05 at 1 37 28 PM](https://user-images.githubusercontent.com/51866972/128315137-2028cef0-9c9e-45bc-9dca-48aef0e39da8.png)

**Comment by kopijunkie** [comment]
Hi @devang-wise 

Thank you for raising this. We have a fix for this issue that will be in our next release.

**Comment by kopijunkie** [comment]
Hi @devang-wise 

We've just released [6.13.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.13.0) which includes the fix I mentioned before. I'll close the ticket for now, but feel free to re-open if you find that it is still happening for you after upgrading.
