### ISSUE TITLE
`onReady` callback not firing

### ISSUE THREAD

**Issue by arnoldmanzano** [onfido/onfido-sdk-ui#153]
How to re-create:
The jsfiddle example posted on the README: https://jsfiddle.net/4xqtt6fL/22/
The `console.log` for onReady does not appear on the logs, the callback doesn't seem to run at any point.
The other events' callback seem to be functioning correctly.

**Comment by rfreitas** [comment]
Hey @arnoldmanzano, it's true. Since we have dropped websockets the `onReady` has lost relevance, since the sdk will boot up and render straight away. Do you still need this functionality in some usecase?

**Comment by arnoldmanzano** [comment]
We are not using the `welcome` step, so it directly loads to the `document` step.
We want to attach some additional `click` `eventListeners` to the buttons on the `document` step (passport, driver's license, identity card buttons). We thought the best way to ensure those buttons are already in the DOM is to attach the listeners after the widget has loaded, using `onReady`.
Since that is not working, we attach the listeners code after `init`, which seems to work, but we cannot confirm if that is a reliable solution.

```
Onfido.init({
  // ...
});

var documentSelectorButtons = document.querySelectorAll('.onfido-sdk-ui-DocumentSelector-option');
  [].forEach.call(documentSelectorButtons, function(button) {
    button.addEventListener('click', function(e) {
    // some code here
  });
});

```

**Comment by rfreitas** [comment]
I see. Well `onReady` would also not give you full certainty that that button is in the DOM, the sdk can always reconstruct, even though it is unlikely.
The most correct way would be to use a live query, but it's also a bit more expensive.

May I ask why you need a listener on the button?

**Comment by hjheath** [comment]
We introduced this bug in `0.15.0` and removed the callback entirely from the SDK in `1.0.0`  https://github.com/onfido/onfido-sdk-ui/releases/tag/1.0.0 so closing this issue as won't fix. 

@arnoldmanzano we are still interested to understand what you use the listener for. Understanding how you use the SDK will help us plan future development.
