### ISSUE TITLE
Include Support for Dutch (NL) language

### ISSUE THREAD

**Issue by AmruthPillai** [onfido/onfido-sdk-ui#1538]
Would it be possible to include support for Dutch within the SDK? Or if I were to create a PR for the same, could it be merged into the project?

**Comment by seewah** [comment]
We have an internal roadmap for SDK languages, to help us prioritise the introduction of new ones, which of course has an ongoing maintenance cost. Can you please reach out to your account manager so that we can get it prioritised? thanks

**Comment by nikollamalic** [comment]
Hello, any work done on this so far? Think it would be a great addition

**Comment by kopijunkie** [comment]
@AmruthPillai @nikollamalic We've released [`6.16.0`](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.16.0) yesterday which features the Dutch language support for the Web SDK. 

Will close this ticket now.
