### ISSUE TITLE
Changing copy on "one final step" page

### ISSUE THREAD

**Issue by ravinpatel** [onfido/onfido-sdk-ui#1545]
Hey! How can I change the copy on this page? I assume its within `language: { phrases: ... `  but what are the keys to change the copy? I would like to change the title

![Screenshot 2021-09-01 at 11 15 31](https://user-images.githubusercontent.com/14273533/131654380-7284dc01-281f-4f7c-beab-393e0d3e46d7.png)

### Version info:

- Onfido SDK: 6.13.0

**Comment by kushal-onfido** [comment]
Hi @ravinpatel 

You can easily change the text of highlighted SDK screen by editing the locale files. Could you please review the following link and see if it helps:

https://github.com/onfido/onfido-sdk-ui/blob/master/src/locales/en_US/en_US.json

Thanks!

**Comment by ravinpatel** [comment]
@kushal-onfido Thanks a lot!
