### ISSUE TITLE
UI Glitch in french version of id.onfido.com

### ISSUE THREAD

**Issue by hakilebara** [onfido/onfido-sdk-ui#1558]
### What was the expected behaviour?

The label "Recommencer" (French for "start again") should be centered in the button and fully visible on https://id.onfido.com/

### What happened instead?

![image](https://user-images.githubusercontent.com/1991564/133103152-851f000c-3876-4a94-a074-7f0f8845e52d.png)

### Version info:

- Onfido SDK : 5.9.2
- OS : iOS 13.7
- Browser : Safari iOS
- Device : iPhone6S
- Node
- Framework or relevant dependencies (if applicable)

### Integration configuration:

n/a the bug happens on https://id.onfido.com/

### Steps to reproduce:

https://user-images.githubusercontent.com/1991564/133105983-9a90d23b-c771-40ea-9e41-72a8580d27db.mp4

**Comment by stefaniacardenas** [comment]
Hi @hakilebara , this issue was fixed in version [5.10.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.10.0)
