### ISSUE TITLE
Authorization error: please re-check your credentials

### ISSUE THREAD

**Issue by TobbeLundberg** [onfido/onfido-sdk-ui#1589]
### What was the expected behaviour?

Should be possible to proceed with reset

### What happened instead?

![image](https://user-images.githubusercontent.com/87008627/138885547-a2caeac5-1718-4925-a0ec-b814cf096565.png)

### Version info:

- Onfido SDK 6.15.1
- OS MacOS 11.6, Windows 10
- Browser Chrome, Vivaldi
- Device MBP M1 13", Dell XPS 13
- Node N/A
- Framework or relevant dependencies (if applicable) React 17

### Integration configuration:

Can provide on email if required

### Steps to reproduce:

Take a selfie and try to save it

### Demo:

On email, if required

**Comment by it-ony** [comment]
@TobbeLundberg can you confirm that this has been fixed. Thanks
