### ISSUE TITLE
Got asked issuing country when choosing identity card flow

### ISSUE THREAD

**Issue by rawle51** [onfido/onfido-sdk-ui#1611]
### What was the expected behaviour?

- choose Identity card flow
- don`t want to see issuing country screen

### What happened instead?

-  choose Identity card flow
- use `showCountrySelection: false `option for step `document`
- see issuing country screen

### Version info:

- "onfido-sdk-ui": "^6.15.0"
- OS: all
- Browser: all
- Device: all

### Integration configuration:
```
const STEPS: Array<StepTypes | StepConfig> = [
        {
          type: 'document',
          options: {
            documentTypes: {
              passport: true, // !!! If set false, flow works correct
              national_identity_card: true,
            },
            showCountrySelection: false, // !!!
          },
        },
        {
          type: 'face',
          options: {
            requestedVariant: 'video',
            useMultipleSelfieCapture: true,
          },
        },
        {
          type: 'complete',
          options: {
            message: 'Thank you!',
            submessage: "We are processing your documents, meanwhile let's continue in the chat",
          },
        },
      ]
```

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

- add step document
- add  documentTypes: `passport: true` and `national_identity_card: true`
- add `showCountrySelection: false` option
- chose identity card flow on document screen
- you will see the issuing country screen (but I expect it will not appear)

Additional info:
If delete `passport: true` option, issuing country screen is not appearing
Bug (or feature 😄 ) appears only if widget uses 2 or more document types

### Demo:

https://user-images.githubusercontent.com/20990164/141256000-20e5cc84-3e16-4b2d-bf27-a11d9292bce9.mov

**Comment by rawle51** [comment]
I have found the documentation
![image](https://user-images.githubusercontent.com/20990164/141258206-dd97f19b-e2d5-40d5-ae4f-96beb2a551fc.png)

is it possible to skip this step or maybe to pass preset value?
Why I want to skip the step - I could not find the United Kingdom as option
Is it possible to add or maybe I miss it and you can help to find the right option...

**Comment by kopijunkie** [comment]
It is possible to skip that screen when there are multiple documents preselected by setting a preset `country` value for the non passport document type(s) as documented [here](https://github.com/onfido/onfido-sdk-ui#document) where instead of setting a 3-letter country code, you set the value as `null` instead. 

So in the case of your configuration, you would be looking to set it up like so: 
```
const STEPS: Array<StepTypes | StepConfig> = [
        {
          type: 'document',
          options: {
            documentTypes: {
              passport: true,
              national_identity_card:  { country: null },
            },
          },
        },
        {
          type: 'face',
          options: {
            requestedVariant: 'video',
            useMultipleSelfieCapture: true,
          },
        },
        {
          type: 'complete',
          options: {
            message: 'Thank you!',
            submessage: "We are processing your documents, meanwhile let's continue in the chat",
          },
        },
      ]
```

**Comment by rawle51** [comment]
@kopijunkie Great, thank you!
Solution works fine 🔥
