### ISSUE TITLE
Multiple documents downloading

### ISSUE THREAD

**Issue by rawle51** [onfido/onfido-sdk-ui#1632]
### What was the expected behaviour?

I want to have ability to download and check several documents during the flow:
- I want user to download passport
- Then I want user to download identity card

So I need to have two steps `document` in a row

Is it possible?

### What happened instead?

If I use
```
{
      type: 'document',
      options: {
        documentTypes: {
          national_identity_card: true,
        },
        useLiveDocumentCapture: true,
      },
    },
    {
      type: 'document',
      options: {
        documentTypes: {
          passport: true,
        },
        useLiveDocumentCapture: true,
      },
    },
```

I see only passport step (so the first step with `national_identity_card` is overrides by the next `document` step)

**Comment by ramprasad-parajuli** [comment]
@rawle51 We do not support 2 different document uploads in a single flow. You could initialize the SDK twice for the same applicant if you want to capture 2 different document types and create 2 different checks.

**Comment by rawle51** [comment]
@ramprasad-parajuli
Ok, I got it. Thank you for reply!
