### ISSUE TITLE
Country flags are not displaying on country code selection

### ISSUE THREAD

**Issue by OmkarPatil2510** [onfido/onfido-sdk-ui#1636]
We are using Onfido SDK 5.13.0. For the mobile number screen country flags are not displaying.

<img width="1679" alt="Screen Shot 2021-11-25 at 5 14 20 PM" src="https://user-images.githubusercontent.com/6984409/143526420-af30b3b0-5212-4fac-8a00-deec79ba42d0.png">

### Version info:

- Onfido SDK: 5.13.0
- OS: All
- Browser: All

### Integration configuration:

```
  onfidoOut = Onfido.init({
    token: "<%= sdk_token %>",
    containerId: 'onfido-mount',
    onComplete: function(data) {
      saveDocumentsAndCreateChecks(data, function(response) {
        var redirect_to = urlParam('redirect_to');

        if(redirect_to) {
          $(location).attr('href', '/user_details/new?redirect_to=' + redirect_to);
        }
        else {
          $(location).attr('href', '/profiles/your_details');
        }
      });
    },
    onError: function (data) {
      console.error(data);
    },
    language: {
      locale: getLocale(),
      phrases: getUIPhrases()
    },
    steps: [
      {
        type: 'document',
        options: {
          documentTypes: {
            passport: true,
            driving_licence: false,
            national_identity_card: true
          }
        }
      },
      {
        type: 'face',
        options: {
          requestedVariant: 'standard'
        }
      }
    ]
  })
  ```

### Steps to reproduce:

1. Select Passport
2. Click "Continue on phone"
3. Click on "Get secure link"
4. Click on "Get link via SMS"
5. Observer dropdown besides mobile number textbox

**Comment by gurpreet-onfido** [comment]
Hello Omkar,

Thank you for writing in.

This issue has already resolved in our SDK release https://github.com/onfido/onfido-sdk-ui/releases/tag/6.15.2. 

Kindly upgrade to the latest stable release https://github.com/onfido/onfido-sdk-ui/releases/tag/6.15.4.

This will resolve the issue for you.

Kind regards,
Gurpreet Singh

**Comment by maralm** [comment]
Hi,

We've got the same issue, we're using version [5.11.4-LTS](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.11.4). Given the 5.11 is a long-term support version of the SDK, we'd like to request that you patch this bug in 5.11, please.

Thank you.

**Comment by maralm** [comment]
@kopijunkie OK, thank you for clarifying the LTS policy.
