### ISSUE TITLE
Cordova webview control

### ISSUE THREAD

**Issue by chris-88** [onfido/onfido-sdk-ui#1655]
I'm seeing an issue in our Android Cordova based app when used in the webview control - not being able to activate the live image for the selfie, is it supported in that scenario?

**Comment by andra-radu** [comment]
Hi @chris-88  - You will need to enable camera permissions on the cordova app side. You can check the following links as we don’t support cordova integration.
https://cordova.apache.org/docs/en/2.5.0/cordova/camera/camera.html
https://stackoverflow.com/questions/45179158/how-do-i-get-permission-to-navigator-getusermedia-via-webview-in-cordoba
