### ISSUE TITLE
Onfido.getCaptures() returns everything except front 'documentCapture'

### ISSUE THREAD

**Issue by flatsteve** [onfido/onfido-sdk-ui#166]
Hey Onfido devs. Firstly, awesome document capture tool. So nice to use something with fallbacks and great mobile support 👍 

I was wondering if you could help me. I'm using the client SDK and found that when I call  `Onfido.getCaptures()` in my `onComplete` callback, the `documentCapture` property in the returned object is always null...

This is weird because if I use `onDocumentCapture` to log out each capture if returns the expected object with the id and blob etc.

I've included a screenshot below to try to illustrate this (first two logs are `documentCapture` third is `Onfido.getCaptures()`):

<img width="591" alt="screen shot 2017-07-03 at 17 34 12" src="https://user-images.githubusercontent.com/1211440/27801544-81f3a04e-6016-11e7-9e10-fef3e12473d4.png">

Am I just being stupid and missed something (wouldn't be the first time) 😉 

P.S I'm including the SDK via a script tag at the moment for testing if that helps (maybe a fix is published to NPM but not updated in the dist?).

**Comment by rfreitas** [comment]
Hi @flatsteve,

Sorry for the late reply, we are looking into this straight away. Which version are you on?

**Comment by rfreitas** [comment]
We have not been able to reproduce this on the latest bundle found in dist.
We have tested it on jsfiddle, here: https://jsfiddle.net/4xqtt6fL/33/

**Comment by flatsteve** [comment]
Hey guys,

Thanks a lot for getting back to me. I managed to reproduce the error on JS fiddle: https://jsfiddle.net/6yh6wshz/1/

<img width="1919" alt="screen shot 2017-07-10 at 18 00 19" src="https://user-images.githubusercontent.com/1211440/28030060-16395180-659a-11e7-8474-c8f96dd87753.png">

I've realised the issue only happens when webcam is enabled (I know this is in beta but it's such an awesome feature I couldn't help myself):

        {
          type: "document",
          options: {
            useWebcam: true
          }
        }

Sorry for not including this essential info before - I didn't notice 😉 

Anyways - not a huge issue as I just save a reference to the document info returned from `documentCapture` and use it if `Onfido.getCaptures()` has a `null` `documentCapture` but thought I'd reply incase this info helps. 

Keep up the awesome work. 

P.S we successfully launched our verification process yesterday using the SDK and it's working a treat 👍

**Comment by rfreitas** [comment]
hmm, I see.

We will try to see if there is a quick fix for it, but we have deprioritized webcam development for document captures. It's because most webcam offer poor quality when capturing objects close to its lenses, since most of them have an optimal focus length for capturing faces.

**Comment by hjheath** [comment]
Update: this is still broken and capturing a document using the webcam remains in beta. We plan to refactor the callbacks in v2.0.0 so anticipate this issue will be made redundant then.

**Comment by hjheath** [comment]
In release 2.0.0: https://github.com/onfido/onfido-sdk-ui/releases/tag/2.0.0 we have removed the `getCaptures` method so this issue is redundant.

Captures are no longer accessible through the SDK, but can be accessed through the API or Onfido dashboard.
