### ISSUE TITLE
onComplete callback is not invoked after submitting docs in Safari and selfie on Mobile Chrome

### ISSUE THREAD

**Issue by serhiiDxc** [onfido/onfido-sdk-ui#1681]
### What was the expected behaviour?
`onComplete` is invoked after all steps are successfully passed and user sees "Thank you screen"

### What happened instead?

user sees "Thank you screen" after he submitted documents in Safari browser, and uploaded selfie via mobile phone, but `onComplete` callback is not invoked

### Version info:

- Onfido SDK 6.13.0
- OS OSX 10.14.6
- Browser Safari 14.1.2
- Device Android Chrome

### Integration configuration:

return init({
                useModal: true,
                isModalOpen: true,
                token: data.sdk_token,
                containerEl: containerRef.current,
                onComplete: () => {
// this is invoked in Chrome after taking selfie on laptop, but not invoked in Safari after selfie on moblie
                    onComplete().then(onfidoSdk.tearDown)
                },
                onModalRequestClose: onClose,
                steps: ['welcome', 'document', 'face', 'complete'],
                disableAnalytics: true,
            })

### Steps to reproduce:

1. Pick Driver license
2.  Upload sample driver license twice (front and back)
3. Proceed with selfie on mobile, upload it
4. Proceed in computer's browser
5. See Thank You screen

**Comment by ramprasad-parajuli** [comment]
@serhiiDxc, thank you for flagging the issue.
We were aware of the issue and we were able to fix the issue in version [6.15.1](https://github.com/onfido/onfido-sdk-ui/blob/master/CHANGELOG.md#6151---2021-10-21). 
Can you please upgrade web SDK on your side and let us know how it performs?

**Comment by serhiiDxc** [comment]
Looks like yes, Safari is not using mobile to take a selfie anymore. So you have replaced that case - with photo on the mobile? Is this case still available somewhere and i can test it (upload docs via browser and proceed with selfie on mobile)?

**Comment by zoeradkani** [comment]
Going to close this issue, as it has been fixed in later versions.
