### ISSUE TITLE
when  import * as Onfido from 'onfido-sdk-ui' then App crashes and show cannot read property prototype of undefined in React native

### ISSUE THREAD

**Issue by MuhammadKashifAslam** [onfido/onfido-sdk-ui#1728]
### What was the expected behaviour?

Please detail what the expected behaviour was

### What happened instead?

Please detail what the actual behaviour was

### Version info:

- Onfido SDK
- OS
- Browser
- Device
- Node
- Framework or relevant dependencies (if applicable)

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

Please describe in as much detail as possible how to reproduce the problem

### Demo:

If possible, please share a URL or public repository where the issue can be reproduced

**Comment by stefaniacardenas** [comment]
Hi, can you import just the `init` function?
`import {init} from "onfido-sdk-ui"`
Which version of the SDK are you trying to import?
FYI you can also use the RN SDK https://github.com/onfido/react-native-sdk

**Comment by MuhammadKashifAslam** [comment]
I have been used onfido-React-Native it work fine but it doesn't show
screen of choose multiple documents it just show front end of documents ,
back of documents and salfie.how can we show below screen in
onfido-react-native??

**Comment by MuhammadKashifAslam** [comment]
I am trying to import latest version of onfido-sdk-ui according to
documentation when I important onfido from require('onfido-sdk-ui')
application crashes and give error cannot read property prototype of
undefined

**Comment by MuhammadKashifAslam** [comment]
import*

**Comment by MuhammadKashifAslam** [comment]
here is my code of React Native Thankyou in advance.

import * as Onfido from 'onfido-sdk-ui'

  const initOnfido = async () => {
        try {
            const instance = Onfido.init({
                useModal: false,
                token: token,
                onComplete: (data) => {
                    // callback for when everything is complete
                    console.log('Everything is complete', data)
                },
                steps: [
                    {
                        type: 'welcome',
                        options: {
                            title: 'Open your new bank account',
                        },
                    },
                    'document',
                    'face',
                    'complete',
                ],
            })
        } catch (err) {
            console.log('err:', err.message, err.request)
        }
    }

Error ScreenShot:

![Screenshot_2022-03-01-15-09-13-46_4fa2ad18c6d519f1e5982927b847faa5 1](https://user-images.githubusercontent.com/80664407/156150717-c54b150b-d44f-4421-b33f-f92f50d9b737.jpg)

**Comment by MuhammadKashifAslam** [comment]
I have been used @onfido/react-native-sdk it work fine but it doesn't show
screen of choose multiple documents it just show front end of documents ,
back of documents and salfie.How can we show below screenshot using this library like which document type you would select.

![Screenshot_2022-03-01-14-48-11-95_40deb401b9ffe8e1df2f1cc5ba480b12 1](https://user-images.githubusercontent.com/80664407/156151289-0a8a46f4-3312-4576-bc03-0e6553b0d55d.jpg)

**Comment by MuhammadKashifAslam** [comment]
@stefaniacardenas I have been resolved the issues because I just specify the documentType: 'driver_license' that's why it navigates only that flow.

**Comment by stefaniacardenas** [comment]
Good to hear. So what configuration are you passing now?

**Comment by MuhammadKashifAslam** [comment]
@stefaniacardenas i have a question if I have been successfully verified CNIC after check how i navigate to welcome Screen for other documents verification for same token,because our requirement is verified ,CNIC,Passport,DriverLicense

**Comment by MuhammadKashifAslam** [comment]
@stefaniacardenas I have a question how we get documentType after document uploaded successfully in my case i just returned back front,back and id .

**Comment by stefaniacardenas** [comment]
> i have a question if I have been successfully verified CNIC after check how i navigate to welcome Screen for other documents verification for same token,because our requirement is verified ,CNIC,Passport,DriverLicense

Do you want to re-initialise the flow to capture more documents? Just call the init function again with the steps you want to capture, after the `onComplete` callback is fired

> I have a question how we get documentType after document uploaded successfully in my case i just returned back front,back and id .

You should be able to get the document type in the data returned in the onComplete callback eg. 
`onComplete((data) => console.log(data.document_front.type))`

**Comment by MuhammadKashifAslam** [comment]
I used React-Native-sdk it just returned document?. front?. id

**Comment by stefaniacardenas** [comment]
Can you email [api@onfido.com](mailto:api@onfido.com) with your issue and they should be able to help. Thank you. 
I'll close this issue for now as this is related to the React Native SDK
