### ISSUE TITLE
Integration with Next.js on Production

### ISSUE THREAD

**Issue by gstrobl** [onfido/onfido-sdk-ui#1755]
### What was the expected behaviour?

I got errors when I'm trying to implement CSP stuff, I think this problem is also connected to my Next.js app. Without the Troubleshooting guide, i got this error: 

`Refused to connect to '<URL>' because it violates the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.`

`Refused to connect to 'wss://sync.onfido.com/v3/socket.io/?EIO=4&transport=websocket' because it violates the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.`

The SDK is loading and at the step where I got the Verfiy Link I got this error.

With the CSP guide (https://documentation.onfido.com/sdk/web/#troubleshooting), I got this error:

`unsafe-inline' http: https:". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled.`

Does anyone have experience, to connect it with Nextjs on production level?

### Version info:

- Browser

**Comment by andra-radu** [comment]
Hi @gstrobl - In order for us to further debug this, can you please provide us the following information?
SDK version and Initialisation configuration code. You can always open a ticket at api@onfido.com to be able to share this info so that we can further investigate.

**Comment by it-ony** [comment]
Hi @gstrobl, 
please share the link to the page. As I read it from the error message, the CSP header has a `strict-dynamic` part included, which disables the white list in flavor of having scripts only be allowed with a nouce or checksum added. 

You can read more about this here: https://csp.withgoogle.com/docs/faq.html#strict-dynamic-with-whitelists

Either get rid of the strict-dynamic or go for hashes in the CSP and included scripts.  You can also check your CSP headers with https://csp-evaluator.withgoogle.com/

If you post them here, I can assist you.

**Comment by gstrobl** [comment]
@it-ony I already created a support ticket, but this issue is pretty hard connect to implement CSP headers in Next.js, an example or something like that would help me a lot.

**Comment by gstrobl** [comment]
@it-ony @andra-radu is the ticket processed over Github or Onfido API Support?

**Comment by it-ony** [comment]
I played around with it today and I didn't have any CSP problems. See my hacked code here: https://github.com/it-ony/nextjs/blob/main/pages/index.js

**Comment by gstrobl** [comment]
> I played around with it today and I didn't have any CSP problems. See my hacked code here: https://github.com/it-ony/nextjs/blob/main/pages/index.js

Can you make this repo public please?

**Comment by it-ony** [comment]
Sorry, nextjs create a new repo, which was private.

**Comment by gstrobl** [comment]
For everybody how has the same issue, always checking if there is no default header placed in the ngnix config. Then place the csp headers over the https://nextjs.org/docs/advanced-features/security-headers especially the `connect-src`, then everything is working like expected.
