### ISSUE TITLE
Documentation: Formatting issue in "Getting started" section (v6.19.0 & v6.18.0)

### ISSUE THREAD

**Issue by DBloodworth95** [onfido/onfido-sdk-ui#1779]
Apologies in advance if this is the wrong section to submit this issue.

I noticed a minor formatting issue in the "Getting Started" section of the SDK documentation.

**Source:** https://documentation.onfido.com/sdk/web/#no--1-obtain-an-api-token

**Version:** 6.19.0 & 6.18.0

![OnFidoDocsFormattingIssue](https://user-images.githubusercontent.com/43654582/160618177-49bea923-4969-4128-a1fa-70c2f745d138.png)

**Comment by stefaniacardenas** [comment]
Thanks for reporting it. I've raised a fix 🙏
