### ISSUE TITLE
Onfido SDK overrides global page CSS `color-scheme` to `light`

### ISSUE THREAD

**Issue by PiDelport** [onfido/onfido-sdk-ui#1804]
### What was the expected behaviour?

I have a project that declares `color-scheme: dark` on `:root`, and didn't expect the Onfido SDK to conflict with that.

### What happened instead?

When including the Onfido SDK, it overrides the `:root` property value to `color-scheme: light` for the entire page.

### Version info:

- Onfido SDK: 6.20.0

### Steps to reproduce:

Declare the following CSS:

```css
:root {
  color-scheme: dark;
}
```

Include the SDK's `style.css`, and observe that it overrides the above to `color-scheme: light`.

### Demo:

This snippet reproduces the issue:

- https://codepen.io/PiDelport/pen/RwxYPyB

### Cause:

While troubleshooting this issue, I tracked it down to the following:

1. Onfido SDK includes `castor.day()` on `:root` in [style.css](https://github.com/onfido/onfido-sdk-ui/blob/6.20.0/src/components/Theme/style.scss#L69)

   - This was added in https://github.com/onfido/onfido-sdk-ui/pull/1289, in [Theme/style.scss](https://github.com/onfido/onfido-sdk-ui/pull/1289/files#diff-2be0d45d90f79d9af0db0fed64b4eb9adb7400de73b0bea57714466e33ec0b80)

2. Castor later added `color-scheme` to `day()` and `night()` in https://github.com/onfido/castor/pull/591 ([files changed](https://github.com/onfido/castor/pull/591/files))

3. That code now lives in Castor Tokens, in [theme.scss.hbs](https://github.com/onfido/castor-tokens/blob/v1.0.0-beta.5/packages/npm/src/theme.scss.hbs)

### Solution?

Instead of attaching `castor.day()` to the `:root` scope, it should probably be attached somewhere closer to where the widget or modal will be attached, or the styles should be scoped to a widget-specific class?

**Comment by DannyvanderJagt** [comment]
Hi! Thank you for reporting and doing the trouble shooting! I've made a PR (https://github.com/onfido/onfido-sdk-ui/pull/1808) for and will let you know when it merged and released.

**Comment by DannyvanderJagt** [comment]
@PiDelport We have made changes to resolve this issue in version `8.1.0`
