### ISSUE TITLE
Steps-Document-Select issuing country, can't input text to search

### ISSUE THREAD

**Issue by 66beta** [onfido/onfido-sdk-ui#1826]
### What was the expected behaviour?

Choose Document - Select issuing country - "Search for country"  input box support input text to search

### What happened instead?

- can't input text to search country
- can't cancel the selected country

### Version info:

- Onfido SDK 6.20.0
- MacOS 10.15.7
- Chrome latest
- Macbook Pro (Intel)
- Node 16.14.0
- Reactjs/Nextjs/Material-UI

### Steps to reproduce:

- Choose Document - Select issuing country - choose Albania - can't change to Algeria
- Choose Document - Select issuing country - can't input text to filter

**Comment by gurpreet-onfido** [comment]
Hello @66beta 

I have tried to reproduce the issue at our end at https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/master/demo/fiddle/ that uses the latest release of the Web SDK and could not reproduce it. 

I am able to change the issuing country and type the text to filter the list.

Could you please try on this link once and let us know how it goes.

Kind regards,
Gurpreet Singh

**Comment by zoeradkani** [comment]
This issue is not valid, the SDK version is outdated. The UI also going to be updated in upcoming version.
