### ISSUE TITLE
Content security policy violation in 6.3.0 SDK on style-src-attr

### ISSUE THREAD

**Issue by kuzmicz** [onfido/onfido-sdk-ui#1859]
### What was the expected behaviour?

Onfido SDK should not add an inline styles when implemented on the web page due to the content security policy directive.

### What happened instead?

The onfido SDK 6.3.0 version causes a CSP violation on the `style-src-attr`

```
csp-report.blocked-uri | inline

csp-report.column-number | 10970

csp-report.disposition | report

csp-report.effective-directive | style-src-attr

csp-report.line-number | 3

csp-report.original-policy | script-src 'self' https://cdn.jsdelivr.net/npm/onfido-sdk-ui@5.4.0/dist/ https://cdn.jsdelivr.net/npm/onfido-sdk-ui@6.3.0/dist/ https://assets.onfido.com;

style-src 'self' https://cdn.jsdelivr.net/npm/onfido-sdk-ui@5.4.0/dist/ https://cdn.jsdelivr.net/npm/onfido-sdk-ui@6.3.0/dist/ https://assets.onfido.com;

csp-report.source-file | https://cdn.jsdelivr.net/npm/onfido-sdk-ui@6.3.0/dist/onfido.min.js

csp-report.status-code | 200

csp-report.violated-directive | style-src-attr
```

### Version info:

- 6.3.0
- All systems
- All browsers
- All devices
- Node: 16.14.0

### Steps to reproduce:

1) Implement a CSP onfido library into webpage with configured content security policy.
2) Open a page and console.

**Comment by gurpreet-onfido** [comment]
Hello @kuzmicz 

Greetings for the day!

We haev looked into it and found a couple of instances that are causing this. It seems to happen in the the country selectors where we use images of country flags. We have fixed this up and the fix will be rolled out in the next release of the SDK.

Stay tuned!

Kind regards,
Gurpreet Singh

**Comment by DannyvanderJagt** [comment]
@kuzmicz Thank you for reporting. We have made changes to resolve this issue in version `8.1.0`
