### ISSUE TITLE
Onfido Flaw in Onfido Utils (Bug in code) causes Automation to Fail in Cypress

### ISSUE THREAD

**Issue by jbird21** [onfido/onfido-sdk-ui#1880]
### What was the expected behaviour?

Cypress to work with Onfido as Per 10 May 2022 and before

### What happened instead?

Onfido now seems to just show a white screen when accessed via Cypress with no error

### Version info:

- Onfido SDK 8.0.0
- OS : OSX
- Browser Chrome

We have used Onfido with Cypress for at-least a solid 6 months with no issues. We have gone to run the tests and now it seems on load that the popup just sits and does not load. If we try manually then there is no issue.

Have there been any changes in the last 7 days?

Has this endpoint been updated?

https://api.onfido.com/v3.3 

![image](https://user-images.githubusercontent.com/95627544/169496110-d334958e-0f42-446f-89b9-a867900aec22.png)

![image](https://user-images.githubusercontent.com/95627544/169502055-8077ac2e-4c90-40de-9f8a-0f56b9ce44f4.png)

Note: We do not get this issue when manually testing

**Comment by jbird21** [comment]
I can see there has been changes in location / country over the last 3 days. Is it just a coincidence that on the /location call to the API that this now falls over?

The issue when looking at the JSON is malformed Json

**Comment by hcz1** [comment]
The cause is as follows, in the first screen shot you can see the PATCH request: `https://api.onfido.com/v3.3/applicants/fb38a941-e778-444b-9d9c-fee7a61fd9e7/location`.   
The Response headers have `content-type: "application/json"`
<img width="755" alt="image" src="https://user-images.githubusercontent.com/14975445/170009899-72630c22-6af1-45cd-83be-0f4df505a29e.png">. 
this call is made using the `http.ts` onfido util:
```
request.onload = () => {
    if (
      request.status === 200 ||
      request.status === 201 ||
      request.status === 204
    ) {
      const contentType = request.getResponseHeader('content-type')
      if (contentType && contentType.startsWith('application/json')) {
        onSuccess(JSON.parse(request.response))
      } else {
        onSuccess(request.response)
      }
    } else {
      onError(request)
    }
  }
```
Therefore causing `JSON.parse(request.response)` to fail.

**Comment by jbird21** [comment]
@vyeruva-onfido any thoughts?

**Comment by jbird21** [comment]
@Gamer1120  It's down to the code change they made inside http.ts.

Waiting on someone in Onfido to review

**Comment by limnash-onfido** [comment]
Hi @jbird21 , just to keep you updated. We will be fixing this in our next release. The release should be out by next week. Thank you!
