### ISSUE TITLE
Country selection page breaks when we hit back button

### ISSUE THREAD

**Issue by mydatahack** [onfido/onfido-sdk-ui#1921]
### What was the expected behaviour?

When we go back to the country selection page by clicking the back arrow, we should be able to select country again.

### What happened instead?

When we go back to the country selection page by clicking the back arrow, the page breaks.

![Screen Shot 2022-06-17 at 11 24 27 am](https://user-images.githubusercontent.com/43569574/174203811-0242db14-e743-4fde-9946-031df25e2483.png)

Error message:

```
index.js:397 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at I (index.js:397:30)
    at b (index.js:191:31)
    at useSelector.js:41:3
    at useSelector.js:11:1
    at _.Aa [as constructor] (index.tsx:25:24)
    at _.B [as render] (index.js:532:14)
    at R (index.js:190:14)
    at S (children.js:137:3)
    at j (index.js:418:4)
    at R (index.js:246:20)
```

It seems like the problem is this:

```js
function argsChanged(oldArgs, newArgs) {
	return (
		!oldArgs ||
		oldArgs.length !== newArgs.length || // <-- this line...
		newArgs.some((arg, index) => arg !== oldArgs[index])
	);
}
```

### Version info:

- Onfido SDK: 8.1
- OS: Mac
- Browser: 
- Device: MacBook
- Node: 14.17.2
- Framework or relevant dependencies (if applicable): React - initialising the sdk with useEffect and target the mount point

### Integration configuration:

```ts
export const Onfido = () => {
  useEffect(() => {
    init({
      token: SDK_TOKEN,
      containerId: 'onfido-mount',
      onComplete: () => {
        console.log('everything is complete')
      },
      steps: ['welcome', 'poa', 'document', 'face', 'complete'],
    })
  })
  return (
    <div id="onfido-mount" />
  )
}
```

### Steps to reproduce:

Select country and proceed. Then press the back button to selected country.

### Reproducible demo:

https://user-images.githubusercontent.com/43569574/174203376-39f390a0-422b-4a06-b820-1c16c236d756.mov

**Comment by DannyvanderJagt** [comment]
Hi @mydatahack, thanks for reporting your issue.

I've taken some time to look into this issue but I can't seem to reproduce it in a clean environment (Onfido SDK with React only), see [here](https://codesandbox.io/s/onfido-web-sdk-github-1921-93rk6g) 

Could you help us reproduce it in the provided snippet or provide additional information? And could you tell us where you found the `argsChanged` code snippet?
