### ISSUE TITLE
onComplete is invoked multiple times which makes integration to an backend difficult.

### ISSUE THREAD

**Issue by ArneSchoonvliet** [onfido/onfido-sdk-ui#1963]
### What was the expected behaviour?

When finishing the flow on the mobile device (document and video flow), the onCompleted function is called once.

### What happened instead?

the onCompleted function is called multiple times. 
This behaviour makes integration quite difficult as on onComplete you would usually do a call to your BE to create a check. 

### Version info:

- Onfido SDK 8.1.0 - 8.1.1
- OS windows & linux based systems
- Browser chrome, edge
- Device oneplus 6t
- Node 16.5
- Framework or relevant dependencies (if applicable) Angular

```ts
import { init, SdkError, SdkHandle, SdkOptions } from 'onfido-sdk-ui';
import { Injectable, OnDestroy } from '@angular/core';

@Injectable()
export class OnfidoService implements OnDestroy {
  private onfido: SdkHandle = null;
  private readonly baseSdkOptions: SdkOptions = {
    useModal: true,
    containerId: 'onfido-mount',
    onModalRequestClose: () => this.close(),
  };

  initialize() {
    if (!this.onfido) {
      this.onfido = init(this.baseSdkOptions);
    }
  }

  open(token: string, success: () => void) {
    debugger;
    this.initialize();
    this.onfido.setOptions({
      token,
      isModalOpen: true,
      onError: (error: SdkError) => {
        debugger;
      },
      onComplete: (data) => {
        debugger;
        success();
        this.close();
      },

      steps: [
        {
          type: 'document',
          options: {
            forceCrossDevice: true,
            useLiveDocumentCapture: false,
          },
        },
        {
          type: 'face',
          options: {
            requestedVariant: 'video',
            uploadFallback: true,
            photoCaptureFallback: false,
          },
        },
      ],
    });
  }

  close() {
    if (this.onfido) {
      this.onfido.setOptions({ isModalOpen: false });
      this.onfido.tearDown();
      this.onfido = null;
    }
  }

  ngOnDestroy() {
    this.close();
  }
}
```

### Steps to reproduce:

I've made a repro in this repository https://github.com/ArneSchoonvliet/angular-ivy-flywhb
You will notice, great success is called multiple times.

**Comment by ArneSchoonvliet** [comment]
Hello

I narrowed it down, when invoking setOptions in the onComplete function it will keep invoking onComplete until a stackoverflow. I have a fiddle showing this behaviour: https://jsfiddle.net/az3yn8fs/33/ 

I want to point out that this behaviour wasn't the case with version 6.20.1 of the SDK.

**Comment by ArneSchoonvliet** [comment]
Any news on this?

**Comment by isaacmwilliamson** [comment]
Is there any update on this?

**Comment by nulrich** [comment]
Hello @isaacmwilliamson @ArneSchoonvliet. This bug has been fixed in https://github.com/onfido/onfido-sdk-ui/pull/1979
