### ISSUE TITLE
onError Not Firing

### ISSUE THREAD

**Issue by mattsputnikdigital** [onfido/onfido-sdk-ui#2017]
Tested in version 8.1 & 8.3

If I provide a bad token, the error is shown in the console, but onError does not fire.

As a test, if I provide a bad containerId onError does fire, so it seems the SDK is swallowing the token / authorisation_error.

**Comment by mattsputnikdigital** [comment]
I have tested the same code in 6.18 and onError fires for a bad token, bad referrer etc... where as 8.3 does not.

**Comment by nulrich** [comment]
@mattsputnikdigital this issue has been addressed in https://github.com/onfido/onfido-sdk-ui/pull/1985, which will be in the next release.

If the token is expired, onError will be called with the message `Authorization error: please re-check your credentials`
