### ISSUE TITLE
`documentTypes` is ignored

### ISSUE THREAD

**Issue by TobbeLundberg** [onfido/onfido-sdk-ui#2029]
### What was the expected behaviour?

When I configure Onfido to only allow passport and national id, only those options should be visible

### What happened instead?

Many more options are shown

![image](https://user-images.githubusercontent.com/87008627/183609333-5dedaf20-29e3-409e-8066-0f982b48d53e.png)

### Version info:

- Onfido SDK 8.3.0
- OS MacOS 12.4
- Browser Vivaldi
- Device MBP M1
- Node n/a
- Framework or relevant dependencies (if applicable) React 17

### Integration configuration:

Here's my steps config

```
      steps: [
        {
          type: "document",
          options: {
            documentTypes: {
              driving_licence: false,
              national_identity_card: true,
              passport: true,
              residence_permit: false,
            },
          },
        },
        'face',
      ],
```

### Steps to reproduce:

Configure onfido with the steps config above and type Sweden in the country select box and you'll see many more document types than what is allowed

### Reproducible demo:

https://jsfiddle.net/rkbufo8h/

**Comment by gurpreet-onfido** [comment]
Hello @TobbeLundberg 

Thank you for bringing this up. Please allow us sometime to check this internally and we will get back to you on this as soon as possible. 

Kind regards
Gurpreet Singh

**Comment by osolliec** [comment]
thanks for reporting, if you would rather not wait for the fix to be released you can just delete the property 
instead of 
```
            documentTypes: {
              driving_licence: false,
              national_identity_card: true,
              passport: true,
              residence_permit: false,
            },
```

you can do

```
            documentTypes: {
              national_identity_card: true,
              passport: true,
// removed the properties that should not appear
            },
```

**Comment by TobbeLundberg** [comment]
@osolliec Thanks for the fix!

I was reading the docs https://github.com/onfido/onfido-sdk-ui#document and it says (the highlight is mine)

> The list of document types visible to the user can be filtered by using the documentTypes option. **The default value for each document type is true.**

So I thought I had to set them to `false` or they would default to `true`. If the default (i.e. the value they get if you don't specify them) is `false` I think you need to update your docs 🙂
