### ISSUE TITLE
Issues with document types and country selection

### ISSUE THREAD

**Issue by pedrotorchio** [onfido/onfido-sdk-ui#2043]
### What was the expected behaviour?

![image](https://user-images.githubusercontent.com/18075966/185009762-6f80f3dd-c62a-4b88-8f47-ced405f22d91.png)

For country selection to appear after a document selection, **only if its required** (if no country was specified and not passport)

### What happened instead?

**1)** 

Using same options as documented in "Example of Document step configurations with preselected documents where Country Selection will still be displayed"
![image](https://user-images.githubusercontent.com/18075966/185010296-28418e18-78f5-4b26-b790-9718c88471d1.png)

```
"documentTypes": {
          "passport": true,
          "driving_licence": true,
          "national_identity_card": true
}
```

I get the country selection first 
![image](https://user-images.githubusercontent.com/18075966/185010561-d36ef873-9a9f-4d6b-aadf-486388001943.png)
And then the options
![image](https://user-images.githubusercontent.com/18075966/185010593-601c3caf-b39f-4b7e-bbc4-7d3114fd5aed.png)

**2)**

Using the options for our own use case, where driving licence may only be Australian and **therefore no country selection is expected**

```
documentTypes: {
            "passport": true,
            "driving_licence": { country: "AUS" },
},
```

Still get a country selection **for all countries** before seeing the options
![image](https://user-images.githubusercontent.com/18075966/185011516-8e72ebe1-7a38-4653-864a-41c3c6dc4666.png)

**3)**

This is the weirdest imo. If I configure document types to two documents with country "AUS", then dropdown still shows first, but with a single option for "Australia". If Passport type doesn't care about country, then why the difference?

```
documentTypes: {
            "driving_licence": { country: "AUS" },
            "national_identity_card": { country: "AUS" }
},
```
![image](https://user-images.githubusercontent.com/18075966/185012034-83e30fa3-3d8a-410b-a225-698dcbf3a0df.png)

### Version info:

- Onfido SDK **v8.3.0**
- OS **Macos 12.5**
- Browser **Chrome 104.0.5112.79** 
- Device  **Chrome device tool** 
- Node **v16.15.1**
- Framework or relevant dependencies (if applicable) VueJS wraps the onfido sdk just to call the Onfido.init method

### Integration configuration:

```
 const documentStep = {
        type: "document",
        options: {
          documentTypes: { 
            "driving_licence": { country: "AUS" },
            "national_identity_card": { country: "AUS" }
          },
          forceCrossDevice: this.useMobileDevice,
          useLiveDocumentCapture: this.getConfigValue(
            "enableLiveDocumentCapture"
          ),
          uploadFallback: true,
        },
};

const selfieStep = {
        type: "face",
        options: {
          requestedVariant: this.getConfigValue("useLiveness")
            ? "video"
            : "photo",
        },
};

const welcomeStep = {
        type: "welcome",
        options: {
          title: this.getConfigValue("welcomeScreen.title"),
          descriptions: this.getConfigValue("welcomeScreen.content"),
          nextButton: this.getConfigValue("welcomeScreen.ctaText"),
        },
};
```

### Steps to reproduce:

[I believe by just following the documented approach you'll get the same issues](https://documentation.onfido.com/sdk/web/#example-of-document-step-configurations-with-preselected-documents-where-country-selection-will-still-be-displayed)

### Reproducible demo:
[Your own jsFiddle seems to be in disagreement with your documentation and displays country selection first. ](https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/master/demo/fiddle)

[But here's one for number 3 above](https://jsfiddle.net/vzf8heau/9/)

**Comment by TobbeLundberg** [comment]
@pedrotorchio I'm just another Onfido customer, who also found this configuration a bit confusing...

But for your case. Let's say I'm an Australian citizen. Then I should get the option to select either Passport or Driver's License. Right?

But if I'm Japanese my only option should be to verify my identity by using my passport. Correct?

If so, Onfido would always have to display the country select dropdown I believe. How would they otherwise know if they should display just the passport option (or skip selection all together) or give the option to pick either passport or driver's license (for Aussies only)?


In your second example you're not allowing passports. Only driver's license and ID card. And for both only Australia. So Australia is the only available choice. So this is a configuration for which I think Onfido should skip the country selection screen.

**Comment by onfido-website-team** [comment]
Hi @pedrotorchio 

I recommend you to use the most updated documentation about Document Screen. https://github.com/onfido/onfido-sdk-ui#document


1) If had "driving_licence" and "national_identity_card" on your code, so Issuing Country Selection will be displayed. That is the designed behaviour.
2) That is expected as well. If documentTypes only includes one document type with a country value, users will not see the document selection screen and instead will be taken directly to the capture screen. @TobbeLundberg gave a good very good example.
3)I agree that would be a better design if we were skipping the Issuing Country Selection, as you had already specified the same country for the document types. I'm reaching out to our internal team to confirm that design and I'll get back to you as soon as possible.

**Comment by pedrotorchio** [comment]
Hey @TobbeLundberg, I appreciate your reply and appologise for not getting back to this issue sooner. Yout point is valid if we are accepting foreign passports, but in our case we only accept Australian citizens and we want them to be requested for their Australian passport and Australian DL without going through a country selection.

**Comment by pedrotorchio** [comment]
@onfido-website-team so there's no way to restrict the Onfido SDK to a single country then? That's mainly what we're trying to do at the moment and thought that would be possible for a combination of Passport (no country specified) and Driving licence (AUS).

**Comment by finppp** [comment]
Hey, I'm looking at a similar situation and just wanted to check something:

I am upgrading from the Web SDK V6 -> V8 and noticed the Country Select has been added, although we haven't changed any code, other than the package version.

We want to accept any driving licence or any passport. Will this always result in a country select?

**Comment by onfido-website-team** [comment]
Hi [pedrotorchio](https://github.com/pedrotorchio)

For the latest release, that is the designed behaviour. The issuing_country screen will be shown first, regardless you have specified the country (Australia). The dropdown selection button will display Australia only. 

Our Engineer team is aware of this behaviour, and they will review it. However, we don’t have an estimated time for a change.

I do apologize for the inconvenience caused.

Kind regards,
Onfido Support

**Comment by onfido-website-team** [comment]
Hi [finppp](https://github.com/finppp) 

For the latest release, this is designed behaviour. As I wrote to Pedro above. I understood your user case, and I’m passing it to our Product Manager and Engineers. However, we don’t have an estimated time for a new change. 

This change happened on released 8.3.0 02 Aug 2022 https://github.com/onfido/onfido-sdk-ui/releases/tag/8.3.0 
“Public: Collect country of residence before other profile data”

I do apologize for the inconvenience caused.

Kind regards,
Onfido Support

**Comment by wwwater** [comment]
Hello, we are also concerned about the confusing behaviour described in case 2), namely when using these settings: 
```
documentTypes: {
            "passport": true,
            "driving_licence": { country: "AUS" },
},
```
SDK documentation says 
>Note: You can set the country for all document types except Passport. This is because passports have the same format worldwide so the SDK does not require this additional information.

So, then why to show the country-selection list at all, if SDK does not require this additional information. This is very confusing for the customer, because we want to limit the documents to a certain country and the users are aware of it. We are rejecting the documents from other countries after the check is done in any case, but letting the user to select a country in SDK creates confusion. 
Please consider either allowing to set the country parameter for `passport` document type or stop showing the country drop down in this case.

Our current workaround is to use `hideCountrySelection` in this particular case (1 country + 1 or more document types, when one of them is passport), but this makes our configuration unnecessary confusing.

**Comment by warrenseine** [comment]
I don't have the context about the original issue, but after testing, it seems to me that the note is wrong. At least, while testing the latest SDK, I'm able to set:

```
documentTypes: {
  passport: { country: "AUS" },
  driving_license: { country: "AUS" }
}
```

and it will skip the country selection and show a disabled field:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/539804/219026979-084884f0-15b4-46e4-9967-1381020c755c.png">

**Comment by wwwater** [comment]
@warrenseine indeed, that works! Thanks for discovering this. Could the SDK documentation be adjusted and include the fact that the country can be set for Passport too?

**Comment by warrenseine** [comment]
Yes, we're changing it to:

> Passports have the same format worldwide so the SDK will not show the country selection screen even if they are not restricted by country (e.g. passport: true).
