### ISSUE TITLE
Problem with Babel loader when trying to build on Windows

### ISSUE THREAD

**Issue by alexvw** [onfido/onfido-sdk-ui#205]
Hello - Great SDK. We ran into an issue trying to build it locally, though.

When trying to run the "webpack --progress --display-error-details --bail" step on any windows machine, the build fails on the object rest spread in C:\idw-dev\onfido-sdk-ui\src\index.js:

[0] Hash: b85f25e531d15a7e821e56e8fdf1d327f9517eb1
Version: webpack 2.7.0
Child
    Hash: b85f25e531d15a7e821e
    Time: 407ms
       [0] ./index.js 388 bytes {0} [built] [failed] [1 error]

    ERROR in ./index.js
    Module parse failed: C:\idw-dev\onfido-sdk-ui\src\index.js Unexpected token (13:63)
    You may need an appropriate loader to handle this file type.
    | Tracker.setUp()
    |
    | const ModalApp = ({ options:{ useModal, isModalOpen, buttonId, ...otherOptions},
    |                     ...otherProps}) =>
    |   <Modal {...{useModal, buttonId}} isOpen={isModalOpen}>
    Child html-webpack-plugin for "index.html":
           [0] ../~/lodash/lodash.js 540 kB {0} [built]
           [1] ../~/html-webpack-plugin/lib/loader.js!./index.ejs 4.4 kB {0} [built]
           [2] ../~/webpack/buildin/global.js 509 bytes {0} [built]
           [3] ../~/webpack/buildin/module.js 517 bytes {0} [built]
Child npm-library:
    Hash: 56e8fdf1d327f9517eb1
    Time: 56ms
       [0] ./index.js 388 bytes {0} [built] [failed] [1 error]

    ERROR in ./index.js
    Module parse failed: C:\idw-dev\onfido-sdk-ui\src\index.js Unexpected token (13:63)
    You may need an appropriate loader to handle this file type.
    | Tracker.setUp()
    |
    | const ModalApp = ({ options:{ useModal, isModalOpen, buttonId, ...otherOptions},
    |                     ...otherProps}) =>
    |   <Modal {...{useModal, buttonId}} isOpen={isModalOpen}>

Modifying the .babelrc and dependencies to include/install plugins for the rest spread transform/syntax does not help - in fact, modifying the babel loader settings in .babelrc and within webpack.config.babel.js don't seem to pick up the changes, as if they're being changed elsewhere.

 The environments are capable of workking with object rest spreads in other babel projects on the same machines.

 Any ideas for how to get around this? We have tried many things, but nothing works.

**Comment by rfreitas** [comment]
Hey Alex,

I looks like you are trying to run our development environment, is that the case?
If you want to consume the sdk it's better to use it as an npm module or by using the js file inside of `/dist/`.

If you do want to in fact run the development environment, can you provide us the use case for it?

**Comment by seewah** [comment]
Hi Alex

Have you tried `npm install`, followed by `npm run dev` to debug.

The Onfido SDK is packaged to be used as an npm module. We do not recommend modifying the source for future compatibility reasons, and our team certainly cannot provide technical support to help you customise the SDK via source modification.

Apologies

See Wah
