### ISSUE TITLE
userConsent dashboard settings

### ISSUE THREAD

**Issue by finppp** [onfido/onfido-sdk-ui#2060]
### What was the expected behaviour?
I was hoping to find a setting in the Onfido Dashboard to enable/disable the "userConsent" step

As per migration guide:
```
6.20.0 -> 8.0.0
Change in SDK Options
The userConsent step can't be added in the steps options anymore. This step is now enabled from your Onfido Dashboard.
```

### What happened instead?
I cannot find the settings

Are there any docs on steps to migrate this feature from V6 -> V8, I had a search but no luck

Thanks

### Version info:

- Onfido SDK 8.3.0
- OS OSX
- Browser Chrome
- Device Mac
- Node 16
- Framework or relevant dependencies (if applicable) React

**Comment by gurpreet-onfido** [comment]
Hello Finlay,

Greetings for the day!

I have confirmed with my team and this setting is no longer in the Dashboard as we have now enabled it for everyone by default. 

Please let us know if there is anything else we can help you with.

Kind regards
Gurpreet Singh
