### ISSUE TITLE
Failed to set an indexed property on 'Window': Indexed property setter is not supported. safewoopra.ts:41

### ISSUE THREAD

**Issue by Jhezem** [onfido/onfido-sdk-ui#2068]
### What was the expected behaviour?

Onfido web sdk library load correctly

### What happened instead?

Onfido modules are not being imported correctly, so web SDK is not working.

### Version info:

- OnfidoIDV SDK 8.3.0
- MacOs
- Chrome / Safari
- Web
- Vanilla js
- CMS WordPress

### Integration configuration:

Issue happens when loading the script

### Steps to reproduce:

Please describe in as much detail as possible how to reproduce the problem

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/44304133/186732384-d80b8241-47fc-487e-b350-45b0796b02e8.png">

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/44304133/186732497-16806db6-8331-4330-9090-ddd4d1dda212.png">

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/44304133/186740671-ffe9942b-d48f-4fe0-9d79-227ca2f8c611.png">

Any idea how to solve this issue?

**Comment by gurpreet-onfido** [comment]
Hello @Jhezem 

Greetings for the day!

It looks like the problem has occurred as we moved Woopra to a core module. We could not reproduce this issue and we have not have any other reports on this causing an issue. However, it looks like the combination of frames may have create the ground for this to fail in browser. 

We will be releasing a fix for the reported issue by the end of this month.

We appreciate your understanding & cooperation in this matter. 

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @Jhezem 

We have  removed Woopra from the web SDK in the release [9.1.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/9.1.0).

Kindly upgrade to the latest release and let us know if the issue still persists.

Kind regards
Gurpreet Singh

**Comment by Jhezem** [comment]
Hi @gurpreet-onfido! I was able confirm that the issue was solved, thank you very much for your hard work.

Regards.
