### ISSUE TITLE
Error when trying to teardown sdk in onComplete

### ISSUE THREAD

**Issue by listiani13** [onfido/onfido-sdk-ui#2126]
### What was the expected behaviour?

Should be able to teardown the sdk when `onComplete`. This was working fine in 8.x

### What happened instead?

Got `Cannot set properties of undefined (setting '__h')` error. Suspect this is coming from preact
<img width="956" alt="image" src="https://user-images.githubusercontent.com/24470609/201259381-ed8f9bf4-692c-4856-89d0-32e64b75f21d.png">

### Version info:

- Onfido SDK: 9.1.4
- OS: Mac
- Browser: Firefox 106.0.5 (64-bit) / Chrome 107.0.5304.87 (Official Build) (arm64)
- Device: Macbook Pro
- Node: 16.13.1
- Framework or relevant dependencies (if applicable): using Expo

### Integration configuration:
```typescript
onfidoWebSdk = init({
	useModal: true,
	containerId: "idv-modal",
	isModalOpen: true,
	// We need to set `useMemoryHistory` to true so when we press the back button within the SDK, it doesn't mess up with the browser's history
	// See SDK navigation issues section in https://www.npmjs.com/package/onfido-sdk-ui
	useMemoryHistory: true,
	shouldCloseOnOverlayClick: true,
	steps: [
		{
			type: "document",
			options: {
				documentTypes: {
					driving_licence: {
						country: "AUS",
					},

					passport: {
						country: "AUS",
					},
				},
				forceCrossDevice: true,
			},
		},
		{ type: "face" },
	],
	token: TOKEN,
	onModalRequestClose() {
		onfidoWebSdk?.setOptions({ isModalOpen: false });
		onfidoWebSdk?.tearDown();
	},
	onComplete: () => {
		console.log("onComplete and do nothing");

		onfidoWebSdk?.setOptions({ isModalOpen: false });
		console.log("trying to teardown", onfidoWebSdk?.tearDown);
		onfidoWebSdk?.tearDown();
	},
	onUserExit() {
		onfidoWebSdk?.setOptions({ isModalOpen: false });
		onfidoWebSdk?.tearDown();
	},
});

```

### Steps to reproduce:
1. User initiate for idv check
2. User take selfie & upload docs
3. User submit, and when doing teardown inside onComplete, it throws an error

### Reproducible demo:

https://github.com/listiani13/onfido-sdk-ui-bug-repro

**Comment by Kaynshin** [comment]
I have the same issue

**Comment by warrenseine** [comment]
I am able to reproduce. Thank you for the detailed bug report and reproducible demo. We'll investigate.

**Comment by DannyvanderJagt** [comment]
Hi, we've investigated the issue and we will release a fix for it. Due to the holidays it it may take a bit of time.

In the meantime as a temporary fix, you can replace `onfidoWebSdk?.tearDown();` with:
```
setTimeout(() => {
    onfidoWebSdk?.tearDown();
}, 0)
```

**Comment by listiani13** [comment]
Seems like this has been fixed in latest release
