### ISSUE TITLE
Countries in the list are not visible on dark background surface modal

### ISSUE THREAD

**Issue by syedsaroshfarrukhdot** [onfido/onfido-sdk-ui#2135]
### What was the expected behaviour?

There should be option in `customUI` to set background color of the Country List Drop Down 

On dark background modal the list is not visible currently because it have always a background color `#FFFFFF`
 
![Screenshot 2022-12-09 at 4 31 26 AM](https://user-images.githubusercontent.com/81307212/206591239-679d10ad-9e6f-4e2a-bf9c-4d76412e04b5.png)

There should also be an option in `customUI` to change text color and hover styling of `DocTypeButton` 

Currently, the `DocTypeButton`  button text uses the same color set to `colorContentBody` props in `customUI`.

https://user-images.githubusercontent.com/81307212/206591400-a0a422b5-6115-4129-afe3-4a067cdacbfd.mov

### What happened instead?

No props to customize dropdown which causes country list to be unreadable in dark color surface modal.

### Version info:

- Onfido SDK 7.0.1

### Reproducible demo:

https://github.com/Expensify/App/issues/13262

**Comment by warrenseine** [comment]
Hello @syedsaroshfarrukhdot, thank you for reporting these UI customization issues.

I also feel that the hard-coded drop-down background color is a bug. It should, at the very least, be bound to the `--ods-color-neutral-white` design system variable.

We'll be discussing with the team if we can add customization options for the country selection drop-down background color and for the document type button background color on hover and active states.

The document button text color can be updated with the `colorContentDocTypeButton` customization option (at least the "Passport" text). Now, for the text color _on hover or active states_, I'm under the impression that the customization option was not an oversight. It was left aside for primary and secondary buttons too. There might be a good reason behind this decision. I'll have to confirm with our Design team.

**Comment by syedsaroshfarrukhdot** [comment]
@warrenseine Thank you for getting back. Looking forward to your response after discussions with your team. 

>The document button text color can be updated with the colorContentDocTypeButton customization option (at least the "Passport" text). 

Yes, It Can Be But the `Photo Page` Text Color On DocType Button Is Not Customizable IMO It Should Also Be Customizable. Currently It  Uses The Same Color Used For `colorContentBody`. Which Is Not A Good Idea As DocTypeButton Color Could Be Such Which May Cause `Photo Page` Text To Be Unreadable.

**Comment by syedsaroshfarrukhdot** [comment]
@warrenseine any update ?

**Comment by warrenseine** [comment]
Not yet, we haven't been able to discuss it internally. We'll probably have to wait a bit more.

**Comment by warrenseine** [comment]
We've agreed to add both options, it should be part of the next release.

**Comment by syedsaroshfarrukhdot** [comment]
> We've agreed to add both options (country selection drop-down background color and document type button background color on hover and active states), it should be part of the next release.

@warrenseine That's great to hear do you have an ETA on next planned release ?

**Comment by warrenseine** [comment]
No, only the background colors for now.

**Comment by syedsaroshfarrukhdot** [comment]
@warrenseine Do we have an ETA for next release

**Comment by warrenseine** [comment]
ETA is Jan 16.

**Comment by syedsaroshfarrukhdot** [comment]
Thanks for updating

**Comment by syedsaroshfarrukhdot** [comment]
@warrenseine I wasn't able to find props to change `country selection drop-down background color` in https://github.com/onfido/onfido-sdk-ui/blob/master/UI_CUSTOMIZATION.md. There are only `colorBorderDocTypeButtonHover` and `colorBorderDocTypeButtonActive` props to change document type button background color on hover and active states. Is it released in this update `10.3.0`.

**Comment by syedsaroshfarrukhdot** [comment]
@warrenseine Yes, Thanks it work as expected with `colorBackgroundSelector`. Do we have a prop in this update to change `button background color on hover` as `colorBorderDocTypeButtonHover` only allows to set the border color on hover state ?

**Comment by syedsaroshfarrukhdot** [comment]
You're Welcome, Thanks it works as a charm. Closing this issue. Thanks

**Comment by warrenseine** [comment]
The documentation was updated as well thanks to @DannyvanderJagt 🙇
