### ISSUE TITLE
Is this repo moved to somewhere else?

### ISSUE THREAD

**Issue by umutcanbolat** [onfido/onfido-sdk-ui#2137]
Hi team,

I see that many files including package.json itself were removed with e86a839. Is this repo moved to somewhere or is it not open source anymore?

Thank you.

**Comment by umutcanbolat** [comment]
@DannyvanderJagt

**Comment by DannyvanderJagt** [comment]
@umutcanbolat The source code moved to an in-house repository. The releases will continue to be published on Github and NPM.
