### ISSUE TITLE
Can't resolve 'fs' on OnfidoUI 10.2.0

### ISSUE THREAD

**Issue by basslagter** [onfido/onfido-sdk-ui#2138]
### What was the expected behaviour?

OnfidoUI initializing as before

### What happened instead?

error - ./node_modules/@onfido/opencv/dist/opencv.js:31:1329
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/onfido-sdk-ui/lib/index.js
...

### Version info:

- Onfido SDK
10.2.0
- OS
Mac latest
- Browser
Chrome latest
- Device
Mac
- Node
18.12.0
- Framework or relevant dependencies (if applicable)
NextJs 13.1.1

### Integration configuration:

`
useEffect(
  void (async () => {
    const { init } = await import('onfido-sdk-ui');
    const sdkHandle = init({...});
  })()
`

### Steps to reproduce:

Run app, see error

### Resolution

Reverted to 10.0.2, no issues.

**Comment by basslagter** [comment]
Closing this as it seems not related to Onfido but more on the NextJs side of things

**Comment by osolliec** [comment]
Hello @basslagter 

thanks for reporting this issue. It's on our end, in the @onfido/opencv package. That package has been updated to 1.0.1.
onfido-sdk-ui pulls the ^1.0.0 version. If you delete your package-lock.json and try to reinstall, the issue should go away (please make sure that the version of the @onfido/opencv package is `1.0.1`)
