### ISSUE TITLE
Two values keep highlighted with Onfido country selection dropdown by combining mouse and keyboard movement 

### ISSUE THREAD

**Issue by Pujan92** [onfido/onfido-sdk-ui#2141]
### What was the expected behaviour?

At a moment single option should get highlighted/focused

### What happened instead?

Two options are highlighted

https://user-images.githubusercontent.com/14358475/215989283-99fdbf32-03f3-4234-ad23-c753ce1c7a39.mov

### Version info:

- Onfido SDK: 10.3.0
- OS: macOS
- Browser: Chrome
- Device: MacBook Air M1
- Node: 16.15.1
- Framework or relevant dependencies (if applicable): react-native

### Integration configuration:

https://github.com/Expensify/App/blob/e1c554a1f5dafe3afc787a069001d55372ce98ef/src/components/Onfido/BaseOnfidoWeb.js#L22

### Steps to reproduce:

1. Open country selection dropdown
2. Hover on any option with the mouse to highlight it
3. Use keyboard down key to highlight other option
4. Observe both the mouse and keyboard option keeps highlighted

**Comment by warrenseine** [comment]
This is an expected behaviour in any drop-down list. Users are expected to move their cursor out of the list if using the keyboard. We won't fix this.

**Comment by Pujan92** [comment]
@warrenseine If we consider a normal html dropdown then at a moment we can only focus a single option from the dropdown. Bcoz mouse movement is overwritten by the keyboard and vice versa. Plz have a look at the attached video.

https://user-images.githubusercontent.com/14358475/216313537-2a79fead-ef58-44e6-b4f5-b8cc511cbd7b.mov

**Comment by Pujan92** [comment]
@warrenseine Can you plz confirm one more time whether this needs to be considered an issue or not?

**Comment by warrenseine** [comment]
We'll add this to our backlog, although the priority will be quite low. In the meantime, feel free to just override the CSS. It should be a difference between: `onfido-sdk-ui-CountrySelector-CountryDropdown-custom__option:hover` and `onfido-sdk-ui-CountrySelector-CountryDropdown-custom__option:active`.

**Comment by Pujan92** [comment]
@warrenseine Thanks for considering it. Definitely using the mentioned selectors will be a good help, is it possible for the team to allow customizing those colors bcoz currently it(dropdown) is using the color for hover/focus which we are providing for the button.
