### ISSUE TITLE
How can we contribute?

### ISSUE THREAD

**Issue by s77rt** [onfido/onfido-sdk-ui#2142]
Hi,

Looks like with the release of v10 the source code is no longer present in this repo (after this commit https://github.com/onfido/onfido-sdk-ui/commit/e86a839c2aa81cdda22ea7de72e9aa83935a6b03)

How can we contribute in this case?

Thank you

**Comment by warrenseine** [comment]
The source code moved to an in-house repository. The releases will continue to be published on Github and NPM.

As the project is not open-source anymore, contributions from third-parties are not accepted. Feel free to submit GitHub issues like you did and we'll do our best to prioritise.
