### ISSUE TITLE
Styling issue for Enter Mobile Number input group button

### ISSUE THREAD

**Issue by Pujan92** [onfido/onfido-sdk-ui#2145]
### What was the expected behaviour?

1. borderRadius of `.onfido-sdk-ui-crossDevice-CrossDeviceLink-btn` should be applied over customized `borderRadiusButton` value as this button is grouped with the input

<img width="375" alt="Screenshot 2023-02-11 at 11 49 31 AM" src="https://user-images.githubusercontent.com/14358475/218243868-ac8197ea-668a-4e1d-8391-8a1d4959e10f.png">

2. Min width(maybe 100px) needs to be given to the `Send Link` button so it renders in single line and on click `Sending` text won't overflow

<img width="376" alt="Screenshot 2023-02-11 at 11 50 42 AM" src="https://user-images.githubusercontent.com/14358475/218243886-0877246e-b0a1-49ba-964e-b607035a45e6.png">

### What happened instead?

Incorrect button radius applied to the grouped button

<img width="377" alt="Screenshot 2023-02-11 at 11 34 46 AM" src="https://user-images.githubusercontent.com/14358475/218243330-1c635169-f672-4b0c-b832-769f5d5941cc.png">

Button text overlflows

<img width="378" alt="Screenshot 2023-02-11 at 11 36 03 AM" src="https://user-images.githubusercontent.com/14358475/218243389-cd794f42-d429-488e-a757-f27ba3e2325a.png">

### Version info:

- Onfido SDK: 10.3.0
- OS: macOS
- Browser: Chrome
- Device: MacBook Air M1
- Node: 16.15.1
- Framework or relevant dependencies (if applicable): react-native

### Integration configuration:

https://github.com/Expensify/App/blob/e1c554a1f5dafe3afc787a069001d55372ce98ef/src/components/Onfido/BaseOnfidoWeb.js#L22

### Steps to reproduce:

1. Choose document
2. Select Issuing Country and choose passport document
3. Continue on Phone > Get Secure Link
4. Get link via SMS
5. Observe the button border radius and width for smaller screen

### Reproducible demo:

https://jsfiddle.net/f0cpodaL/

**Comment by Pujan92** [comment]
@warrenseine could you plz check on this issue and provide your thoughts?

**Comment by warrenseine** [comment]
Hello @Pujan92, I'm not responsible for this issue in particular, but this has been raised internally to be prioritised. If there's any urgency, Expensify can raise it though Customer Support.

**Comment by Pujan92** [comment]
Ok @warrenseine, Thanks!

**Comment by warrenseine** [comment]
No, support@onfido.com. Not sure where this web-sdk@onfido.com address goes to (I see it as package author indeed).

**Comment by michaelhaxhiu** [comment]
Thanks!

**Comment by DannyvanderJagt** [comment]
Hi 👋 Thanks for raising the issue. We've addressed it and it will be part of v12.2.0 which is scheduled to be release mid April 2023.

**Comment by michaelhaxhiu** [comment]
Wahoo, thanks so much for your help!
