### ISSUE TITLE
"No such step: auth" console error

### ISSUE THREAD

**Issue by patrykszwed** [onfido/onfido-sdk-ui#2149]
### What was the expected behaviour?

No errors in console. The `auth` step is part of a [documentation](https://documentation.onfido.com/sdk/web/#auth) so I guess there should be no errors or it should be removed from the docs.

### What happened instead?

An error `No such step: auth` is shown.

Console in our app:
![image](https://user-images.githubusercontent.com/32751479/223688060-c74d6ff8-56e7-4c65-b600-64d7253cead9.png)

Console in the demo:
![image](https://user-images.githubusercontent.com/32751479/223687881-dee35881-196b-4741-ab70-94ee19913e24.png)

### Version info:

- Onfido SDK: 11.0.0
- OS: macOS Ventura 13.2.1
- Browser: Google Chrome 110.0.5481.177 (Official Build) (arm64) 
- Device: MacBook Pro M1
- Node: 14.21.2
- Framework or relevant dependencies (if applicable)

### Integration configuration:

It is enough to add `auth` to `steps` array in the demo attached.

### Steps to reproduce:

Just add `auth` to `steps` array in Onfido init function's config.

### Reproducible demo:
https://jsfiddle.net/3bk5rovx/1/

**Comment by warrenseine** [comment]
Hello @patrykszwed, I see that the documentation is still referring to Auth, and this is an oversight from us we'll fix. The product has been discontinued and our Selfie or Motion products can be used for the same business purpose. Feel free to reach out to your Onfido AE and/or CSM. They should be able to detail the context and propose solutions.
