### ISSUE TITLE
consider "driving licence" rather than "driver's licence" in en_GB language

### ISSUE THREAD

**Issue by bmwalters** [onfido/onfido-sdk-ui#2152]
This is a response to a concern previously raised in 2017 [here](https://github.com/onfido/onfido-sdk-ui/issues/257#issuecomment-346377394). 

Previously:
> We are trying to make our products as international as possible and we think that Driver's license is the most widely understood term.

Nowadays the Onfido SDK has support for many languages, so it would be possible to update just the en_GB locale to use the term that is common there.

UK government sites refer to "driving licence":
https://www.gov.uk/browse/driving/driving-licences

The card itself is also apparently titled "driving licence": https://en.wikipedia.org/wiki/Driving_licence_in_the_United_Kingdom#/media/File:UK_full_licence_dec_2021.jpg

### What was the expected behaviour?

All strings referring to driving licences use the phrase "driving licence" rather than "driver's licence" or "driver's license".

https://github.com/onfido/onfido-sdk-ui/blob/93148ca7cc9ef2d21f9719e9e318e943bc2e3fc8/locales/en_GB/en_GB.json#L123-L124
https://github.com/onfido/onfido-sdk-ui/blob/93148ca7cc9ef2d21f9719e9e318e943bc2e3fc8/locales/en_GB/en_GB.json#L132-L133
https://github.com/onfido/onfido-sdk-ui/blob/93148ca7cc9ef2d21f9719e9e318e943bc2e3fc8/locales/en_GB/en_GB.json#L207
https://github.com/onfido/onfido-sdk-ui/blob/93148ca7cc9ef2d21f9719e9e318e943bc2e3fc8/locales/en_GB/en_GB.json#L739

"license":
https://github.com/onfido/onfido-sdk-ui/blob/93148ca7cc9ef2d21f9719e9e318e943bc2e3fc8/locales/en_GB/en_GB.json#L498
https://github.com/onfido/onfido-sdk-ui/blob/93148ca7cc9ef2d21f9719e9e318e943bc2e3fc8/locales/en_GB/en_GB.json#L674

Thank you for reading.

### What happened instead?

We are currently using language phrase overrides to get this behavior and it is suboptimal to maintain as new strings are added.

### Version info:

- Onfido SDK: 12.0.0

### Integration configuration:

N/A

### Steps to reproduce:

N/A

### Reproducible demo:

N/A

#### Thank you!

**Comment by gurpreet-onfido** [comment]
Hello @bmwalters 

Thank you for raising this up. 

We will get this reviewed by our team and update you as soon as we conclude it. 

Thank you so much!

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @bmwalters 

This is to update you that our team updated these strings. We will let you know once they are rolled out. 

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @bmwalters Greetings for the day!

Our team has confirmed that the translations have been updated in v12.3.0+.

Please let us know if there is anything else we can help you with.

Kind regards
Gurpreet Singh
