### ISSUE TITLE
Onfido SDK failed to launch Production React App (Vite)

### ISSUE THREAD

**Issue by milantarami** [onfido/onfido-sdk-ui#2153]
### What was the expected behaviour?

It works fine in dev environment but not working on production 

Note: I am using vite 4.0.4

### Version info:

- Onfido SDK : 10.0.2
- OS : Ubuntu  22.04
- Browser : Microsoft Edge Version 111.0.1661.54 (Official build) (64-bit)
- Node : 18.0.1
- Framework or relevant dependencies (if applicable) : React 18.2.0 , Vite 4.0.4

### Integration configuration:

```
 const onfidoOut = init({
      useMemoryHistory: true,
      token: sdkToken,
      containerId: 'onfido-mount',
      steps: [
        {
          type: 'welcome',
          options: {
            title: 'Complete your KYC verification',
            nextButton: 'Continue',
          },
        },
        "document",
        'face',
        'complete',
      ],
      onComplete: async function (data: any) {
        trigger()
      },
      onError: (e) => {
        // e.type = exception | expired_token | authorization_error
        setIsError(true)
        console.error(e)
      },
      onUserExit: (userExitCode) => {
        console.error(userExitCode)
      },
      customUI: {
        // fonts
        fontFamilyTitle: Fonts.secondary,
        fontFamilyBody: Fonts.primary,
        fontFamilySubtitle: Fonts.secondary,
        fontSizeTitle: '1.2rem',
        fontSizeSubtitle: '1.1rem',
        fontSizeBody: '1rem',
        fontWeightTitle: 500,
        colorContentTitle: alpha(theme.palette.text.primary, 0.87),
        colorContentSubtitle: alpha(theme.palette.text.primary, 0.77),
        colorContentBody: alpha(theme.palette.text.primary, 0.67),

        colorBackgroundSurfaceModal: theme.palette.background.paper,
        borderWidthSurfaceModal: '0',

        //  button
        borderRadiusButton: '30px',

        // primary button
        colorBorderButtonPrimary: 'transparent',
        colorBackgroundButtonPrimary: theme.palette.primary.main,
        colorContentButtonPrimaryText: theme.palette.primary.contrastText,
        colorBackgroundButtonPrimaryActive: theme.palette.primary.main,
        colorBackgroundButtonPrimaryHover: alpha(theme.palette.primary.main, 0.7),

        // secondary button
        colorBorderButtonSecondary: 'transparent',
        colorBackgroundButtonSecondary: theme.palette.secondary.main,
        colorContentButtonSecondaryText: theme.palette.secondary.contrastText,
        colorBackgroundButtonSecondaryActive: theme.palette.secondary.main,
        colorBackgroundButtonSecondaryHover: alpha(theme.palette.secondary.main, 0.7),
      },
    })
```

### Steps to reproduce:

1. user clicks button to launch the onfido SDK
2. SDK does not launch ( no error only sdk version get logged on conolse onfido_sdk_version 10.0.2 728d1d0037b124318118cf7c5780810f07d0eef2 ) 

### Reproducible demo:

Private codebase
[more details](https://github.com/onfido/onfido-sdk-ui/issues/2153#issuecomment-1493282914)

**Comment by milantarami** [comment]
Maybe this is caused due to `js-cookie` package that i am using as dependencies in my project and `Onfido` is also using it as dependencies 

after i remove `js-cookie` code that i am using in my project than it is working in both production & dev.

**Comment by milantarami** [comment]
> Maybe this is caused due to `js-cookie` package that i am using as dependencies in my project and `Onfido` is also using it as dependencies
> 
> after i remove `js-cookie` code that i am using in my project than it is working in both production & dev.
> 
> [Docs: Namespace Conflict Js Cookie](https://github.com/js-cookie/js-cookie#namespace-conflicts)

**Comment by gurpreet-onfido** [comment]
Hello @milantarami 

Thank you for reaching out!

I will check this with our team and will get back to you. 

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @milantarami I hope you are doing well!

Did you get a chance to look into the questions asked by my colleague Olivier?

Looking forward to your response. 

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello there!

Due to lack of response from the reporter, we are closing this thread. Feel free to reach out to us, if you need any help. 

Kind regards
Gurpreet Singh

**Comment by RauppRafael** [comment]
Hi, I'm experiencing the same issue in my nuxt/vue 3 app that also uses Vite, the modal opens normally in the development environment but simply doesn't open in production

**Comment by karamisa** [comment]
Same here. Loading it through CDN fixed the issue. Might be the best option until it is addressed.
