### ISSUE TITLE
Build errors when updating from 6.18.0 to 12.4.0

### ISSUE THREAD

**Issue by coxp** [onfido/onfido-sdk-ui#2172]
We want to implement motion reports and so need to upgrade the SDK to a version greater than 11.0 but unfortunately we have problems building with every version of the library that has been released since 9.9. We are using the npm version of the libary and importing the types directly into our project.

`import { init as onfidoInit, SdkHandle as onfidoSdkHandle } from 'onfido-sdk-ui';`

Using version 12.4.0 gives these errors.

```
./node_modules/node-fetch/index.js:10:11-26 - Error: Module not found: Error: Can't resolve 'http' in '<project>\node_modules\node-fetch'
./node_modules/node-fetch/index.js:11:12-28 - Error: Module not found: Error: Can't resolve 'https' in '<project>\node_modules\node-fetch'
./node_modules/node-fetch/index.js:12:11-26 - Error: Module not found: Error: Can't resolve 'zlib' in '<project>\node_modules\node-fetch'
./node_modules/node-fetch/index.js:13:13-30 - Error: Module not found: Error: Can't resolve 'stream' in '<project>\node_modules\node-fetch'
```

After adding webpack config to resolve these we get the following errors.

```
./node_modules/browserify-zlib/lib/binding.js:4:13-30 - Error: Module not found: Error: Can't resolve 'assert' in '<project>\node_modules\browserify-zlib\lib'
./node_modules/node-fetch/lib/fetch-error.js:29:0-24 - Error: Module not found: Error: Can't resolve 'util' in '<project>\node_modules\node-fetch\lib'
./node_modules/@onfido/active-video-capture/dist/index.umd.cjs:7757:18-33 - Error: Module not found: Error: Can't resolve 'util' in '<project>\node_modules\@onfido\active-video-capture\dist'
```

```
module.exports = {
  resolve: {
    fallback: {
      assert: require.resolve('assert/'),
      http: require.resolve('stream-http'),
      https: require.resolve('https-browserify'),
      stream: require.resolve('stream-browserify'),
      util: require.resolve('util/'),
      zlib: require.resolve('browserify-zlib')
    }
  }
};
```

Finally adding the remaining libraries to the webpack config as above and installing the required dependencies, we are left with a single warning.

`./node_modules/encoding/lib/iconv-loader.js:9:12-34 - Warning: Critical dependency: the request of a dependency is an expression
`

Additionally, the module containing the library increases in size by over 11Mb. Are we missing something here and there's an easier way to consume the library in an Angular project?

**Comment by coxp** [comment]
Still fails in v13.0.0-rc1 with the basic new angular project and installing the onfido-sdk-ui. Are you meaning to depend on node.js specific packages?

```
Warning: <project>\src\app\app.component.ts depends on 'onfido-sdk-ui'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

./node_modules/onfido-sdk-ui/lib/index.js:5069:17-42 - Error: Module not found: Error: Package path . is not exported from package <project>\node_modules\@onfido\opencv (see exports field in <project>\node_modules\@onfido\opencv\package.json)

./node_modules/@onfido/active-video-capture/dist/index.umd.cjs:6575:18-33 - Error: Module not found: Error: Can't resolve 'util' in '<project>\of-example\node_modules\@onfido\active-video-capture\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
```

**Comment by warrenseine** [comment]
Hello @coxp, sorry I didn't answer earlier.

Thanks for reporting this issue. We will get to it. It didn't make it to rc.1, and I cannot promise it will be fixed in v13, but we're aware of it.

We sure do not intend to depend on Node.js builtins. We'll get rid of them. I'm not sure why this specifically causes issues with Angular, because I'm able to build with Webpack 5 otherwise. We will figure this out.

**Comment by coxp** [comment]
Thanks. I think the issue may be that Angular is built around using standard ES modules (although it does support CommonJS modules with warnings) and I believe the Onfido SDK is bundled as only a CommonJS module. Although you clearly can't test for every framework I think it might be a good idea to have a sample app with a framework that uses ES modules alongside the current sample apps that use vanilla JS and React. 

There is a sample repo [here ](https://github.com/coxp/of-example)of a new angular project with the basic Onfido SDK component initialised that shows the error.

```
npm install
npm run build
```

**Comment by coxp** [comment]
The first build error seems to be cause by the addition of these lines to the @onfido\opencv package.json. I think bundling all the Onfido libraries to support both a CommonJS and ESM version would resolve all the issues.

 ```
"exports": {
    ".": {
      "import": "dist/opencv.js",
      "types": "dist/types/index.d.ts"
    },
    "./wasm": {
      "import": "dist/opencv.wasm.js",
      "types": "dist/types/index.d.ts"
    }
  },
```

**Comment by gurpreet-onfido** [comment]
Hello Paul,

Greetings for the day!

Our team has confirmed that a fix has now released in our SDK version 13.0.0. You are requested to upgrade to this version and let us know how it goes. 

Kind regards
Gurpreet Singh

**Comment by warrenseine** [comment]
Thank you for pointing it out! We have an issue in our CI that adds the `latest` tag to any release, even when patching previous versions. I have fixed it manually, and we'll be looking into the CI bug 🙇🏻

**Comment by coxp** [comment]
Hi, v13.1.0 resolves the issue with requiring any browser polyfills but the module size is now 5x larger than the earlier library. I'll close this issue and open a separate one for that though.
