### ISSUE TITLE
Next13 pressing back on onfido-sdk-ui causing hard refresh of page

### ISSUE THREAD

**Issue by TikiCat7** [onfido/onfido-sdk-ui#2181]
### What was the expected behaviour?
Pressing back between steps in the onfido-sdk-ui should not cause the entire page to be refreshed.

### What happened instead?
The entire page refreshes.

### Version info:

- Onfido SDK 13.2.0
- OS MacOS Ventura 13.4.1
- Browser Arc 1.3.0, Chrome 115.0.5790.170 (Official Build) (arm64)
- Device Macbook Pro 14 2021 M1
- Node 16.15.1
- Framework or relevant dependencies (if applicable)
- nextjs 13.4.8
- react 18.2.0

### Integration configuration:
`/app/onfido/page.tsx`
```typescript
"use client"

import { useEffect } from "react"
import { init } from "onfido-sdk-ui"

export default function OnfidoPanel({
  workflowRunId,
  sdkToken,
}: {
  workflowRunId: string
  sdkToken: string
}) {
  useEffect(() => {
    init({
      workflowRunId,
      token: sdkToken,
      containerId: "onfido-mount",
      onComplete: function (data) {
        console.log("onfido flow complete")
      },
    })
  }, [])
  return <div id="onfido-mount"></div>
}
```
- hard coding the token and workfloRunId produces the same result as passing props from a server component.

### Steps to reproduce:
Basic implementation of onfido-sdk-ui in a next13 app router setup.
Upon loading the page SDK loads fine.
Navigating through the steps forward works fine.
Anytime I press back on a step, the entire page refreshes making the user lose all progress.

### Reproducible demo:
reproducible demo: https://github.com/TikiCat7/onfido-refresh-issue
(please add token + workflow id in the page.tsx init call)

https://github.com/onfido/onfido-sdk-ui/assets/15680763/9f9be534-419f-468d-af2c-c7c1936377a7

**Comment by edd-singlifeph** [comment]
@TikiCat7 i experience similar problem and solved it by adding  `useMemoryHistory: true` on the options of init

```
"use client"

import { useEffect } from "react"
import { init } from "onfido-sdk-ui"

export default function OnfidoPanel({
  workflowRunId,
  sdkToken,
}: {
  workflowRunId: string
  sdkToken: string
}) {
  useEffect(() => {
    init({
      workflowRunId,
      token: sdkToken,
      useMemoryHistory: true, // add this line
      containerId: "onfido-mount",
      onComplete: function (data) {
        console.log("onfido flow complete")
      },
    })
  }, [])
  return <div id="onfido-mount"></div>
}
```

**Comment by TikiCat7** [comment]
thank you @edd-singlifeph, that resolved the issue 🙇🏼
