### ISSUE TITLE
UI not appearing on mobile size screen

### ISSUE THREAD

**Issue by JadSayegh** [onfido/onfido-sdk-ui#234]
When I shrink the screen to mobile size the UI doesn't show up. I can make it work by removing the style on the following CSS selector:
```
@media (max-width: 30em) .onfido-sdk-ui-Modal-inner
```

**Comment by hjheath** [comment]
Hi Jad, thanks for raising the issue, please could you help me to reproduce it.

Can you reproduce it here: https://jsfiddle.net/4xqtt6fL/60/ if so please outline the steps you took to reproduce it. Could you also let me know what browser (type and version) you are using.
