### ISSUE TITLE
Asks to use microphone & tries to capture when mic (but not camera) is available

### ISSUE THREAD

**Issue by francisjervis** [onfido/onfido-sdk-ui#26]
As per title - on a MBP with closed lid & external display (so, mic available but not camera), page load triggers a request to access the microphone. This is probably related to the behavior seen in the shot attached - it appears that the script is currently not detecting capture devices correctly in edge cases.

![screen shot 2016-06-17 at 11 10 07 pm](https://cloud.githubusercontent.com/assets/10519862/16169407/0ee19d92-34e1-11e6-9b1f-fbd69fece53d.png)

**Comment by hjheath** [comment]
Thanks we are taking a look.

@gosseti - I think we can fix this by specifying video only when calling getUserMedia

**Comment by rfreitas** [comment]
Hi Francis,

Can you let us know which browser you are using?

**Comment by francisjervis** [comment]
This was in Chrome.

**Comment by francisjervis** [comment]
Still seeing this intermittently.
![screen shot 2016-07-25 at 2 45 19 am](https://cloud.githubusercontent.com/assets/10519862/17097275/0ac1fb64-5212-11e6-84b2-4cbb2a65c46b.png)

**Comment by rfreitas** [comment]
It seems that part of the problem is with Chrome and your webcam. Can you visit this webpage: https://www.onlinemictest.com/webcam-test

The other part of the problem, is that the code should automatically adapt in case there is no webcam available.

**Comment by hjheath** [comment]
Fixed as part of https://github.com/onfido/onfido-sdk-ui/pull/152
