### ISSUE TITLE
Bootstrap 3 styling issue

### ISSUE THREAD

**Issue by ipridham** [onfido/onfido-sdk-ui#264]
Seems that the CSS does not play nicely with BS3 (BS4 is fine), see https://jsfiddle.net/4xqtt6fL/112/ as an example (based on your own original fiddle)

**Comment by hjheath** [comment]
Hi, thanks for raising the issue. We have a bug where some layouts are based on the base font size. When bootstrap is changes the font size to something we don't expect the layouts break.

We plan to fix this bug soon so you will be able to change the font size without breaking the SDK layout.

As a quick fix you can change the font size bootstrap is setting on the `html` element from `10px` to `16px`.

**Comment by snkashis** [comment]
Any movement on this?

**Comment by rfreitas** [comment]
Unfortunately not. Next quarter there will be a greater focus on accessibility and changing the units to comply with the change base font size requirement is one of the first tasks. Sorry about that.

**Comment by rfreitas** [comment]
Should be fixed once this PR https://github.com/onfido/onfido-sdk-ui/pull/544 goes live

**Comment by stefaniacardenas** [comment]
Fixed in [v4.0.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/4.0.0)
