### ISSUE TITLE
Include other languages

### ISSUE THREAD

**Issue by daninfpj** [onfido/onfido-sdk-ui#273]
It’s very important for us to be able to show the widget in different languages (spanish, initially). We’d be willing to contribute a PR once we’ve agreed on the proper way to implement it. Maybe something along the lines of [Airbnb’s Polyglot.js](https://github.com/airbnb/polyglot.js)?

Cheers!

**Comment by seewah** [comment]
We are starting to explore language localisation now, to in fact, support Spanish initially. Timeline will be roughly over the next couple of months (with obviously Christmas and new year coming up). Thanks for including link to this library. @hjheath @stefaniacardenas this maybe of interest to you?

**Comment by rfreitas** [comment]
ref: https://github.com/onfido/onfido-sdk-ui/pull/285

**Comment by daninfpj** [comment]
Closing since discussion is on #285
