### ISSUE TITLE
Customisation of  Steps 

### ISSUE THREAD

**Issue by shftx70** [onfido/onfido-sdk-ui#303]
Hi,

I'm interested in integrating Onfido SDK directly into our website. We need to collect Passport/Driving licence and also documents such as a utility bill.

I'm looking for a solution whereby I can add in an extra stage, after the selfie verification so that the user can submit their utility bill and have it sent directly to our email.

1. User uploads passport/driving licence - Processed by Onfido
2. Selfie verification -  Processed by Onfido
3. Custom stage - User uploads a document which is not processed by Onfido

I'm thinking of hiring a developer to do this, would such a solution be possible?

Thanks

**Comment by seewah** [comment]
That is not possible right now I am afraid. Though what you are looking for is on the roadmap. If you want to find out more, please send an email to api@onfido.com mentioning this github issue? Many thanks
