### ISSUE TITLE
Reduce size...

### ISSUE THREAD

**Issue by RobertLowe** [onfido/onfido-sdk-ui#317]
403 KB *minified*?

There's really a lot of deps in this...

**Comment by rfreitas** [comment]
Hi @RobertLowe we are aware of our large bundle size, we are in the process of splitting into smaller chunks.
You can also defer the download of the sdk in case you have a UI that precedes this sdk.

In terms of dependencies we do try to pick the slimmest, is any dependency that you think it's clearly redundant?

**Comment by RobertLowe** [comment]
Off the top `socket.io`, consider detecting it or loading from CDN. Lot's of `react` stuff, I would expect you to switch tracks, but it's kind of extra weight for angular, meteor, etc projects.

I wrote a script to scan I'll probably package for NPM, but here's some hinting:


        wpt@https://github.com/onfido/js-client-tracker/tarball/master size:  127 Bytes
        indexof@0.0.1                            size:  698 Bytes
        component-inherit@0.0.3                  size: 1020 Bytes
        callsite@1.0.0                           size:       1 KB
        standalone-react-addons-pure-render-mixin@0.1.1 size:       1 KB
        component-bind@1.0.0                     size:       1 KB
        shebang-regex@1.0.0                      size:       1 KB
        supports-webp@1.0.3                      size:       1 KB
        to-array@0.1.4                           size:       1 KB
        has-cors@1.1.0                           size:       1 KB
        object-component@0.0.3                   size:       1 KB
        backo2@1.0.2                             size:       1 KB
        shebang-command@1.2.0                    size:       2 KB
        isarray@2.0.1                            size:       2 KB
        is-stream@1.1.0                          size:       2 KB
        has@1.0.1                                size:       2 KB
        element-class@0.2.2                      size:       2 KB
        parse-unit@1.0.1                         size:       2 KB
        parseqs@0.0.5                            size:       2 KB
        arraybuffer.slice@0.0.6                  size:       2 KB
        has-binary2@1.0.2                        size:       2 KB
        exenv@1.2.0                              size:       2 KB
        blob@0.0.4                               size:       2 KB
        better-assert@1.0.2                      size:       2 KB
        parseuri@0.0.5                           size:       2 KB
        base64-arraybuffer@0.1.5                 size:       2 KB
        amator@1.0.1                             size:       3 KB
        object-assign@4.1.1                      size:       3 KB
        value-equal@0.2.1                        size:       3 KB
        dasherize@2.0.0                          size:       3 KB
        foreach@2.0.5                            size:       3 KB
        ms@2.0.0                                 size:       3 KB
        is-windows@1.0.1                         size:       3 KB
        loose-envify@1.3.1                       size:       3 KB
        warning@3.0.0                            size:       3 KB
        component-emitter@1.2.1                  size:       3 KB
        after@0.8.2                              size:       3 KB
        symbol-observable@0.2.4                  size:       3 KB
        yeast@0.1.2                              size:       3 KB
        hoist-non-react-statics@2.3.1            size:       3 KB
        for-each@0.3.2                           size:       3 KB
        setimmediate@1.0.5                       size:       3 KB
        isomorphic-fetch@2.2.1                   size:       3 KB
        type-detect@0.1.1                        size:       3 KB
        encoding@0.1.12                          size:       3 KB
        pseudomap@1.0.2                          size:       3 KB
        symbol-observable@1.1.0                  size:       3 KB
        resolve-pathname@2.2.0                   size:       3 KB
        deep-eql@0.1.3                           size:       4 KB
        isexe@2.0.0                              size:       4 KB
        ultron@1.1.1                             size:       4 KB
        invariant@2.2.2                          size:       4 KB
        json-stringify-safe@5.0.1                size:       4 KB
        which@1.3.0                              size:       4 KB
        yallist@2.1.2                            size:       4 KB
        clone@1.0.3                              size:       4 KB
        pdfobject@2.0.201604172                  size:       5 KB
        bezier-easing@2.0.3                      size:       5 KB
        define-properties@1.1.2                  size:       5 KB
        cross-env@3.2.4                          size:       6 KB
        style-builder@1.0.13                     size:       6 KB
        pretty-format@3.8.0                      size:       6 KB
        js-tokens@3.0.2                          size:       6 KB
        lru-cache@4.1.1                          size:       6 KB
        cross-spawn@5.1.0                        size:       6 KB
        lodash.assign@4.2.0                      size:       6 KB
        is-date-object@1.0.1                     size:       6 KB
        function-bind@1.1.1                      size:       6 KB
        attr-accept@1.1.0                        size:       6 KB
        classnames@2.2.5                         size:       6 KB
        socket.io-parser@3.1.2                   size:       6 KB
        url-search-params@0.10.0                 size:       6 KB
        is-regex@1.0.4                           size:       7 KB
        hoist-non-react-statics@1.2.0            size:       7 KB
        is-symbol@1.0.1                          size:       7 KB
        whatwg-fetch@2.0.3                       size:       7 KB
        minimist@1.2.0                           size:       8 KB
        string.prototype.trim@1.1.2              size:       8 KB
        regenerator-runtime@0.11.1               size:       8 KB
        keypather@1.10.2                         size:       8 KB
        is-callable@1.1.3                        size:       8 KB
        object-keys@1.0.11                       size:       8 KB
        eventemitter2@2.1.3                      size:       9 KB
        safe-buffer@5.1.1                        size:       9 KB
        es-to-primitive@1.1.1                    size:       9 KB
        visibilityjs@1.2.4                       size:       9 KB
        scroll-into-view-if-needed@1.4.0         size:       9 KB
        xmlhttprequest-ssl@1.5.4                 size:      10 KB
        immutability-helper@2.6.0                size:      10 KB
        asap@2.0.6                               size:      11 KB
        engine.io-parser@2.1.1                   size:      11 KB
        object-loops@0.8.0                       size:      12 KB
        xml2js@0.4.19                            size:      12 KB
        babel-runtime@6.26.0                     size:      13 KB
        reselect@2.5.1                           size:      14 KB
        dnd-core@2.5.4                           size:      14 KB
        enumerate-devices@1.1.1                  size:      15 KB
        sax@1.2.4                                size:      15 KB
        async-limiter@1.0.0                      size:      16 KB
        promise@7.3.1                            size:      16 KB
        debug@2.6.9                              size:      16 KB
        countup.js@1.8.1                         size:      16 KB
        101@1.6.2                                size:      16 KB
        preact-transition-group@1.1.1            size:      18 KB
        xmlbuilder@9.0.4                         size:      19 KB
        ws@3.3.2                                 size:      22 KB
        prop-types@15.6.0                        size:      23 KB
        react-dropzone@3.4.0                     size:      23 KB
        react-redux@4.4.6                        size:      25 KB
        react-dnd-html5-backend@2.5.4            size:      27 KB
        history@4.5.1                            size:      27 KB
        node-fetch@1.7.3                         size:      27 KB
        blueimp-load-image@2.12.2                size:      27 KB
        es-abstract@1.10.0                       size:      28 KB
        react-webcam-onfido@0.1.0                size:      30 KB
        redux@3.7.2                              size:      30 KB
        redux@3.5.2                              size:      30 KB
        input-format@0.1.15                      size:      34 KB
        react-modal-onfido@1.5.2                 size:      35 KB
        disposables@1.0.1                        size:      38 KB
        preact-render-to-string@3.7.0            size:      39 KB
        ua-parser-js@0.7.17                      size:      39 KB
        is-function@1.0.1                        size:      42 KB
        engine.io-client@3.1.4                   size:      45 KB
        preact-compat@3.16.0                     size:      46 KB
        react-styling@1.6.4                      size:      54 KB
        react-dnd@2.5.4                          size:      67 KB
        es6-promise@4.1.1                        size:      74 KB
        react-modal@3.1.8                        size:     122 KB
        fbjs@0.8.16                              size:     123 KB
        bluebird@3.5.1                           size:     132 KB
        react@15.4.2                             size:     139 KB
        lodash-es@4.17.4                         size:     150 KB
        raven-js@3.9.1                           size:     154 KB
        preact@8.2.6                             size:     158 KB
        react-day-picker@6.2.1                   size:     161 KB
        react-native-listener@1.0.1              size:     176 KB
        iconv-lite@0.4.19                        size:     182 KB
        socket.io-client@2.0.4                   size:     228 KB
        react-responsive-ui@0.10.9               size:     247 KB
        lodash@4.17.4                            size:     303 KB
        node-polyglot@2.2.2                      size:     340 KB
        libphonenumber-js@0.4.44                 size:     351 KB
        core-js@1.2.7                            size:     356 KB
        react-dom@15.4.2                         size:     517 KB
        core-js@2.5.3                            size:     573 KB
        react-phone-number-input@0.15.2          size:       4 MB
        ---------------------------------------------------------
        core-js found with competing versions: [ '2.5.3', '1.2.7' ]
        redux found with competing versions: [ '3.7.2', '3.5.2' ]
        hoist-non-react-statics found with competing versions: [ '2.3.1', '1.2.0' ]
        symbol-observable found with competing versions: [ '0.2.4', '1.1.0' ]
        ---------------------------------------------------------
        Deps scanned: 147  dups: 4
        ---------------------------------------------------------
        These are TGZ compressed sizes of the whole NPM module, but 
        may give a relativistic idea of package weight.

**Comment by pashka4281** [comment]
oh wow `react-phone-number-input@0.15.2          size:       4 MB` - this thing comes with some sort of example ui images here https://github.com/catamphetamine/react-phone-number-input/tree/master/docs/images which I believe make a large portion of that size.

Also I noticed you guys have both react & preact, may I know why? It seems like they're self-excluding. I'd assume you're in the process of migrating and we shall expect soon see how react leaves packages.json.

**Comment by RobertLowe** [comment]
@pashka4281 relativistic weight, outliers can have bloat that's not `required`

**Comment by rfreitas** [comment]
Hi @RobertLowe,

Thanks for sharing the info. We actually have it on our roadmap to move socket.io to a separate chunk, but not top priority for now, unless this is a blocker in your integration.
`react-phone-number-input` is already in a separate chunk so it won't interfere with first load.

As a temporary workaround is also possible to defer the loading of our bundle incase you have a UI you shown before our sdk (but that is a big if).

For React and React Dom, this is actually a great catch, since this dependency was not being used, we will remove it but it won't impact bundle size.

There is also another known issue, which is if you use the project through npm, our dependencies will come pre bundled, which means you won't have size savings in case we share dependencies and they match. Addressing this is also in our backlog.

**Comment by RobertLowe** [comment]
@rfreitas no blockers for us, we have an internal PR to pull from the CDN as it seems to be more optimal for our app (having more NPM packages around seemed to slow meteor down during build and rebuild times). 

`package-lock.json` scanner released here: https://www.npmjs.com/package/fatapp

Cheers

**Comment by rfreitas** [comment]
15% bundle reduction and size reports automatically generated. Closing this issue.
