### ISSUE TITLE
Bootstrap compatibility

### ISSUE THREAD

**Issue by francisjervis** [onfido/onfido-sdk-ui#32]
Some of the CSS styling interferes with Bootstrap 3 default classes, causing eg. navbar to be displayed improperly where the Onfido sdk-ui CSS has also been imported. See image in comment on #25.

**Comment by rfreitas** [comment]
are you still experiencing interference? [PR#52](https://github.com/onfido/onfido-sdk-ui/pull/52) adds prefixes to all selectors, greatly reducing chances of interference.

**Comment by rfreitas** [comment]
I'm closing this issue due to lack of information.
