### ISSUE TITLE
Any ETA for Swift 4.1 update?

### ISSUE THREAD

**Issue by ImmanuelKannan** [onfido/onfido-sdk-ui#321]
Hi guys, I updated Xcode and its now using Swift 4.1. I tried to build my project and got this compiler error: "Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1". Any ideas when Onfido will be updated to Swift 4.1?

**Comment by rfreitas** [comment]
Hi @ImmanuelKannan this is the repo for the JS SDK.
Please visit https://github.com/onfido/onfido-ios-sdk for the iOS SDK.
