### ISSUE TITLE
Onfido's init method doesn't appear to work from React's componentDidMount

### ISSUE THREAD

**Issue by micahblu** [onfido/onfido-sdk-ui#330]
I'm trying to initiate Onfido from within a React application. I have built a very simple Onfido React component but it's not working. I've followed the instructions very carefully but to not avail.

In the index.html I have before closing body tag:
`<div id='onfido-mount'></div>`

This is the component script:
```js
import React from 'react'
import Onfido from 'onfido-sdk-ui'

class OnfidoField extends React.Component<any, any> {
  constructor(props) {
    super(props)
    this.state = Object.assign({}, this.props)
  }
  componentWillReceiveProps(nextProps) {
    this.setState(Object.assign({}, this.state, nextProps))
  }
  componentDidMount() {
    console.log('this.state.onfidoToken', this.state.onfidoToken)
    if (this.state.onfidoToken) {
      console.log('INITTING ONFIDO', document.getElementById('onfido-button'), document.getElementById('onfido-button'))
      Onfido.init({
        useModal: true,
        token: this.state.onfidoToken,
        containerId: 'onfido-mount',
        buttonId: 'onfido-button',
        steps: [
          'welcome',
          'document',
          'complete'
        ],
        onComplete: function () {
          console.log("everything is complete")
        }
      })
    }
  }
  render({ field, onfidoToken } = this.state) {
    return (
      <div>
        <button id='onfido-button' disabled></button>
      </div>
    )
  }
}

export default OnfidoField
```
The component is mounted and the onfido init does produce in the console log `onfido_sdk_version 2.3.0` but does not update the onfido button which shows as a button element with no values so a little blank square.

As you can see in the componentDidMount I console log both onfido elements and they do show so they are available to the DOM at the moment onfido.init is called. I've also confirmed the token is passed.

Any help would be appreciated.

**Comment by rfreitas** [comment]
if you don't use `useModal` does it work?

If you are using React I recommend not using the `buttonId`, because our sdk is actually changing stuff in the DOM for that element. Better is to have your own button and when it get called you open the sdk modal programatically yourself.

**Comment by ernaneluis** [comment]
How could I have access to the onfido object at `onModalRequestClose` callback? 

```
const mapDispatchToProps = dispatch => ({
  initOnfido: ({ onfidoToken }) => {
    const onfido = Onfido.init({
      token: onfidoToken,
      containerId: 'onfido-mount', // id of the element you want to mount the component on
      isModalOpen: false,
      useModal: true,
      onComplete: () => {
        console.log('everything is complete')
        // tell your backend service that it can create the check
        dispatch(toProfile({ step: 4 }))
      },
    })

    onfido.setOptions({
      onModalRequestClose: e => {
        onfidoObj.setOptions({ isModalOpen: false })
      },
    })
    return onfido
  },
  openOnfido: onfidoObj => {
    onfidoObj.setOptions({ isModalOpen: true })
  },
})
```

**Comment by rfreitas** [comment]
in `onModalRequestClose ` shouldn't `onfidoObj` be `onfido` instead? Also where can `openOnfido` get the reference for `onfidoObj`?

**Comment by alonp99** [comment]
I have the same issue when using `useModal: true`.
Tried with and without buttonId.

@rfreitas Any ideas?

**Comment by alonp99** [comment]
@micahblu did you solved it?

**Comment by stefaniacardenas** [comment]
In [version 3.0.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/3.0.0) we have removed support for `buttonId` therefore you will have to programmatically trigger the modal and close the modal on `onModalRequestClose`. For more details, check out the [migration notes](https://github.com/onfido/onfido-sdk-ui/blob/master/MIGRATION.md). For a react example (we use `preact`), check out this [demo](https://github.com/onfido/onfido-sdk-ui/blob/master/src/demo/demo.js). I will close this issue for now but feel free to follow up if you find any other issue.
