### ISSUE TITLE
Request: allow passing options to Raven config

### ISSUE THREAD

**Issue by jord-goldberg** [onfido/onfido-sdk-ui#338]
Hi, I'm currently working on integrating the onfido sdk into an existing web application. This application has certain requirements - one requirement is detecting when the browser developer console is open to prevent a user from spoofing their GPS coordinates. One strategy we've been using for chrome successfully can be found in [this stackoverflow answer](https://stackoverflow.com/questions/7798748/find-out-whether-chrome-console-is-open).

Unfortunately, the default config of Raven uses console.log output for breadcrumbs. Without setting the Raven autoBreadcrumbs.console config option to false, the SO answer linked above incorrectly shows the console is open all of the time.

If we could pass a ravenConfig option to the Onfido.init method, this would absolutely solve our issue with the client SDK. This seems like a pretty simple thing, so I'd be willing to fork and make a pull request if you are open to that.

**Comment by rfreitas** [comment]
Hi @jord-goldberg,

For your particular case, have you been able to fork and consume your changes?

We have been taking a look at this (sorry we didn't reply earlier), it seems we don't need that option at all. Assuming that is true the best option would be for us to just turn it off, without giving the option to turn it on in the settings.

We will be testing this out next week, let me know if you are blocked in the meantime.

**Comment by jord-goldberg** [comment]
Yes, we were able to disable the breadcrumbs and are using the SDK without issue right now. Thanks for the response - if turning off breadcrumbs altogether is OK with you, that works great for us.

**Comment by stefaniacardenas** [comment]
Hi, this issue has been fixed in [version 3.0.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/3.0.0) therefore I will close this issue for now but feel free to follow up if you have any other issue.
