### ISSUE TITLE
error callback to renew the jwt token

### ISSUE THREAD

**Issue by HoneyryderChuck** [onfido/onfido-sdk-ui#348]
We are having some trouble using the SDK when a JWT has expired, as we don't have a way to know this on the client side. 

Our JWTs are generated in the backend and sent to the frontend. **If** the user doesn't complete the flow and comes back later to it, he will receive the same JWT, and calls for document upload will fail with 401 "token has expired". The problem here is, the SDK doesn't have a way (a callback) to tell us about this issue, and we can't recover from it, and we can't help the user. 

My suggestion: some callback (i.e.: `onTokenExpired`) that we can piggy-back on. This way, we can renew a token (or generate a new one) and restart the flow for the user.

**Comment by rfreitas** [comment]
Hi @HoneyryderChuck ,

Is it possible from your side to generate a jwt every time you are going to initialise the sdk?

**Comment by HoneyryderChuck** [comment]
Not really, and specially because this can happen with users who keep their tab open. Would be cool to act upon such errors.

**Comment by HoneyryderChuck** [comment]
Went ahead and implemented a "new jwt token on every session" scheme, which mostly works. It will still fail if the user doesn't refresh the page and lets the token expire (a real-world use case is when finding some document takes longer than expected), and it's hard to say if the "Connection was lost" error message will lead the user to refresh the page. So I leave you with the "feature request".

**Comment by rfreitas** [comment]
It's a fair point and one we have considered before as well. In case the jwt for every session approach stops working for you or yields too many errors, do let us know. We will also look into having a callback for this feature if the complexity is small.

**Comment by HoneyryderChuck** [comment]
thx for the feedback @rfreitas , will let you know if it ever comes to that!

**Comment by jdimmerman** [comment]
@rfreitas - This is something that Zipcar is running into as well. I'd love the ability to handle via a callback as it's the most elegant solution for this that we can think of (but open to alternatives!). We do get a new token upon every session, but our users may to leave tabs open.

Thanks!
