### ISSUE TITLE
Can we take the video also instead the Selfie like we can do with Adnroid and IOS mobile devices?

### ISSUE THREAD

**Issue by mukeshkumar1986** [onfido/onfido-sdk-ui#357]
Can we take the video also with web ui instead the Selfie like we can do with Adnroid and IOS mobile devices?

Is there option available to capture the video with UI sdk like IOS and Android sdk?

**Comment by Gorbyy** [comment]
Hi,

Unfortunately that is not possible at the moment but with are working on it and we estimate to have a beta version available later this month.

Cheers

**Comment by seewah** [comment]
Hi the feature is coming out towards the end of the July. We will advertise it in the changelog when it is released. So please check back in in about a month's time.
