### ISSUE TITLE
Not compatible with no-eval CSP

### ISSUE THREAD

**Issue by tony-blockchain** [onfido/onfido-sdk-ui#380]
Currently `onfido-sdk-ui` is not working without adding `script-src 'unsafe-eval'` CSP header.
This issue compromises security of any page with `onfido-sdk-ui` on it.

The problem is the script-loader used in Tracker:
https://github.com/onfido/onfido-sdk-ui/blob/beaad7fda1bc5ad6685ccba01c73d1a44243128c/src/Tracker/index.js#L4

Shouldn't be too hard to change [old-style export](https://github.com/onfido/js-client-tracker/blob/2b6635ea3379a9462d50a6eb3b47811dd51519b4/wpt.js#L1642-L1670) to commonjs

**Comment by rfreitas** [comment]
It's a good point. We will create a task around it. In case you have already done it, we won't mind a PR :)

**Comment by stefaniacardenas** [comment]
Hi, this issue has been fixed in [version 3.0.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/3.0.0) therefore I will close this issue for now but feel free to follow up if you have any other issue.
