### ISSUE TITLE
nextButton option does not apply overridden text

### ISSUE THREAD

**Issue by ctrlaltdylan** [onfido/onfido-sdk-ui#391]
On instantiation in the `options` object if you pass a `nextButton` string it does not actually update the button in the "welcome" step:

        var onfido = Onfido.init({
          token: data.token,
          containerId: 'id-verification-wizard',
          steps: [
            {
              type: 'welcome',
              options: {
                nextButton: 'Next'
              }
            }
          ]
        })

This does not update the `welcome.next_button` to the string `'Next'`. Instead you have to pass into the `language` option:

        var onfido = Onfido.init({
          token: data.token,
          containerId: 'id-verification-wizard',         
          language: {
            locale: 'en',
            phrases: { welcome: { next_button: 'Next' } },
          }
        })

**Comment by rfreitas** [comment]
I believe this might be by design, pinging @stefaniacardenas

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan,
Thanks for pointing that out. I believe this is a regression and we will try to fix it as soon as possible.
In the meanwhile, please keep using the `language` options to override the button string.

**Comment by josokinas** [comment]
@stefaniacardenas The fix has been merged to development branch, please close the issue when it's released. Thank you!

**Comment by stefaniacardenas** [comment]
Thanks @josokinas

**Comment by stefaniacardenas** [comment]
This issue has been fixed in version `5.5.0`. Closing this issue now.
