### ISSUE TITLE
Do you accept PRs for new locales?

### ISSUE THREAD

**Issue by Aralun** [onfido/onfido-sdk-ui#398]
I intend to translate the SDK into French for our app.  
Would you accept a PR with the translation? I assume it'd be hard to maintain it if you don't have someone fluent already.

**Comment by Aralun** [comment]
Well, the translation is achieved both for mobile and desktop.

**Comment by GiuliaDi** [comment]
Hi Aralun,
I would advise checking the "Customising SDK" section of our documentation, that shows you how to customise the SDK language by overriding the locale and strings.
https://github.com/onfido/onfido-sdk-ui
Best regards
Giulia

**Comment by Aralun** [comment]
Ah thanks but I believe there's a misunderstanding. My code is perfectly fine and the result loos good:

![Screenshot of the translated Onfido widget](https://user-images.githubusercontent.com/4149052/43793857-3f3f31c8-9a6c-11e8-947b-eab3be624c46.png)

Now since I have done this work it may as well benefit others. I figured I could PR your repo to give you the translation. The only issue is that there's little point if you don't have anyone to maintain it.

**Comment by seewah** [comment]
Many thanks @Aralun for the offer. We have an internal process for managing and publishing translations, so it would not be a straight PR merge. However, if you don't mind issuing a PR, at least we can see the strings, and we can then incorporate that into our central database, and add French as a supported (and maintained) languages in upcoming releases. We will not be able to credit you with the contribution in this case though, I am afraid...

**Comment by Aralun** [comment]
tbh I don't really mind. Maybe mention that the community helped you with the French translation somewhere.

Will do the PR this afternoon.
