### ISSUE TITLE
UI creates duplicate Requests

### ISSUE THREAD

**Issue by ctrlaltdylan** [onfido/onfido-sdk-ui#399]
<img width="414" alt="screen shot 2018-08-07 at 8 59 07 am" src="https://user-images.githubusercontent.com/2694734/43784084-886e70b2-9a20-11e8-9cbb-4b6c0d2b8e41.png">

You can ignore the 422 request on the `onfido-create` endpoint. That's our `onComplete` action being fired and we have a server side check to make sure we don't create 2 checks. 

However, the UI seems to be duplicating every single request. So it's uploading the same ID document twice, the same selfie picture twice and firing the `onComplete` event twice. All during _1_ run through of the wizard.

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan, which version of the SDK are you using? The requests returning `200` should be `OPTIONS` requests, not duplicates. If the `onComplete` callback is being fired twice you might have two instances of the SDK running at the same time.

**Comment by ctrlaltdylan** [comment]
@stefaniacardenas Correct the document uploads are OPTIONS requests. And I wouldn't leave redundant instantiation that out of the realm of possibility with our current build system - I'll close this one out.
