### ISSUE TITLE
Fix integration with freegeoip.net

### ISSUE THREAD

**Issue by justinkiang** [onfido/onfido-sdk-ui#419]
Seems like you are using freegeoip.net to get the user's location to pre-populate the country code on PhoneNumberInput component.

However they have shutdown their api, causing the country code to default to GB instead.

Their API redirected to http://freegeoip.net/shutdown, looks like it is going to be a drop in replacement.  Shouldn't be too hard to resolve this issue.

**Comment by stefaniacardenas** [comment]
We have removed the request to freegeoip in this PR #371. The phone number will default to GB, until we can integrate with a new ip detection service.

**Comment by stefaniacardenas** [comment]
Hi, we have removed the integration with `freegeoip`. In the [latest release](https://github.com/onfido/onfido-sdk-ui/releases/tag/3.0.0) the default country for the SMS number input can be customised by passing the `smsNumberCountryCode` option when the SDK is initialised. We will probably use a new IP service in the near future but for now you can customise the default flag by passing the preferred parameters. I will close this issue for now but please feel free to get in touch if you have any other issue or suggestion.
