### ISSUE TITLE
Default selfie camera input to use front facing camera

### ISSUE THREAD

**Issue by justinkiang** [onfido/onfido-sdk-ui#420]
Right now it's using the Camera component where the capture attribute is not set.

iOS and android will set the preferred camera to front facing camera if that attribute is set to "user"

**Comment by stefaniacardenas** [comment]
Hi @justinkiang, we have included a fix for this issue in version [2.7.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/2.7.0) I will therefore close this issue.
