### ISSUE TITLE
Generating an SDK Token - No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by yokesh351** [onfido/onfido-sdk-ui#458]
While doing the below request for Generating an SDK Token - 
curl https://api.onfido.com/v2/sdk_token
  -H 'Authorization: Token token=YOUR_API_TOKEN'
  -F 'applicant_id=YOUR_APPLICANT_ID'
  -F 'referrer=REFERRER_PATTERN'

URL where SDK is loaded - https://lccx.io/security-setting
REFERRER_PATTERN - https://lccx.io/security-setting

Error issue seen in browser console -

Failed to load https://api.onfido.com/v2/sdk_token: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://lccx.io' is therefore not allowed access.

Issue screenshot - http://prntscr.com/ktpv61

This is preventing us to move to the next step. Kindly help. onfido account email - robert@lccx.co.uk

**Comment by stefaniacardenas** [comment]
Hi, did you manage to solve this issue?

**Comment by stefaniacardenas** [comment]
I am going to close this issue for inactivity. Feel free to get in touch if you are still facing this problem.
