### ISSUE TITLE
Video check title

### ISSUE THREAD

**Issue by tony-blockchain** [onfido/onfido-sdk-ui#463]
It currently says 'Check selfie'. I guess it should be migrated to something like 'Check video'.

**Comment by stefaniacardenas** [comment]
Hi, thanks for reporting the issue. This has been fixed in [version 2.8.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/2.8.0). The release was published yesterday.

**Comment by tony-blockchain** [comment]
Awesome, thanks Stefania! Will upgrade soon.
