### ISSUE TITLE
Add German language support

### ISSUE THREAD

**Issue by mcfilib** [onfido/onfido-sdk-ui#471]
It'd be really handy if the sdk could support `de` in addition to `es` and `en`.

**Comment by stefaniacardenas** [comment]
Hi @mcfilib, thank you so much for raising the PR. We have an internal process for managing and publishing translations, so it would not be a straight PR merge. We will review the strings and user test them and hopefully we will be able to incorporate German within the supported languages in upcoming releases. For now, you can initialise the SDK with `de` as a custom language. Again, thank you so much for your contribution. I will reply to your comments in the PR and close it for now.

**Comment by mcfilib** [comment]
@stefaniacardenas did you ever end up adding german to the sdk?

**Comment by stefaniacardenas** [comment]
Hi @mcfilib, we appreciate you took the time to submit German translations. We took note of your translation for future reference but, unfortunately, at the moment we are unable to provide a time frame for German support and maintenance. If you have specific requirement please get in touch with your account manager and they might be able to help with your request.
