### ISSUE TITLE
The file upload dialog box opens up twice in chrome

### ISSUE THREAD

**Issue by voith** [onfido/onfido-sdk-ui#478]
- onfido-sdk-version: 2.7.0 (Also, tested with 2.8.0)
- os: OSX
- chrome version: Version 69.0.3497.100
### What was wrong?
Whenever I try upload documents, the dialog box open up twice. I tested this in firefox, safari and chrome. I face this issue only in chrome.
Happens when I try to upload a file as shown in the image below:
<img width="521" alt="screen shot 2018-09-26 at 11 43 28 am" src="https://user-images.githubusercontent.com/8171193/46060591-86203600-c181-11e8-99e2-861a5d4dd127.png">

### MVE
index.html
```
<html lang="en">
    <head>
	<title>Onfido SDK Test</title>
	<link src="static/css/onfido.css">
	<script src="static/js/jquery-2.0.3.min.js"></script>
  	<script src="static/js/onfido.min.js"></script>
 	<script src="static/js/onfido_init.js"></script>
    </head>
    <body>
	<div id="onfido-mount" data-jwt="DUMMY_JWT_TOKEN"></div>
    </body>
</html>
```
`static/onfido_init.js`
```
(function ($) {
  $(document).ready(function () {
    console.log('entered here');
    Onfido.init({
      useModal: false,
      token: $("#onfido-mount").data("jwt"),
      onComplete: function (data) {
        console.log(data);
        console.log("Onfido everything is complete")
      },
      steps: [
        {
          type: 'welcome',
          options: {
            title: "You can start your verification now",
            descriptions: [
              "Please prepare id or driving license or passport",
              "Enable your camera an microphone",
            ]
          }
        },
        'document',
        {
          type: 'face',
          options: {
            requestedVariant: 'video'
          }
        },
        {
          type: 'complete',
          options: {
            message: "We'll now process your documents and video",
            submessage: "Please wait for email confirmation",
          }
        }
      ]
    });
  });

})(jQuery);
```
### Additional Notes
I found the following event listener in chrome.
<img width="889" alt="screen shot 2018-09-26 at 11 53 34 am" src="https://user-images.githubusercontent.com/8171193/46061053-de0b6c80-c182-11e8-98b2-fc5689a535ba.png">
When I remove it manually, everything works fine as expected.

PS: I'm **not** a JS developer. I'm an absolute noob at frontend related stuff. So please correct me If I have done anything wrong there.

**Comment by voith** [comment]
A css fix worked for me:
```
.onfido-sdk-ui-CustomFileInput-input
  display: none !important 
```
Not sure if the file input should appear there in the first place.
We are going to use the sdk in our soon to hit production release. A quick fix and release will be highly appreciated.

**Comment by stefaniacardenas** [comment]
Hi, thanks for reporting the issue.
There might be an `input { display: block }` somewhere in your CSS that is overriding the SDK style. In order to prevent this from happening, we will incorporate inline style for this element in the upcoming releases. 
For now, please use the CSS solution you mentioned.
