### ISSUE TITLE
Video facial recognition is receiving 422 from Onfido API

### ISSUE THREAD

**Issue by phackwer** [onfido/onfido-sdk-ui#495]
When activating video mode with 

                            {
                                type: 'face',
                                options: {
                                    requestedVariant: 'video'
                                }
                            },

At the end of the process.

Here is a sample log of the error received:

[2018-10-17 17:06:58] api-consumer.INFO: POST https://api.onfido.com/v2/applicants/***/checks?reports%5B%5D%5Bname%5D=facial_similarity&reports%5B%5D%5Bname%5D=document&type=express HTTP/1.1  ==> RESPONSE: 422 - {"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"applicant":["You must provide a live photo to be able to proceed with this check"]}}} [] []

Isn't the Javascript SDK sending the captured video to the remote API?

When using simple image capture, the error does not happens.

**Comment by stefaniacardenas** [comment]
Hi @phackwer,
You are seeing that error because when you request the video variant you should add the `variant` returned in the `onComplete` callback to the check request. As stated in the documentation https://github.com/onfido/onfido-sdk-ui#1-creating-a-check

> The facial_similarity check can be performed in two different variants: `standard` and `video`. If the SDK is initialised with the `requestedVariant` option for the face step, the check should be created by specifying the value ultimately returned by the `onComplete` callback.
The value of `variant` indicates whether a photo or video was captured and it needs to be included in the request in order to initiate the facial_similarity check.
Example of data returned by the `onComplete` callback:
`{face: {variant: 'standard' | 'video'}}`

>If a facial_similarity is requested without `variant`, it will default to `standard`.

```shell
$ curl https://api.onfido.com/v2/applicants/YOUR_APPLICANT_ID/checks \
    -H 'Authorization: Token token=YOUR_API_TOKEN' \
    -d 'type=express' \
    -d 'reports[][name]=document' \
    -d 'reports[][name]=facial_similarity' \
    -d 'reports[][variant]=VARIANT'
```

I hope this helps

**Comment by phackwer** [comment]
Didn't actually help. I'm not doing anything on the onComplete (just the console.log).

I've added a callback to my backend to get the check, which works 100% when I use video, but when I add the variant=video (I've even tried variant=VARIANT - which makes no sense, but video didn't work either) I always get 422 from the backend, saying that I need to provide a live photo to get it working.

So, if I'm using the SDK, and I set the step

{
    type: 'face',
    options: {
        requestedVariant: 'video'
    }
},

Why the backend replies 422 saying that I should provide Live Photo to get variant=video?

Here is precise log for the call and the response:

[2018-10-24 13:25:14] api-consumer.INFO: POST https://api.onfido.com/v2/applicants/[SUPPRESSED ID]/checks?reports%5B%5D%5Bname%5D=facial_similarity&reports%5B%5D%5Bname%5D=document&reports%5B%5D%5Bvariant%5D=video&type=express HTTP/1.1  ==> RESPONSE: 422 - {"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"applicant":["You must provide a live photo to be able to proceed with this check"]}}} 

BTW: I'm using Guzzle to get the check result.

**Comment by phackwer** [comment]
A quick question: 

Is Video Facial Similarity Check disabled in the sandbox?

**Comment by stefaniacardenas** [comment]
Hi @phackwer,

You should not hardcode the `variant` in the request for creating a check.
The motivation behind it is that in some cases, the SDK cannot capture a live video (ie when the camera is not working or browser does not support video recording) therefore we need to fallback to photo.
When you complete the capture flow on the SDK you have to take the data returned in the `onComplete` callback and pass it to the function that initiates the check in your server. For example:
```javascript
onComplete: function(data) {
    // this is an example of a function you should define somewhere in your app
    // that takes as an argument the data returned in the onComplete callback 
    // and passes it to the backend where it can be included 
    // in the request parameters for creating a check
    sendToBackEndToInitiateCheck(data.face.variant)
}
```

Once your backend gets that data, you can start a check by assigning the data received to the `variant` parameter in your create check request.

Assuming `VARIANT = data.face.variant`, this is all you need to do:
```CURL
$ curl https://api.onfido.com/v2/applicants/YOUR_APPLICANT_ID/checks \
    -H 'Authorization: Token token=YOUR_API_TOKEN' \
    -d 'type=express' \
    -d 'reports[][name]=document' \
    -d 'reports[][name]=facial_similarity' \
    -d 'reports[][variant]=VARIANT'
```
Please let me know if you need further information about this.

**Comment by phackwer** [comment]
Ok, now it is making a bit more sense. I believe it would be great help if you could add this piece of information at the end of the README as a Troubleshooting section for the question "Why do I get 422 from the remote API when trying to use video as the facial recognition variant?".

**Comment by stefaniacardenas** [comment]
Definitely, I will update the README with more information about creating a check when requesting the video variant. I will close this for now.

**Comment by phackwer** [comment]
Thanks. :-)Cheers.
