### ISSUE TITLE
useModal: true does not work

### ISSUE THREAD

**Issue by sokunthel** [onfido/onfido-sdk-ui#498]
Onfido throwing below error when using "useModal: true" to open in a modal/popup, here's the code http://jsfiddle.net/7oht16x0/
```
ariaAppHider.js:29 Uncaught Error: react-modal: You must set an element with 'Modal.setAppElement(el)' to make this accessible
    at i (ariaAppHider.js:29)
    at o (ariaAppHider.js:20)
    at Object.t.toggle (ariaAppHider.js:25)
    at t.renderPortal (Modal.js:84)
    at t.componentDidMount (Modal.js:59)
    at h (preact.esm.js:286)
    at m (preact.esm.js:315)
    at x (preact.esm.js:949)
    at O (index.js:31)
    at Object.M.init (index.js:82)
    at XMLHttpRequest.request.onload ((index):57)
```

**Comment by Gorbyy** [comment]
Hi @sokunthel 

If you are using React, we recommend you to have your own button to trigger the sdk modal programatically.
For example:
```
<script>
    function triggerOnfido() {
      Onfido.init({
        useModal: false,
        token: token,
        onComplete: function(data) {
          // callback for when everything is complete
          console.log("everything is complete")
        },
        steps: [
          'welcome',
          'document',
          'face',
          'complete'
        ]
      });
    };
</script>
```
while having in the body:
`<button id='onfido-button' onClick="triggerOnfido()">Verify identity</button>`
I would also like to tell you that we are about to do a release which removes support for triggering the modal.
I hope this helps!

Cheers

**Comment by sokunthel** [comment]
I'm not using React. Just plain vanilla JS. _"trigger the sdk modal programmatically"_ - are you suggesting that I need to rely on a third party library to open it in a modal? What does _useModal: true_ do exactly? Here's the link to the updated code with a button. http://jsfiddle.net/7oht16x0/4/.

**Comment by sokunthel** [comment]
useModa: true does not work still in 3.0.0. Can you guide me on how to trigger the modal please?

**Comment by stefaniacardenas** [comment]
In [version 3.0.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/3.0.0) we have removed support for `buttonId` therefore you will have to programmatically trigger the modal and close the modal on `onModalRequestClose`. For more details, check out the [migration notes](https://github.com/onfido/onfido-sdk-ui/blob/master/MIGRATION.md). For a react example (we use `preact`), check out this [demo](https://github.com/onfido/onfido-sdk-ui/blob/master/src/demo/demo.js). I will close this issue for now but feel free to follow up if you find any other issue.
