### ISSUE TITLE
Proof of address feature

### ISSUE THREAD

**Issue by ppoliani** [onfido/onfido-sdk-ui#506]
I was looking into the repository and trying to figure out how to enable the upload of proof of address through the widget. 

I noticed that there is a related branch. Is it merged to master and If so, is there any documentation explaining how we can use it.

**Comment by stefaniacardenas** [comment]
Hi @ppoliani,
the Proof of Address feature is part of a limited trial and is not currently documented. If you would like to request a trial for this feature please get in touch with our client support at client-support@onfido.com or speak to your account manager and they will be able to advise on how to move forward.

**Comment by ppoliani** [comment]
@stefaniacardenas Thank you for the quick reply. Do you know if that feature is being used in production?

**Comment by stefaniacardenas** [comment]
Hi @ppoliani, this feature is not being used in production. Your account manager or client support will be able to give you an idea regarding the timeline for this feature official release or for a possible trial. I hope this helps. I will close this issue for now but feel free to get in touch if you have any other questions.

**Comment by aktary** [comment]
This issue is five months old... has there been any movement?  I'm sending an email to client-support, but figured I'd ask here too.

**Comment by aktary** [comment]
Just for giggles, I tried it as part of a welcome > document > face > poa > complete flow and (at least at first glance in the local dev environment) it seems to work.  Is it fully functional now?

**Comment by stefaniacardenas** [comment]
The feature is now functional and can be used in production as a stand alone flow for now, not in conjunction with other capture steps such as `face` and `document`. Therefore I would suggest using it as such `['welcome', 'poa', 'complete']`
