### ISSUE TITLE
Importing sdk in polymer app not working

### ISSUE THREAD

**Issue by amitrathik** [onfido/onfido-sdk-ui#508]
When I try to import Onfido using the ES6 import syntax, i get the following error:

Uncaught (in promise) SyntaxError: The requested module '../../node_modules/onfido-sdk-ui/lib/index.js' does not provide an export named 'default'

**Comment by rfreitas** [comment]
Hi @amitrathik ,

What sdk version are you using?
Also, which bundler are you using, webpack?

Is this reference project https://github.com/onfido/onfido-sdk-web-sample-app helpful?

**Comment by amitrathik** [comment]
> Hi @amitrathik ,
> 
> What sdk version are you using?
> Also, which bundler are you using, webpack?
> 
> Is this reference project https://github.com/onfido/onfido-sdk-web-sample-app helpful?

 "onfido-sdk-ui": "^2.8.0"

because we are using polymer JS, we are not using webpack or any bundler. polymer has it's own internal bundler.

**Comment by rfreitas** [comment]
I see. Unfortunately we don't support polymer. Have you tried the standalone js file instead? I understand it might not be ideal, but it can unblock you for now at least.

**Comment by amitrathik** [comment]
> I see. Unfortunately we don't support polymer. Have you tried the standalone js file instead? I understand it might not be ideal, but it can unblock you for now at least.

Are you referring to just using the dist/onfido.min.js file?

**Comment by rfreitas** [comment]
yes

**Comment by stefaniacardenas** [comment]
Hi, did you manage to solve this issue by importing the JS file directly? I will close for inactivity but please feel free to reopen if the problem still exists.
