### ISSUE TITLE
Web SDK - data format for creating an applicant

### ISSUE THREAD

**Issue by bkawk** [onfido/onfido-sdk-ui#514]
I am following the web SDK path here https://github.com/onfido/onfido-sdk-ui

I can see the first step is to create an applicant, the below code works from the command line, substituting my auth token for my test token

```
$ curl https://api.onfido.com/v2/applicants \
    -H 'Authorization: Token token=YOUR_API_TOKEN' \
    -d 'first_name=John' \
    -d 'last_name=Smith'
```

When I convert this to node

```
var url = 'https://api.onfido.com/v2/applicants';
var method = 'POST';
var headers = {'Authorization': 'Token token=<YOUR TOKEN IN HERE>'};    
var body = {first_name:"Will",last_name:"Hill"};

function callback(error, response, body) {
    console.log(body);
    console.log(response);
    console.log(error);
}
request({url, method, headers, body}, callback)
```

And submit the code I get this error which seems self explanatory 

```
{"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"first_name":["can't be blank"],"last_name":["can't be blank","is too short (minimum is 2 characters)"]}}}
```

so I then tried to format the body in different ways, as a string
```
var dataString = 'first_name=John&last_name=Smith';
```
Or as an object
```
var dataString = {"first_name":"John","last_name":"Smith"};
```
Or as an array of objects
```
var dataString = [{'first_name':'John'},{'last_name':'Smith'}];
```
or an array of strings
```
var dataString = ['first_name=John','last_name=Smith'];
```
I have also tried by way of converting each of these formats to a string and a buffer with no luck! 

If I use an HTTP GET request I can see all the applicants we have made from the command line, but not the one I am submitting.

Also note that error never contains an error and the error is shown in the body.

https://github.com/bkawk/onfido-node/blob/master/index.js#L12-L17

**Comment by bkawk** [comment]
I found your example code here https://github.com/onfido/onfido-sdk-web-sample-app/blob/master/app/server.js#L13-L18

```
    function callback(error, response, body) {
            console.log(body);
            console.log(response);
            console.log(error);
    }

    unirest
    .post('https://api.onfido.com/v2/applicants')
    .headers({'Authorization': 'Token token=test_cYzbqYVlmYixWQN0V6CYD3AOlIYdeZk9'})
    .send({first_name:"James",last_name:"Grinder"})
    .end(callback)
}

```
Which should essentially be the same as my last ettempt using request, but this time `error` and `response` are empty and `error` in `raw_body` conatains what looks like an applicant object??
```
{"id":"a4bf8a18-7e9e-4381-90f5-0be9989ac34a","created_at":"2018-11-07T03:34:11Z","sandbox":true,"title":null,"first_name":"James","middle_name":null,"last_name":"Grinder","email":null,"gender":null,"dob":null,"telephone":null,"mobile":null,"nationality":null,"country":"gbr","delete_at":null,"href":"/v2/applicants/a4bf8a18-7e9e-4381-90f5-0be9989ac34a","mothers_maiden_name":null,"country_of_birth":null,"town_of_birth":null,"previous_last_name":null,"id_numbers":[],"addresses":[]}' }
```

**Comment by stefaniacardenas** [comment]
Hi @bkawk, did the answer solved the issue?

**Comment by stefaniacardenas** [comment]
Hi @bkawk, I hope that the previous reply answered your question. I will close this issue for now.
