### ISSUE TITLE
Getting document ids in "onComplete" callback

### ISSUE THREAD

**Issue by alonp99** [onfido/onfido-sdk-ui#517]
Hi Guys,

Getting the document ids after onComplete callback can be useful both to initiate a check for those doc ids and making an OCR request to fill following KYC forms.
Do you plan to add this functionality in the near future?

**Comment by ramprasad-parajuli** [comment]
Hi @alonp99 
Thank you for your suggestion. We are currently in the process of gathering feedback and suggestions from our customers, and we are trying to work on them based on the demand to include it in our future releases.
I would like to let you know that this is something we have received from several customers and it is in the roadmap. We will be implementing it soon and will go live in the next few releases, unfortunately, I cannot provide you with an exact timeline at this moment. I will reach out to you once I have a date, but, most probably, it will be implemented in Q1 or Q2 of 2019.
I hope this helps.

**Comment by stefaniacardenas** [comment]
Hi @alonp99, 
Thank you so much for submitting PR #519. I am pleased to inform you that the feature went live on [v4.0.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/4.0.0).
I will close this issue but please feel free to keep giving us feedbacks to improve our SDK.
