### ISSUE TITLE
Phone: set default country

### ISSUE THREAD

**Issue by phackwer** [onfido/onfido-sdk-ui#528]
Is there anyway to define the default country when user chooses to use mobile to take pic? I wanted to have Ireland as default instead of GB.

**Comment by phackwer** [comment]
Ok, could you update README or manual page?

**Comment by stefaniacardenas** [comment]
Hi, we update the README with public changes before each release. This specific feature has been documented in [this section](https://github.com/onfido/onfido-sdk-ui/#customising-sdk) of the README, on the bullet point `smsNumberCountryCode`.

**Comment by stefaniacardenas** [comment]
I will close this ticket as solved.
