### ISSUE TITLE
Slow performance when using live tokens

### ISSUE THREAD

**Issue by phackwer** [onfido/onfido-sdk-ui#530]
Hi,

We have implemented onfido in our solution and noted that when we switched to the Live token the performance became really slow. When we switch back to sandbox, uploading the images (document and selfie) is much faster. Is there anything we can do to make it faster? Why would it be slower in production? Are there any realtime processing going on when uploading the images? 

Somehow it feels like the processing should only be done after the create check is sent and also in the background, but the slow performance every time (almost like if the upload takes longer for live token).

Thank you.

**Comment by ramprasad-parajuli** [comment]
@phackwer Thank you for reaching out. The reason you are seeing time difference in processing of uploads and selfie is that, for sandbox token, Onfido does not look into the uploads for Glare detection or any other tasks that Onfido carries out on the document and the selfie being uploaded.
For live tokens though, Onfido makes sure that the Document uploaded do not have any problems or issues with them for smoother customer experience once the Check is created. I know it becomes somewhat irritating to observe some time difference, but that is for the best results Onfido could provide to our customers. I apologize for the long post here, but I hope this helps.
