### ISSUE TITLE
"Camera access rejected" screen on Chrome, without prompt, with camera allowed

### ISSUE THREAD

**Issue by tony-blockchain** [onfido/onfido-sdk-ui#537]
When using Chrome camera access denied screen appears instantly although camera being explicitly allowed

![screenshot 2018-12-21 at 16 30 31](https://user-images.githubusercontent.com/40363889/50352823-4da0b600-053e-11e9-9bbf-c91c0b5221da.png)

Chrome Version 71.0.3578.98

Some errors in the console

`error DOMException object` in the minified file near the `console.log("error",e,void 0===e?"undefined":(0,o.default)(e))}(`

```
index.js:46 Refused to load the script 'http://www.woopra.com/track/ce/?ra=NRRWBuZZDuCe&alias=onfido-js-sdk.com&instance=onfidojssdkwoopra&ka=24000&meta=&screen=1920x1080&language=en-GB&app=js-client&referer=http%3A%2F%2Flocalhost%3A8080%2Fen%2F&idle=0&vs=r&cookie=frx2qLVqzvSd&event=screen_face_video_capture&cv_sdk_version=3.1.0-rc.3&cv_client=localhost&ce_requestedVariant=video&ce_uploadFallback=false' because it violates the following Content Security Policy directive: "script-src 'self' https://www.woopra.com/track/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by seewah** [comment]
Can you confirm which version of the JS SDK you are using? Thanks!

**Comment by tony-blockchain** [comment]
Encountered on both of

3.1.0-rc.3
3.1.0-rc.1

**Comment by tony-blockchain** [comment]
Just tried 3.0.1 with same results

**Comment by morganjbruce** [comment]
@tony-blockchain my suspicion is that the woopra issue is a red herring that occurs in local development, as your CSPs might be blocking requests from localhost:8080 (per the referrer in the blocked woopra URL) to woopra.com

Could you please confirm:

1. Is this happening in local development, production, or both?
2. Which version of the SDK are you currently using in production?
3. Which operating system are you (or affected users) using?  macOS Mojave?

**Comment by tony-blockchain** [comment]
Fixed on our side

1. Microphone was required, didn’t know that
2. Looks like Chrome started to enforce microphone to be explicitly allowed on iframe recently
3. Updating it helped

**Comment by morganjbruce** [comment]
Thanks Tony, that's great to hear; I'll close this issue now.

**Comment by summerela** [comment]
I'm having this issue.

**Comment by warrenseine** [comment]
Hey @summerela, you are commenting on an issue from 2018. A lot of things have changed in the meantime, so please open a new issue with all the details requested in the issue template. Thanks!
