### ISSUE TITLE
Some life cycle methods do not get called at Camera and Capture, such as `componentWillUnmount `

### ISSUE THREAD

**Issue by rfreitas** [onfido/onfido-sdk-ui#54]
1. Go to document capture step
2. Put a document in front of the camera
3. Wait for the confirmation screen to appear
4. If the problem is not visible, press Take again and go to step 1.

Problem:
2. The `screenshot` function of the `Camera` component keeps getting called and it's because the `componentWillUnmount` does not get fired.

**Comment by rfreitas** [comment]
The issue is more general now. Components are not getting their lifecycle methods called, methods such as `componentDidMount` or `componentWillUnmount`.

**Comment by rfreitas** [comment]
This bug has been scoped to the component `Camera` and `Capture`. A fix should solve the issue for these components. A more general bug will be created.

**Comment by hjheath** [comment]
Fixed in https://github.com/onfido/onfido-sdk-ui/pull/71 and https://github.com/onfido/onfido-sdk-ui/pull/181
