### ISSUE TITLE
What is the EXACT customisation needs to be added in the document step?

### ISSUE THREAD

**Issue by aniruddhashevle** [onfido/onfido-sdk-ui#541]
Below doesn't seem to be worked! It provides all the documents even if the flag set to false!

```
steps: [
            'welcome',
            {
                type: 'document',
                options: {
                    passport: true,
                    driving_license: false,
                    national_identity_card: true
                }
            },
            'face'
        ];
```

**Comment by yoginair** [comment]
This is worked! Please trying this one!  :-)
{
    type: 'document',
    options: {documentTypes:{
                    passport: false,
                    driving_licence: true,
                    national_identity_card: true
                }}
  },

**Comment by aniruddhashevle** [comment]
Solved in #542

**Comment by stefaniacardenas** [comment]
Glad you found the solution. I will close this ticket for now.

**Comment by stefaniacardenas** [comment]
And thanks for raising the PR, we will review it as soon as possible.
