### ISSUE TITLE
How to pre-filled the mobile number field and disable the mobile number field?

### ISSUE THREAD

**Issue by aniruddhashevle** [onfido/onfido-sdk-ui#543]
Is there any way to provide mobile no in the `Onfido.init()` configuration?
If the mobile number is provided with the country code in the init() function, we can either make the mobile no field pre-filled and disabled OR skip that field!

**Comment by stefaniacardenas** [comment]
Hi, this is currently on our roadmap and we will hopefully include this feature in one of the upcoming releases.

**Comment by Avi98** [comment]
Hi, is this issue resolved? I couldn't get the solution for this when I implemented like bellow
`options: {
            forceCrossDevice: true,
            smsNumberCountryCode: "UN",
            userDetails: { number: 447500123456 }
}`

user numbers were no pre-populated and is there a way to make mobile number non-editable?

**Comment by stefaniacardenas** [comment]
- The `smsNumberCountryCode` expects a valid ISO country code. In your configuration you have "UN" which is not a valid alpha-2 code. Please refer to https://www.iso.org/obp/ui/#search/code/ 
- The right format for the number expects the plus in front of the number as in the following example `{ userDetails: { number: +447500123456 } }`
Currently, there is no way of making the number non editable as that would probably increase the user drop-off. If that is your use case you could target the input class and disable it yourself if a valid number is present or you could get in touch with your Onfido account manager and discuss your use case to propose a change. I hope that helps

**Comment by Avi98** [comment]
Thanks
