### ISSUE TITLE
Error when using in Firefox private mode

### ISSUE THREAD

**Issue by DxTa** [onfido/onfido-sdk-ui#562]
"Connection lost" when using Firefox private mode or Brave

## Expected Behavior
When click uploading documents, I would expect the documents are uploaded and **onComplete** callback function is executed.

## Current Behavior
However, in Firefox private mode and Brave (might be other browsers as well), I got "Connection lost" error. Checking network tab, I got **bad referrer** error response from onfido because Firefox private mode has different referrer policy compared to Chrome. 

See image below, default value of referrer policy in private mode is **2** meaning **strict-origin-when-cross-origin** (only send the origin when the protocol security level stays the same (HTTPS→HTTPS), and send no header to a less secure destination (HTTPS→HTTP) - more info at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy). Hence, the referrer used to generate jwt token is different from the referrer used to make POST request to **/v2/documents**

![image](https://user-images.githubusercontent.com/1542811/51844013-ea642980-231c-11e9-92f7-b2dd9e8eec92.png)

My current temporary solution for it is using wildcard pattern when generating jwt token. E.g: https://example.com/*

## Steps to Reproduce
1. Using firefox private mode
2. Going through onfido steps to upload document
3. Got "connection error"

## Context (Environment)
- OS: Macbook
- Browser: Firefox v64.0.2 (private mode)

**Comment by rfreitas** [comment]
Hi @DxTa ,

Thanks for raising this issue.

What would be your expected behaviour from a referer point of view?
By reading the documentation (thanks for that) it the seems only way is to set up a referer pattern like you suggested, that includes the origin only.

**Comment by DxTa** [comment]
@rfreitas, thanks for the fast reply.

I think if `referer` has been using as part of the process, then the current way is setting wildcard referer pattern as my example and your conclusion. But I think, it would be nice to add the issue/answer to documentation to support other developers as well where there are questions for similar cases such as:
- some specific browsers
- some plugins/extensions that stripping the referrer
- there is "no-referrer" meta tag in the head of website
- some security feature enabled might conflict

The better solution, I would think of is making `referrer` optional or replaced with domain origin in some case

**Comment by stefaniacardenas** [comment]
Thank you for your feedback @DxTa. Our [documentation for JWT generation](https://documentation.onfido.com/#generate-web-sdk-token) has been updated and it now includes some additional information on referrer policy and patterns.
I will close this issue for now but please feel free send us any suggestion or improvement request.
