### ISSUE TITLE
Implement typings

### ISSUE THREAD

**Issue by JoeStead** [onfido/onfido-sdk-ui#567]
When trying to use the SDK in a typescript project, there are no typings which makes the task quite difficult.

**Comment by aktary** [comment]
I needed this too, so I wrote one.  Here it is... but I warn you that this is off-the-cuff and is by no means production-ready:

`declare module 'onfido-sdk-ui' {
  interface IOnfidoResponse {
    document_front: {
      id: string;
      type: string;
      side: string;
    };
    face: {
      id: string;
      variant: string;
    };
  }
  interface IOnfidoConfig {
    token: string;
    containerId: string;
    onComplete?: (data: IOnfidoResponse) => null;
    onModalRequestClose?: () => null;
    isModalOpen?: boolean;
    useModal?: boolean;

    steps?: [
      string | {
        type: string;
        options: {
          title?: string;
          descriptions?: [string];
          nextButton?: string;
          country?: string;
          documentTypes?: {
            passport?: boolean;
            driving_licence?: boolean;
            national_identity_card?: boolean;
            bank_building_society_statement?: boolean;
            utility_bill?: boolean;
            council_tax?: boolean; // GBR only
            benefit_letters?: boolean; // GBR only
            government_letter?: boolean; // non-GBR only
          };
          forceCrossDevice?: boolean;
          requestedVariant?: 'standard' | 'video';
          uploadFallback?: false
          message: string;
          submessage: string;
        }
      }]
  }

  interface IOnfidoHandle {
    tearDown(): null;
    setOptions(opts: IOnfidoConfig): null;
  }
  export function init(e: any): IOnfidoHandle;
}`

feel free to modify/update

**Comment by NickRivers3** [comment]
@aktary - How did you init Onfido within Typscript file? I keep getting `Object(...) is not a function`.

**Comment by aktary** [comment]
I created a type definition file.  Can't guarantee this is still valid with the latest version of onfido-sdk-ui, but here it is:

```typescript
declare module 'onfido-sdk-ui' {
  interface IOnfidoResponse {
    document_front: {
      id: string;
      type: string;
      side: string;
    };
    face: {
      id: string;
      variant: string;
    };
  }
  interface IOnfidoConfig {
    token: string;
    containerId: string;
    onComplete?: (data: IOnfidoResponse) => null;
    onModalRequestClose?: () => null;
    isModalOpen?: boolean;
    useModal?: boolean;

    steps?: [
      string | {
        type: string;
        options: {
          title?: string;
          descriptions?: [string];
          nextButton?: string;
          country?: string;
          documentTypes?: {
            passport?: boolean;
            driving_licence?: boolean;
            national_identity_card?: boolean;
            bank_building_society_statement?: boolean;
            utility_bill?: boolean;
            council_tax?: boolean; // GBR only
            benefit_letters?: boolean; // GBR only
            government_letter?: boolean; // non-GBR only
          };
          forceCrossDevice?: boolean;
          requestedVariant?: 'standard' | 'video';
          uploadFallback?: false
          message: string;
          submessage: string;
        }
      }]
  }

  interface IOnfidoHandle {
    tearDown(): null;
    setOptions(opts: IOnfidoConfig): null;
  }
  export function init(e: any): IOnfidoHandle;
}
```

**Comment by NickRivers3** [comment]
Thanks @aktary, I was able to add these typings, but we still have the same error:

`object()... is not a function error`
We've tried various imports, but with no luck. 

```
import * as Onfido from 'onfido-sdk-ui'; // object()... is not a function error
import {init} from 'onfido-sdk-ui'; // same error as above
import Onfido from 'onfido-sdk-ui'; // same error as above
```

**Comment by stefaniacardenas** [comment]
Hi all, FYI we will implement typings this quarter. @NickRivers3 are you using a framework like Next.js or any other framework that executes code server-side first? If so, you might have to import the SDK asynchronously, like in the example below:

```
let Onfido;
async componentDidMount() {
      Onfido = await import('onfido-sdk-ui')
}
Onfido.init()

Let me know if that helps.

**Comment by LiamDotPro** [comment]
I've submitted a pull request to add SDK UI typings to `DefintelyTyped` here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48176 Once accepted you'll be able to use `@types/onfido-sdk-ui` in the meantime before they add official typings. @stefaniacardenas  If you can ping me on this thread when the official typing's are released and I'll submit the request for the DefintelyTyped typings to be removed.

**Comment by stefaniacardenas** [comment]
Will do, thanks @LiamDotPro 👍
