### ISSUE TITLE
`smsNumberCountryCode` option not applying

### ISSUE THREAD

**Issue by ctrlaltdylan** [onfido/onfido-sdk-ui#574]
Passing the `smsNumberCountryCode` doesn't seem to change the default country for the SDK:

```
Onfido.init({
   ...
   smsNumberCountryCode: 'US',
   ...
})
```

Still defaults to GB as the country when prompted to enter an in phone # for an SMS link.

Running v3.1.0 of `onfido-sdk-ui`

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan,
I cannot reproduce the issue, I'm passing `smsNumberCountryCode: 'US'` to the initialization parameters in this [JSFiddle](https://jsfiddle.net/zhb54nf9/) and I can see the country flag changing to US. 
Can you provide me with more details about your implementation?

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan, 
Did you manage to get it working in the end?

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan,
I will close this issue for inactivity. Feel free to reopen if the problem still exists.

**Comment by ctrlaltdylan** [comment]
I figured out the issue, at least on our setup (running onfido-ui-sdk v5). You need to use `language.locale` to `'us'` and then the properly displays the US area code preset.
