### ISSUE TITLE
Browser Back button is not clearing `fullScreen` css classes

### ISSUE THREAD

**Issue by wakooka** [onfido/onfido-sdk-ui#578]
## Expected Behavior
`FullScreen` classes should be removed when doing a browser back from the full screen modal step.

## Current Behavior
Full screen CSS classes don't get removed when exiting the modal, which results in a white text color in the header (back arrow & title), which is almost impossible to read.

## Steps to Reproduce
1. Upload a document
2. Click "enlarge image"
3. Click browser back button
4. The text and back arrow are white in the header, and will remain like this throughout the flow.
![onfido-back](https://user-images.githubusercontent.com/1606624/52482818-937b1180-2bb2-11e9-9b6c-b53e017b912f.gif)

Version used: `3.1.0`

Let me know if you need clarifications,
Thanks

**Comment by stefaniacardenas** [comment]
Hi @wakooka,
Thanks for reporting the issue. It was already in our backlog but we will prioritise it and let you know when it's fixed. Many thanks

**Comment by kopijunkie** [comment]
Hi @wakooka 

FYI release 5.1.0 has gone out with the fix for the bug you reported. 

Please let us know if you are still seeing this issue.
