### ISSUE TITLE
submit check problem.

### ISSUE THREAD

**Issue by sepehrhz** [onfido/onfido-sdk-ui#583]
In last step of checking process, after taking a photo, all process restarts and gives 404 error for onfido.min.js and doesn't submit the check.

**Comment by stefaniacardenas** [comment]
Hi @sepehrhz, how are you submitting the check? The SDK is not responsible for requesting the check, it just returns a callback at the end of the flow so you can ping your backend and initiate the check from the server. Could you give me more details about the issue you are seeing?

**Comment by sepehrhz** [comment]
Thanks for your reply, The check process seems like it completes but now I have another problem that is woopra. After I took picture and try to upload it, check process restarts before submitting the form and starts from the first step and in my browser inspector I see the woopra request is failed.

**Comment by stefaniacardenas** [comment]
Hi @sepehrhz, 
Are you still experiencing this issue? If so could you give me more details about how to reproduce it?

**Comment by sepehrhz** [comment]
Hi,Thanks for your reply. I don't work on that project anymore...
