### ISSUE TITLE
Add more details on when the video variant will be rejected

### ISSUE THREAD

**Issue by JoeStead** [onfido/onfido-sdk-ui#585]
When trying to use the video variant for facial similarity checks, the documentation states that it can fall back to the standard variant if the SDK is unable to record video:

>  If the `requestedVariant` is video, we will try to fulfil this request depending on camera availability and device/browser support. In case a video cannot be taken the face step will fallback to the `standard` option.

We have a user who is using the SMS option to complete the option on their iPhone X, but is always presented with the standard variant.

Given the iPhone X is a modern phone, we would expect the video to be captured, however as the exact details of when the fallback is used has not been documented, we have no way of diagnosing why this is happening.

**Comment by stefaniacardenas** [comment]
Hi @JoeStead,
Thanks for reporting this. Unfortunately, Safari does not support video recording functionalities yet, therefore on Safari we will always fallback to the standard variant. I will make more details about the fallback get included in the documentation in the next releases. Many thanks!

**Comment by zoeradkani** [comment]
going to close this issue as it seems like there is backlog ticket for it.
