### ISSUE TITLE
Enable theme customization

### ISSUE THREAD

**Issue by afkatja** [onfido/onfido-sdk-ui#616]
It would be nice if the `theme` was exposed, just as the `init` is. 

Right it seems I have to do the hacky copy-pasting classnames from the generated UI, like all classnames prefixed with `.onfido-sdk-ui-Theme`. Overriding the constants would do the trick I guess.

If there is a (better) way of customizing the styling of the UI, please update the docs and point me in that direction! Thanks in advance!

**Comment by stefaniacardenas** [comment]
Hi, at the moment there is no better way of overriding the style of the UI but we will probably deliver a solution for partially overriding styles during Q3. I hope that helps!
