### ISSUE TITLE
Skip the step to choose the document type

### ISSUE THREAD

**Issue by afkatja** [onfido/onfido-sdk-ui#617]
In our implementation we only want to have a check for one type of document, driving license, so we would like to have an option to be able to skip the step where the user needs to choose what kind of document they have to verify. 
![image](https://user-images.githubusercontent.com/708310/55791516-f3ad0780-5abe-11e9-9c49-2a16d9ddbfb9.png)
How can we bypass this step and start with the next screen instead?

**Comment by stefaniacardenas** [comment]
Hi, in version 5.0.0 you can skip the document selection if the list of document types only includes one document. For example, in this case your step list would look like this:
```
Onfido.init(
    { steps: [
       'welcome',
       { type: 'document',
          options: {
            documentTypes: {
               driving_licence: true
             }
           }
        },
        'face',
        'complete'
    ]}
)
```
This feature currently only works on flows with one document step and one face step.

**Comment by Avi98** [comment]
Hi, @stefaniacardenas is it possible to skip user details step. What I mean is it  possible to do something like this

`smsNumberCountryCode: "IN",
      userDetails: {
       skipAndSendLink: true
        smsNumber: '7678602399'
      },`

Is possible to send this link directly to user number without showing them that screen

**Comment by stefaniacardenas** [comment]
Hi @Avi98,
No, at the moment you cannot skip that. Do you want to force your user to always use their mobile phones?

**Comment by Avi98** [comment]
yes, is it possible?

**Comment by stefaniacardenas** [comment]
You could use the `forceCrossDevice` option for the document step to force the user to use their mobile phone (see example below). The user will still be able to modify their number and will have to click on the `Send link` button.
```
Onfido.init(
    { steps: [
       'welcome',
       { type: 'document',
          options: {
            forceCrossDevice: true
           }
        },
        'face',
        'complete'
    ]}
)
