### ISSUE TITLE
Token Factory

### ISSUE THREAD

**Issue by JohnnyDreamguns** [onfido/onfido-sdk-ui#619]
I’ve been developing an application using the following token factory URL to generate a sandbox token and applicant:
https://token-factory.onfido.com/sdk_token

This has been working great but suddenly it’s slow and sometimes responds with ‘something went wrong’

**Comment by JohnnyDreamguns** [comment]
Seems to suddenly be working fine, must have just been having a temporary issue

**Comment by stefaniacardenas** [comment]
Hi, you should not use tokens from https://token-factory.onfido.com/sdk_token. That's not a production endpoint and you won't be able to retrieve the data submitted or to initiate a checks for your applicants if you use that token for the SDK flow. To generate a token please follow the details in the ["Generate Web Sdk Token" section](https://documentation.onfido.com/#generate-web-sdk-token) of the Onfido documentation.
