### ISSUE TITLE
Onfido breaks when run in production mode

### ISSUE THREAD

**Issue by mattKjer** [onfido/onfido-sdk-ui#624]
Hi!

We're encountering a rather tough issue that seems to be related to webpack and Onfido.

When running Onfido in development mode, everything works just fine. When we run Onfido in production the library does not seem to be imported properly and we get a `TypeError: k.init is not a function`.

We were initially having issues with 'window not defined' error, which we solved by lazy loading the component in a ComponentDidMount function.

```
var Onfido = {};

async componentDidMount() {
    const { onfidoTokenURL, handleError } = this.props;
    // lazy loads the onfido library so that window is defined
    try {
        Onfido = await require("onfido-sdk-ui");
    if (onfidoTokenURL) {
      try {
        const onfidoToken = await apiGet(this.props.onfidoTokenURL);
        this.setState({ onfidoToken }, () => this.startOnfido());
      } catch (err) {
        handleError(err);
      }
    }
  } catch(err) {
    console.log('import error', err)
    }
 }
```

I logged out the result of the require statement in both development and production modes and these were the results.

```
Failing Onfido (Production) -  ƒ (e,t,n){var l=t&&n||0,u=t||[],d=(e=e||{}).node||r,f=void 0!==e.clockseq?e.clockseq:o;if(null==d||null==f){var h=i();null==d&&(d=r=[1|h[0],h[1],h[2],h[3],h[4],h[5]]),null==f&&(...

Working Onfido (Development) resulting in k.init is not a function - Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}
init: (...)
Symbol(Symbol.toStringTag): "Module"
__esModule: true
get init: ƒ ()
__proto__: Object 
```

Any help with this would be greatly appreciate, if I need to submit any more info or details about the webpack config, happy to provide. 

Thanks!

**Comment by stefaniacardenas** [comment]
Hi @mattKjer, which version of the SDK are you using?

**Comment by mattKjer** [comment]
Currently on 5.0.0

**Comment by rfreitas** [comment]
hey @mattKjer development and production builds don't really use different bundles of the `onfido-sdk-ui`, which suggests that your webpack configuration might have different behaviours depending on whether it's prod or not. Have you looked into your minifier, seeing if that is the cause of the issue?

**Comment by liorJuice** [comment]
I also ran into this problem when importing with `await import('onfido-sdk-ui')` and i can confirm it's the onfido-sdk-ui package build type that causes it. i tried to debug the problem but wasn't able to find src maps. to be able to debug it i cloned this repo, run the build:dev script and put the output lib and dist folders in my node_modules. to my surprise the error disappeared! please check this lead. the repro is very easy. just call `init` on `const {init} = await import('onfido-sdk-ui')` on a project that gets onfido-sdk-ui from npm.

**Comment by isitrita** [comment]
@rfreitas any update on fixes of production build of onfido?

**Comment by mattKjer** [comment]
For other users experiencing this issue and to provide some context for our fix -  we made a reusable component to be hosted in our private nexus repo so all of the onfido-sdk-ui was being built and published with the component. As it was our prod webpack build that was failing, we just included the library in a script tag with - https://www.npmjs.com/package/react-load-script .

This allowed us to bypass webpack building the onfido-sdk-ui, it just meant that we had to implement a loading state while the library was being pulled in. It works for now but would be nice to be able to import the sdk and bundle with the component to reduce loading times.

**Comment by rfreitas** [comment]
Hi,

We'll be investigating this, thanks for all the reports!
Hopefully next week we have a fix on it.

Sorry for the troubles!

**Comment by rfreitas** [comment]
I was not able to reproduce the issue.
My example is here: https://github.com/onfido/onfido-sdk-web-sample-app/pull/20

It's worth considering it this is related to this webpack issue: https://github.com/webpack/webpack/issues/8656
Since I had to lock the version to get the lazy import to work.

**Comment by kopijunkie** [comment]
Closing this ticket as it's been inactive.
