### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by Avi98** [onfido/onfido-sdk-ui#626]
Is there a way for error handling. I can't find it in the documentation on how to handle server errors.

**Comment by stefaniacardenas** [comment]
Hi, are you referring to the errors returned by the Onfido API? If so, please check out [this section](https://documentation.onfido.com/#errors) of the Onfido documentation.

**Comment by Avi98** [comment]
@stefaniacardenas I need error handling on SDK side, not from API.

**Comment by Avi98** [comment]
@stefaniacardenas  is there a callback function that provides error like this

`Onfido.init({
  // the JWT token that you generated earlier on
  token: 'YOUR_JWT_TOKEN',
  // id of the element you want to mount the component on
  containerId: 'onfido-mount',
 **onBlock: function (error){} **
  onComplete: function(data) {
    console.log("everything is complete")
    // `data` will be an object that looks something like this:
    // ```
    // {
    //   "document_front": {
    //     "id": "5c7b8461-0e31-4161-9b21-34b1d35dde61",
    //     "type": "passport",
    //     "side": "front"
    //   },
    //   "face": {
    //     "id": "0af77131-fd71-4221-a7c1-781f22aacd01",
    //     "variant": "standard"
    //   }
    // }
    // ```
    //
    // You can now trigger your backend to start a new check
    // `data.face.variant` will return the variant used for the face step
    // this can be used to perform a facial similarity check on the applicant
  }
})`

**Comment by stefaniacardenas** [comment]
There isn't at the moment but I can talk to the rest of the team and evaluate introducing it. I appreciate the suggestion. What type of use case are you trying to solve?

**Comment by Avi98** [comment]
I was looking for handling errors like SMS sending failure of the server can't be reached etc.

**Comment by stefaniacardenas** [comment]
Hi @Avi98, we are discussing adding the error callback and it would be good to understand how you would handle the SMS failure if we were to return the error to you.

**Comment by cakasuma** [comment]
Hi @stefaniacardenas , I also having the same issue, for example, if we uses invalid token to initialize onfido, we are unable to upload document and gives `connection lost, please try again later` with redo button. I want to override the message for the `connection lost` message, is there any way i can do that?

**Comment by stefaniacardenas** [comment]
Hi, the `onError` callback has been added in version [5.4.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.4.0). Please refer to [this part](https://github.com/onfido/onfido-sdk-ui/#handling-callbacks) of the documentation. I will now close this issue.
