### ISSUE TITLE
problem upload document ( useing live token )

### ISSUE THREAD

**Issue by myosryrc** [onfido/onfido-sdk-ui#630]
Hi,i have problem when i used live token when I choose upload passport give me this error :
connection lost : Document capture didin't work . please try again. 

hint :  when i used test token it worked with out any issues

**Comment by stefaniacardenas** [comment]
Hi, 
The token you should pass is a JSON Web Token as detailed in this section of the {Onfido documentation](https://documentation.onfido.com/#generate-web-sdk-token). Are you having this problem when passing a JWT created with a live token? What type of error do you see in your Chrome console?

**Comment by afkatja** [comment]
Hi @stefaniacardenas 
Having a similar issue with trying to upload a driving license
![image](https://user-images.githubusercontent.com/708310/57016598-2a3bf500-6c1b-11e9-8cd8-303714c9ee23.png)
Error in console: `POST https://api.onfido.com/v2/documents 401`
What I can see is that the request is being sent with `Authorization: Bearer undefined` in the headers.
(I'm trying to simulate a repetitive check request btw, but the token etc should be valid.)

**Comment by stefaniacardenas** [comment]
Hi @afkatja, `Authorization: Bearer undefined` means that the Json Web Token is not correctly passed to the SDK. When the Json Web Token is passed correctly after the bearer you should see a long string which is your token. I hope that helps

**Comment by afkatja** [comment]
@stefaniacardenas I would prefer Onfido to throw an error _before_ initializing in case the token is invalid; is there a way to validate it before trying to upload a document (like a separate endpoint)?

**Comment by stefaniacardenas** [comment]
Hi, the `onError` callback has been added in version [5.4.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.4.0). Please refer to [this part](https://github.com/onfido/onfido-sdk-ui/#handling-callbacks) of the documentation. I will now close this issue.
