### ISSUE TITLE
[security] 153 known vulnerabilities

### ISSUE THREAD

**Issue by davityavryan** [onfido/onfido-sdk-ui#646]
Hi, first off let me start by saying thank you for creating this module and the hard work you've clearly put towards it over the years.

I have found that this package have 153 known vulnerabilities (11 unique) just by running `npm install` which runs `npm audit`. So the summary is
```
found 153 vulnerabilities (125 low, 8 moderate, 20 high) in 50683 scanned packages
  run `npm audit fix` to fix 13 of them.
  139 vulnerabilities require semver-major dependency updates.
  1 vulnerability requires manual review. See the full report for details.
```

IMO, for identity verification package it is very bad to have 20 high risk vulnerabilities.

## After running `npm audit fix` (without force)
```
added 1921 packages from 951 contributors in 60.674s
fixed 13 of 153 vulnerabilities in 50683 scanned packages
  1 vulnerability required manual review and could not be updated
  3 package updates for 139 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```
### `npm audit`
```
found 128 vulnerabilities (124 low, 1 moderate, 3 high) in 50671 scanned packages
  127 vulnerabilities require semver-major dependency updates.
  1 vulnerability requires manual review. See the full report for details.
```
### **Simple check shows that `npm run dev` and `npm run test` still works fine**

and the only `package.json` change was `surge@^0.20.1 --> ^0.20.4`

<details><summary>npm outdated</summary>

<pre>
Package                                              Current          Wanted  Latest  Location
@babel/cli                                             7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/core                                            7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-class-properties                7.1.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-decorators                      7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-export-default-from             7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-export-namespace-from           7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-function-sent                   7.1.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-json-strings                    7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-numeric-separator               7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-throw-expressions               7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-syntax-dynamic-import                    7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-syntax-import-meta                       7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-transform-flow-strip-types               7.0.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-transform-react-jsx                      7.0.0           7.3.0   7.3.0  onfido-sdk-ui
@babel/plugin-transform-runtime                   7.0.0-rc.3           7.4.4   7.4.4  onfido-sdk-ui
@babel/preset-env                                      7.1.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/register                                        7.0.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/runtime-corejs2                            7.0.0-rc.3           7.4.4   7.4.4  onfido-sdk-ui
autoprefixer                                           7.2.3           7.2.6   9.5.1  onfido-sdk-ui
babel-core                                    7.0.0-bridge.0  7.0.0-bridge.0  6.26.3  onfido-sdk-ui
babel-loader                                           8.0.4           8.0.5   8.0.5  onfido-sdk-ui
babel-upgrade                                         0.0.23          0.0.23   1.0.1  onfido-sdk-ui
blueimp-load-image                                    2.12.2          2.12.2  2.21.0  onfido-sdk-ui
classnames                                             2.2.5           2.2.5   2.2.6  onfido-sdk-ui
css-loader                                             2.1.0           2.1.1   2.1.1  onfido-sdk-ui
eslint                                                5.14.1          5.16.0  5.16.0  onfido-sdk-ui
eslint-plugin-flowtype                                 3.4.2           3.7.0   3.7.0  onfido-sdk-ui
eslint-plugin-react                                   7.12.4          7.13.0  7.13.0  onfido-sdk-ui
eventemitter2                                          2.1.3           2.1.3   5.0.1  onfido-sdk-ui
file-loader                                            0.9.0           0.9.0   3.0.1  onfido-sdk-ui
flow-bin                                              0.93.0          0.93.0  0.98.0  onfido-sdk-ui
history                                                4.5.1           4.5.1   4.9.0  onfido-sdk-ui
http-server                                           0.10.0          0.10.0  0.11.1  onfido-sdk-ui
jest                                                  23.6.0          23.6.0  24.7.1  onfido-sdk-ui
jest-cli                                              23.6.0          23.6.0  24.7.1  onfido-sdk-ui
less-loader                                            4.0.5           4.1.0   5.0.0  onfido-sdk-ui
mini-css-extract-plugin                                0.5.0           0.5.0   0.6.0  onfido-sdk-ui
node-polyglot                                          2.2.2           2.3.0   2.3.0  onfido-sdk-ui
pdfobject                                      2.0.201604172   2.0.201604172   2.1.1  onfido-sdk-ui
postcss-base64                                         0.4.1           0.4.1   0.7.1  onfido-sdk-ui
postcss-custom-media                                   5.0.1           5.0.1   7.0.8  onfido-sdk-ui
postcss-loader                                         2.0.9           2.1.6   3.0.0  onfido-sdk-ui
postcss-url                                            7.3.0           7.3.2   8.0.0  onfido-sdk-ui
preact-compat                                         3.18.4          3.18.5  3.18.5  onfido-sdk-ui
react-modal-onfido                                     1.5.2           1.5.2   1.5.3  onfido-sdk-ui
react-native-listener                                  1.0.1           1.0.1   1.0.2  onfido-sdk-ui
react-phone-number-input                              0.15.2          0.15.2  2.3.11  onfido-sdk-ui
react-redux                                            4.4.6           4.4.6   7.0.3  onfido-sdk-ui
react-webcam-onfido                                   0.1.10          0.1.12  0.1.12  onfido-sdk-ui
redux                                                  3.5.2           3.5.2   4.0.1  onfido-sdk-ui
regenerator-runtime                                   0.12.1          0.12.1  0.13.2  onfido-sdk-ui
reselect                                               2.5.1           2.5.1   4.0.0  onfido-sdk-ui
rimraf                                                 2.6.2           2.6.3   2.6.3  onfido-sdk-ui
socket.io-client                                       2.0.4           2.2.0   2.2.0  onfido-sdk-ui
source-map-loader                                      0.1.6           0.1.6   0.2.4  onfido-sdk-ui
speed-measure-webpack-plugin                           1.3.0           1.3.1   1.3.1  onfido-sdk-ui
supports-webp                                          1.0.3           1.0.3   2.0.1  onfido-sdk-ui
terser-webpack-plugin                                  1.2.2           1.2.3   1.2.3  onfido-sdk-ui
visibilityjs                                           1.2.4           1.2.4   2.0.2  onfido-sdk-ui
webpack                                               4.29.5          4.30.0  4.30.0  onfido-sdk-ui
webpack-bundle-analyzer                               2.11.1          2.13.1   3.3.2  onfido-sdk-ui
webpack-cli                                            3.2.3           3.3.1   3.3.1  onfido-sdk-ui
webpack-dev-server                                     3.2.0           3.3.1   3.3.1  onfido-sdk-ui
wpt                                                   5.1.19             git     git  onfido-sdk-ui
</pre>

</details>

## After running `npm audit fix --force`
```
added 194 packages from 107 contributors, removed 121 packages, updated 116 packages and moved 18 packages in 30.946s
fixed 127 of 128 vulnerabilities in 50671 scanned packages
  1 vulnerability required manual review and could not be updated
  3 package updates for 127 vulns involved breaking changes
  (installed due to `--force` option)
```
### `npm audit`
```
found 1 high severity vulnerability in 1716243 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```
### **Simple check shows that `npm run dev` and `npm run test` still works fine**

`package.json` changes
```
jest@^23.6.0 --> ^24.7.1
jest-cli@^23.6.0 --> ^24.7.1
webpack-bundle-analyzer@^2.11.1 --> ^3.3.2
```

<details><summary>npm outdated</summary>

<pre>
Package                                              Current          Wanted  Latest  Location
@babel/cli                                             7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/core                                            7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-class-properties                7.1.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-decorators                      7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-export-default-from             7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-export-namespace-from           7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-function-sent                   7.1.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-json-strings                    7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-numeric-separator               7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-throw-expressions               7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-syntax-dynamic-import                    7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-syntax-import-meta                       7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-transform-flow-strip-types               7.0.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-transform-react-jsx                      7.0.0           7.3.0   7.3.0  onfido-sdk-ui
@babel/plugin-transform-runtime                   7.0.0-rc.3           7.4.4   7.4.4  onfido-sdk-ui
@babel/preset-env                                      7.1.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/register                                        7.0.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/runtime-corejs2                            7.0.0-rc.3           7.4.4   7.4.4  onfido-sdk-ui
autoprefixer                                           7.2.3           7.2.6   9.5.1  onfido-sdk-ui
babel-core                                    7.0.0-bridge.0  7.0.0-bridge.0  6.26.3  onfido-sdk-ui
babel-loader                                           8.0.4           8.0.5   8.0.5  onfido-sdk-ui
babel-upgrade                                         0.0.23          0.0.23   1.0.1  onfido-sdk-ui
blueimp-load-image                                    2.12.2          2.12.2  2.21.0  onfido-sdk-ui
classnames                                             2.2.5           2.2.5   2.2.6  onfido-sdk-ui
css-loader                                             2.1.0           2.1.1   2.1.1  onfido-sdk-ui
eslint                                                5.14.1          5.16.0  5.16.0  onfido-sdk-ui
eslint-plugin-flowtype                                 3.4.2           3.7.0   3.7.0  onfido-sdk-ui
eslint-plugin-react                                   7.12.4          7.13.0  7.13.0  onfido-sdk-ui
eventemitter2                                          2.1.3           2.1.3   5.0.1  onfido-sdk-ui
file-loader                                            0.9.0           0.9.0   3.0.1  onfido-sdk-ui
flow-bin                                              0.93.0          0.93.0  0.98.0  onfido-sdk-ui
history                                                4.5.1           4.5.1   4.9.0  onfido-sdk-ui
http-server                                           0.10.0          0.10.0  0.11.1  onfido-sdk-ui
less-loader                                            4.0.5           4.1.0   5.0.0  onfido-sdk-ui
mini-css-extract-plugin                                0.5.0           0.5.0   0.6.0  onfido-sdk-ui
node-polyglot                                          2.2.2           2.3.0   2.3.0  onfido-sdk-ui
pdfobject                                      2.0.201604172   2.0.201604172   2.1.1  onfido-sdk-ui
postcss-base64                                         0.4.1           0.4.1   0.7.1  onfido-sdk-ui
postcss-custom-media                                   5.0.1           5.0.1   7.0.8  onfido-sdk-ui
postcss-loader                                         2.0.9           2.1.6   3.0.0  onfido-sdk-ui
postcss-url                                            7.3.0           7.3.2   8.0.0  onfido-sdk-ui
preact-compat                                         3.18.4          3.18.5  3.18.5  onfido-sdk-ui
react-modal-onfido                                     1.5.2           1.5.2   1.5.3  onfido-sdk-ui
react-native-listener                                  1.0.1           1.0.1   1.0.2  onfido-sdk-ui
react-phone-number-input                              0.15.2          0.15.2  2.3.11  onfido-sdk-ui
react-redux                                            4.4.6           4.4.6   7.0.3  onfido-sdk-ui
react-webcam-onfido                                   0.1.10          0.1.12  0.1.12  onfido-sdk-ui
redux                                                  3.5.2           3.5.2   4.0.1  onfido-sdk-ui
regenerator-runtime                                   0.12.1          0.12.1  0.13.2  onfido-sdk-ui
reselect                                               2.5.1           2.5.1   4.0.0  onfido-sdk-ui
rimraf                                                 2.6.2           2.6.3   2.6.3  onfido-sdk-ui
socket.io-client                                       2.0.4           2.2.0   2.2.0  onfido-sdk-ui
source-map-loader                                      0.1.6           0.1.6   0.2.4  onfido-sdk-ui
speed-measure-webpack-plugin                           1.3.0           1.3.1   1.3.1  onfido-sdk-ui
supports-webp                                          1.0.3           1.0.3   2.0.1  onfido-sdk-ui
terser-webpack-plugin                                  1.2.2           1.2.3   1.2.3  onfido-sdk-ui
visibilityjs                                           1.2.4           1.2.4   2.0.2  onfido-sdk-ui
webpack                                               4.29.5          4.30.0  4.30.0  onfido-sdk-ui
webpack-cli                                            3.2.3           3.3.1   3.3.1  onfido-sdk-ui
webpack-dev-server                                     3.2.0           3.3.1   3.3.1  onfido-sdk-ui
wpt                                                   5.1.19             git     git  onfido-sdk-ui
</pre>
</details>

## `ecstatic`'s high severity vulnerability
This one is tricky though. Yesterday owner of this package unpublished all (really) versions from npm because of vulnerability. And although you can still fix vulnerability on your side by upgrading that one package in your `package-lock.json` manually, it's not a solution.
Currently there is [an open issue](https://github.com/jfhbrook/node-ecstatic/issues/255) on their side to provide version for at least ^3.x.x so that ppl will be able to install `http-server`. also there is [an open issue](https://github.com/indexzero/http-server/issues/521) on their side too.

So for that one you should wait. Oooor change the package to some other static server for Travis (seems like you are using it for Travis only).

### `npm run dev` runs but page has errors because of `redux`. some minor changes to codebase.

<details><summary>npm outdated</summary>

<pre>
Package                          Current          Wanted  Latest  Location
autoprefixer                       7.2.6           7.2.6   9.5.1  onfido-sdk-ui
babel-core                7.0.0-bridge.0  7.0.0-bridge.0  6.26.3  onfido-sdk-ui
babel-upgrade                     0.0.23          0.0.23   1.0.1  onfido-sdk-ui
blueimp-load-image                2.12.2          2.12.2  2.21.0  onfido-sdk-ui
classnames                         2.2.5           2.2.5   2.2.6  onfido-sdk-ui
eventemitter2                      2.1.3           2.1.3   5.0.1  onfido-sdk-ui
file-loader                        0.9.0           0.9.0   3.0.1  onfido-sdk-ui
flow-bin                          0.93.0          0.93.0  0.98.0  onfido-sdk-ui
history                            4.5.1           4.5.1   4.9.0  onfido-sdk-ui
http-server                       0.10.0          0.10.0  0.11.1  onfido-sdk-ui
less-loader                        4.1.0           4.1.0   5.0.0  onfido-sdk-ui
mini-css-extract-plugin            0.5.0           0.5.0   0.6.0  onfido-sdk-ui
pdfobject                  2.0.201604172   2.0.201604172   2.1.1  onfido-sdk-ui
postcss-base64                     0.4.1           0.4.1   0.7.1  onfido-sdk-ui
postcss-custom-media               5.0.1           5.0.1   7.0.8  onfido-sdk-ui
postcss-loader                     2.1.6           2.1.6   3.0.0  onfido-sdk-ui
postcss-url                        7.3.2           7.3.2   8.0.0  onfido-sdk-ui
react-modal-onfido                 1.5.2           1.5.2   1.5.3  onfido-sdk-ui
react-native-listener              1.0.1           1.0.1   1.0.2  onfido-sdk-ui
react-phone-number-input          0.15.2          0.15.2  2.3.11  onfido-sdk-ui
react-redux                        4.4.6           4.4.6   7.0.3  onfido-sdk-ui
redux                              3.5.2           3.5.2   4.0.1  onfido-sdk-ui
regenerator-runtime               0.12.1          0.12.1  0.13.2  onfido-sdk-ui
reselect                           2.5.1           2.5.1   4.0.0  onfido-sdk-ui
source-map-loader                  0.1.6           0.1.6   0.2.4  onfido-sdk-ui
supports-webp                      1.0.3           1.0.3   2.0.1  onfido-sdk-ui
visibilityjs                       1.2.4           1.2.4   2.0.2  onfido-sdk-ui
wpt                               5.1.19             git     git  onfido-sdk-ui
</pre>
</details>

Of course you can also update all major versions and keep updating packages once in a while when you bump major version of package (and seems like you do it often)

## Why? why you haven't spotted this (maybe you did, maybe not)
`npm install` automatically does `npm audit` so you should have been able to see these warnings already. But the tool that you are using `Snyk` which is integrated to this repository is not checking lock files. :( so it sees, for ex., `@babel/core@^7.1.2` and it checks with fresh version of that package instead of checking locked version. Thats why all your pull request are "ok", but in reality they are not.

## Conclusion
Always keep your dependencies up to date and try to keep their count to as small as you can.

p.s. `wpt` is installed and pinned to specific version via Github tag instead of package. I am not here to judge, but probably it make sense to use their package via npm instead.

**Comment by davityavryan** [comment]
p.s.2. Same thing is in `onfido-sdk-core` but with >700 known vulnerabilities. but that's another topic for other repo.

**Comment by davityavryan** [comment]
[Good news](https://github.com/jfhbrook/node-ecstatic/issues/255#issuecomment-489098210). `ecstatic` has published [new version for `^3.x.x`](https://github.com/jfhbrook/node-ecstatic/compare/3.3.1...3.3.2) so upgrading `http-server` will fix all vulnerabilities

**Comment by rfreitas** [comment]
Hi @davityavryan 

Thank you for the very detailed report.

In terms of cleaning some of those vulnerabilities, there is a PR here: https://github.com/onfido/onfido-sdk-ui/pull/595 which tackled all known vulnerabilities at that time, unfortunately we haven't released it yet. At the time time the main culprits were `surge` and `jest`, both of which do not touch production code at neither build or runtime, hence why we didn't push for an hotfix.

However, since that PR there have been new vulnerabilities discovered, which seem to include the following dependencies: `http-server`; `babel-cli`; `eslint and `postcss-loader`.
Out of those only `postcss-loader` carries risk, since the other ones do not touch production code (`babel-cli` is not used by webpack, it's only user for local debugging). I will discuss with the team to figure out if we should publish an hotfix for the `postcss-loader`, which technically should only touch CSS code, but still might carry risk due to being part of the build stack. Otherwise the next release will include the the vulnerability fixes. (New PR here: https://github.com/onfido/onfido-sdk-ui/pull/651 )
Due to this, your point on Snyk is also a good one. If you know of a better tooling for this, please do share. In the meantime we will be looking to improve the monitoring.

For `wpt` we were not able to find an npm package of the woopra client tracker, however if you have, it would be great if you could share it with us.

**Comment by davityavryan** [comment]
Hey @rfreitas,
Thanks for response.
Sorry I didn't know about #595. And thanks for #651. Can't wait for a new release.

### Regarding a tool to catch vulnerabilities
Although Snyk is good. but yeah as of they are not testing with lock files in mind you can even remove that tool from your project(s). And the easiest way to find vulnerabilities will be old `npm audit` :)
I mean you can run `npm audit` on travis and check for exit code. (p.s. probably even `npm install` will return error code as of it does run `npm audit`).
Meanwhile I am writing an open-source tool which will do that kind of checks recursively. I will ping you here when I will implement it and you guys can decide if you want to use it.

### Regarding `wpt`
I see what you mean. They have a package for node but not for client side.
Not sure why you are specifically targeting that version. but yeah ok.
I will only suggest you to change the way that it installs. In [early days](https://github.com/onfido/onfido-sdk-ui/blame/3b546018fe6dafd2f6a193664c074813b2154cd7/package.json#L117) you were targeting tarball from master in your own repository, but then you changed it to git tag on Woopra repo. The problem is that you are requiring `git` as executable to be available in install stage. Which IMO is not a good idea.
I would suggest to change it to tarball again (this time same Woopra's repo's tarball) which will be pointing to same code source by running `npm install wpt@https://github.com/Woopra/js-client-tracker/archive/v5.1.19.tar.gz`. it will also of course change your `package-lock.json` file but that's expected.
IMHO all the install stages should not require any extra tools (especially `git`). This can be also automatically tested by several lines of `Dockerfile` on CI. This way you will isolate your potentially vulnerable `package.json` and `package-lock.json` from source code. This is just an extra test for you and of course it is just a recomendation.

<details><summary>Dockerfile</summary>

<pre>
FROM node:10-alpine

WORKDIR /app

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

CMD npm install
# and some checks here. like `npm audit`
# and the you can copy rest and do your magic there
</pre>

</details>

### And in general
If you will keep your packages up to date (like upgrade your devDependencies once a month and non dependencies once two months) will help us (users/developers) happier. And you will make sure that you don't have vulnerability pollution.

**Comment by davityavryan** [comment]
Hey @rfreitas,

Do you have any updates regarding `wpt`?

I can open a pull request if needed.

**Comment by stefaniacardenas** [comment]
Hi @davityavryan. Thanks for the suggestion. We are planning to work on it in the next three weeks but feel free to go ahead and open a PR. Thank you very much!

**Comment by davityavryan** [comment]
@stefaniacardenas Done. :)

**Comment by davityavryan** [comment]
p.s. I will mark this issue as closed after PR will be merged. if it's fine for you.

**Comment by davityavryan** [comment]
I am going to close this issue as of the points mentioned here are resolved. Thanks a lot for your work.

*But* at the end we decided to use CDN version of your package and not include all the really really outdated packages into our system.

p.s. removing `onfido-sdk-ui` package from our `package.json` was fun because it also introduced a lot of "red"-s in `yarn.lock` file. I might be wrong but approximately 30% of packages were required by your package :(
