### ISSUE TITLE
Backbutton should have `type="button"`

### ISSUE THREAD

**Issue by afkatja** [onfido/onfido-sdk-ui#647]
The back button in the Onfido component is implemented like this:
```
<button href="#" class="onfido-sdk-ui-NavigationBar-back onfido-sdk-ui-NavigationBar-disabled onfido-sdk-ui-NavigationBar-backHoverDesktop"><span class="onfido-sdk-ui-NavigationBar-iconBack"></span><span class="onfido-sdk-ui-NavigationBar-label">back</span></button>
```
This has two issues:
- the `href` attribute is invalid for the `button` tag
- it misses the `type` attribute and the browsers interpret it as `type="submit"`
In our case, this bug causes the component to reload our application, which results in unexpected behavior.

The fix should be:
```
<button class="onfido-sdk-ui-NavigationBar-back onfido-sdk-ui-NavigationBar-disabled onfido-sdk-ui-NavigationBar-backHoverDesktop" type="button"><span class="onfido-sdk-ui-NavigationBar-iconBack"></span><span class="onfido-sdk-ui-NavigationBar-label">back</span></button>
```
_or_
in the onClick event handler, `preventDefault()` and `stopPropagation()` should be added.
Both solutions simultaneously wouldn't hurt either.

**Comment by kopijunkie** [comment]
Hi @afkatja 

Thank you for highlighting this issue and this has been addressed in release 5.1.0 so I will close this ticket now. But feel free to re-open it if you find any buttons that we might have missed.
