### ISSUE TITLE
Onfido for React Web app

### ISSUE THREAD

**Issue by zohaib10** [onfido/onfido-sdk-ui#657]
Hi, I have a simple question on if I have the correct flow for how to setup the Onfido SDK in React. 
1) Have an API key
2) Create an Onfido applicant token on the backend
3) generate an SDK token? Does this need to be done on the backend or can it be done on the frontend? also does ios require this or is it only needed to web? 
4) after this we can initialize the SDK and do the image processing stuff

Thank you in Advance for an answer.

**Comment by stefaniacardenas** [comment]
Hi @zohaib10, apologies for the late reply. Regarding the point below
> generate an SDK token? Does this need to be done on the backend or can it be done on the frontend? also does ios require this or is it only needed to web?
Yes, you should generate the SDK token on the backend. Currently, only the Web SDK uses JSON Web Tokens.
I hope this helps. Please let me know if you have any other question.

**Comment by stefaniacardenas** [comment]
Hi @zohaib10, did you manage to complete the integration? I will close this issue for now but feel free to get in touch if you have any other question.
