### ISSUE TITLE
Instruction to remove glasses on the selfie

### ISSUE THREAD

**Issue by phackwer** [onfido/onfido-sdk-ui#661]
Hi,

When doing the selfie I continuously get a "No face found" error, easily bypassed when I just remove my glasses. I think it would be nice to have instructions regarding that on the selfie page. Small note 
"Remove your glasses for a better facial recognition" or something like it.

**Comment by seewah** [comment]
Hi, thanks for the feedback. This is actually on the roadmap, and we will be adding an introduction screen for the selfie step in the short/mid term. Incidentally, most of the time, glasses do not interfere with either the capture or the analysis of the selfie too much. The important point is that the eyes are visible. Again thanks for the suggestion!

**Comment by emanuelverardi** [comment]
Hi, could we also add the possibility of overwrite the presented texts on the selfie screens? Actually it would be nice if we could do text setting on all screens.

**Comment by ctrlaltdylan** [comment]
This is very related to my comments on the other issue I opened:

https://github.com/onfido/onfido-sdk-ui/issues/696

@seewah is there a timetable for when the introduction screen for the selfie step will be available? The translations are specified in the language JSON but they don't appear to be doing anything.

**Comment by seewah** [comment]
Unfortunately we could not prioritise this last quarter due to our focus on accessibility support on the SDK. We will try to fit this into our development roadmap over the next few months, but I am afraid I cannot give a more concrete ETA for the intro screen right now, sorry.

**Comment by ctrlaltdylan** [comment]
@seewah thank you for the update

**Comment by stefaniacardenas** [comment]
Sorry for the late update. The selfie intro screen that include guidance on removing glasses during selfie capture has been released in version [5.7.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.7.0). Closing this issue now.
