### ISSUE TITLE
DocumentStep bypassing

### ISSUE THREAD

**Issue by tnmendes** [onfido/onfido-sdk-ui#676]
In the iOS Onfido SDK, you can provide documentType and Country Code and by doing that you can be bypassing the need to show the option to select the that.
You can achieve that by doing this:
```swift
let config = try! OnfidoConfig.builder()
            .withToken(Configuration.kOnfidoMobileToken)
            .withApplicantId(authorization)
            .withFaceStep(ofVariant: .photo) // photo or video
            .withAppearance(contentView.getOnfidoAppearance()) // UI customisation
            .withDocumentStep(ofType: documentType, andCountryCode: coutryCode) // Flow customisation, documents select
            .build()
```

More specifically this line:
```swift
.withDocumentStep(ofType: documentType, andCountryCode: coutryCode) // Flow customisation, documents select
```

How can I do the same thing on Onfido SDK UI?

**Comment by kopijunkie** [comment]
Hi @tnmendes 

Could you give more details about what you are trying to achieve so that I can better understand what setting you need? The country code selection for documents is not required for the web SDK.

**Comment by tnmendes** [comment]
HI @kopijunkie, 

I want to achieve the same that you can do Onfido iOS SDK
https://github.com/onfido/onfido-ios-sdk#customising-sdk

```
Let's say that you would like to capture only driving licenses from the United Kingdom. The following code shows how to do this:
.withDocumentStep(ofType: .drivingLicence, andCountryCode: "GBR")
```

I already know the country and the document of the user and when I load the Onfido UI SDK I want to avoid showing the documents step as I do with iOS SDK.

How can achieve that? Thank you

**Comment by kopijunkie** [comment]
Hi @tnmendes 

Apologies for the late response. Unfortunately this feature on the iOS SDK is not available on the JS SDK.

**Comment by kopijunkie** [comment]
Will close this ticket due to inactivity and also as this is an iOS SDK feature that is not supported on the JS SDK.
