### ISSUE TITLE
iPad Mini 2 - iOS 9.3.5 hangs after upgrading from v3 to v5.

### ISSUE THREAD

**Issue by phackwer** [onfido/onfido-sdk-ui#677]
Hi,

We have migrated from v3 to v5 by basically replacing the js file and doing some tweaks for the CSS to match our webapp and we are having reports of errors with iPad 2 mini iOS 9.5.3 now.

Are there any significant changes that could cause this problem?

Thank you.

**Comment by stefaniacardenas** [comment]
Hi @phackwer, do you have any details about the errors you are seeing on iPad 2?

**Comment by phackwer** [comment]
Hi @stefaniacardenas ,

If you have access to BrowserStack, choose iOS, Other versions, and iPad Mini 4, iOS 9.3 - closest emulator I know to the problem with the device.

We tested on a newer iPad Air 2 and it worked. So, if you could tell us up to what version of iOS you are supporting, we can at least warn our users that they will need to skip that step and continue from a desktop or supported device.

**Comment by kopijunkie** [comment]
Hi @phackwer 

I tried with our SDK demo app with the SDK's latest build (5.2.1) on BrowserStack with the emulator you mentioned and an iPad Air we have that's running on iOS 9.3.2 but was unable to find any issues or errors running through all the steps. 

Could you give us more details and/or some screenshots of the errors you're getting on the iPad Mini?

**Comment by phackwer** [comment]
Hi. This is what happens on that iPad with iOS 9.3

![image](https://user-images.githubusercontent.com/4871786/59424613-35fb0980-8dcc-11e9-83d4-04519f1ac8db.png)

And this is what happens to newer iPads (it works)

![image](https://user-images.githubusercontent.com/4871786/59424803-8f633880-8dcc-11e9-88e7-d9e8b6d3e7de.png)

**Comment by phackwer** [comment]
Obs: we did font and colors adjustments on the CSS to match our layout, but that's all we did it.

**Comment by phackwer** [comment]
Obs2: ,{environment:"production",release:"5.2.1",debug:!0,autoBreadcrumbs:{console:!1},

I think we are already using 5.2.1

**Comment by kopijunkie** [comment]
@phackwer Since I am still unable to reproduce it with our end, are you able to share a link where we can have a look at what the problem might be?
