### ISSUE TITLE
Jest will not run on component loading onfido-sdk-ui

### ISSUE THREAD

**Issue by jingoldby** [onfido/onfido-sdk-ui#680]
Hi there,

just running into an issue where our test suite (jest) does not run when we import the onfido-sdk into our react onboarding component. Wondering if this is a known or previously experienced issue with any versions?

I set up a basic example repo [here](https://github.com/jingoldby/onfido-example) where you can see jest fails when onfido is imported into a component.

All tests run when I comment out this import and remove references to onfido. Appreciate any thoughts you might have on this issue.

Cheers.

**Comment by stefaniacardenas** [comment]
Hi, does the issue happen only when you try to run the tests or are you unable to import the library entirely? Thanks for creating the example, I will have a look at it tomorrow. My guess is that it might be related to this issue https://github.com/onfido/onfido-sdk-ui/issues/615

**Comment by jingoldby** [comment]
Thanks for the quick response! I can confirm it's just when we run tests. The library loads and runs as expected with the iframe popping up on init.

**Comment by jingoldby** [comment]
just revisiting this with a clean repo and I now just have a 'window is not defined' error in the component loading the sdk.

I think this might be a known issue but not sure what the solution is (I've tried awaiting onfido-sdk in componentDidMount but still no luck). Any help appreciated! Cheers
