### ISSUE TITLE
mobilePhrases for capture.face.instructions incorrectly mapped and not working as expected

### ISSUE THREAD

**Issue by ctrlaltdylan** [onfido/onfido-sdk-ui#696]
Running v5 of `onfido-ui-sdk` and I have been trying to include additional instructions on the "face" capture step on the cross device mobile page.

I tried updating the `options`, specifically the `language.mobilePhrases` as the documentation suggests:

```
     ...
      language: {
        language: 'en',
        locale: 'us',
        mobilePhrases: {
          "capture.face.instructions": "Please take a picture showing your face. For the best results, remove anything remove anything that might cover your face such as sunglasses or hats."
        }
      }
     ...
```

However, this doesn't have any affect on the face capture step on the mobile UI. I discovered that changing the `phrases.capture.face.title` does actually change the title of the mobile face capture UI page, but it's not very useful because it takes up so much space:

![Screenshot_20190614-153132](https://user-images.githubusercontent.com/2694734/59542610-a5035b80-8ebb-11e9-8efe-72db003c5455.png)

Options to reproduce:

```
      language: {
        language: 'en',
        locale: 'us',
        phrases: {
          capture: {
            face: {
              title: "Please take a picture showing your face. For the best results, remove anything remove anything that might cover your face such as sunglasses or hats.",
            }
          }
        }
```

Is there a special option I need to enable for this `mobilePhrases.capture.face.instructions` or `phrases.capture.face.instructions` to appear on this page?

**Comment by ctrlaltdylan** [comment]
On closer look, it appears that the instruction screen for the face step just is being skipped entirely and I think that may be the root cause of this issue.

**Comment by kopijunkie** [comment]
Hi @ctrlaltdylan 

Could you let me know what device/emulator you were getting this behaviour on? 

I've tried overriding the facial capture screen title with `mobilePhrase` and on Chrome mobile emulator the SDK seems to be picking up my override text.

Below is the language config I used: 
```js
language: {
    locale: "en",
    phrases: {
        capture: {
            face: {
                title: "Please take a picture showing your face. For the best results, remove anything that might cover your face such as sunglasses or hats.",
            }
        }
    },
    mobilePhrases: {
        capture: {
            face: {
                title: "Please take a picture showing your face only."
            }
        }
    }
}
```

**Comment by ctrlaltdylan** [comment]
Sorry @kopijunkie my description of the problem wasn't very good. 

The real issue is that there's no instructions page for the face step.

The `mobilePhrases.capture.face.title` is too small of an area for all of the instructions we want to leave for the users when they're uploading with their phone.

The document capture step includes an instructions step. It's missing for the face capture step.

I thought it was a mismapping issue for `mobilePhrases.capture.face.instructions` but it appears that particular property isn't showing because the instructions page doesn't exist for the face step.

I'm experiencing the issue on Chrome with Mac desktop and the Pixel 2 on the mobile screens on the latest version of onfido-ui-sdk (v5.*)

**Comment by kopijunkie** [comment]
Ah, I see what you mean now. `capture.face.instructions` is actually meant for the file upload fallback screen. If you want to have a look at this screen to see if it suits your needs, you can set `options.uploadFallback: true` in the `face` step's options. 

Though I also see you've also asked @seewah about the timetable for the introduction screen of the selfie step in another issue someone raised and I believe that is more in line with what you are looking to have.

**Comment by ctrlaltdylan** [comment]
@kopijunkie ah yes that explains it. For our use case we prefer to have the uploadFallback disabled because fraudsters are starting to upload photoshops more frequently.

@seewah is it possible to enable the face step instructions screen in the short term?

**Comment by kopijunkie** [comment]
Hi @ctrlaltdylan 

I see that @seewah has given you an update in #661 so I will close this ticket so that there's a single source for any further updates on the feature and any further related questions.
