### ISSUE TITLE
Blank page inside the onfido frame after choosing document type to upload on XiaoMi MiuiBrowser 10.8.3-g

### ISSUE THREAD

**Issue by liorJuice** [onfido/onfido-sdk-ui#697]
When you start the sdk on MiuiBrowser on a XiaoMi (we tried it on XiaoMi with Android 8.1.0 and MiuiBrowser 10.8.3-g ), it starts up just fine. After choosing the document type to upload, on the upload screen you get a blank page inside the onfido bubble:

![blank onfido](https://user-images.githubusercontent.com/45418456/59603016-fa847600-9110-11e9-82cc-27579859120e.JPG)

while debugging, there seem to be no relevant error on the console or failed network request. 

this _might_ be related to this open issue: [issue613](https://github.com/onfido/onfido-sdk-ui/issues/613), but that issue talks about a different flow.

Thanks.

Edit: we currently use onfido-sdk-ui v5.0.0 , but i was able to reproduce the problem with your v5.2.1 jsFiddle at https://jsfiddle.net/ckLh05y4/show

**Comment by seewah** [comment]
hi we will take a look at this. However, MiuiBrowser isn't something we support/test against at the moment. While its global popularity remains low, we cannot guarantee support, but we will investigate.

**Comment by amoyano** [comment]
Hi i'm having this issue too, is it resolved?  whe I try with my laptop
And when I try with my iphone last version safari and chrome  said
UNSUPPORTED BROWSER, restar tthe process with the last version....

thanks

**Comment by stefaniacardenas** [comment]
I will close this issue as MiuiBrowser is not supported
