### ISSUE TITLE
Changing the position of onfido-sdk-ui-Overlay-face with offset-y

### ISSUE THREAD

**Issue by ctrlaltdylan** [onfido/onfido-sdk-ui#700]
During the face capture step the `onfido-sdk-ui-Overlay-face` is the div that's responsible for setting the darkened face overly.

I have a `capture.face.title` that's pretty long, and I'd like to move the `onfido-sdk-ui-Overlay-face` down a bit to show the entire text and fix the collision:

<img width="303" alt="Screen Shot 2019-06-18 at 11 30 08 AM" src="https://user-images.githubusercontent.com/2694734/59708569-a5a53600-91ca-11e9-87cd-e35f32d5268e.png">

I've deduced that the `onfido-sdk-ui-Overlay-face` position is controlled by the `background-position` property which ultimately depends on a dynamic variable called `offset-y`:

https://github.com/onfido/onfido-sdk-ui/blob/86d4308555e2d9d037832ba74307cae499783932/src/components/Overlay/style.css#L41

Is there a way to control the `offset-y` dynamically or replace a constant with a different value?

**Comment by kopijunkie** [comment]
Hi @ctrlaltdylan 

Currently the only way to reposition it would be by overriding the CSS  for `background-position` for `.onfido-sdk-ui-Overlay-face`. Though I should mention that there is a possibility the CSS override will need to be updated with any change in the CSS or class name in future SDK releases.

**Comment by kopijunkie** [comment]
Closing this ticket due to inactivity but feel free to re-open if you have further questions on this.
