### ISSUE TITLE
Onfido SdK for Angular

### ISSUE THREAD

**Issue by artem-galas** [onfido/onfido-sdk-ui#704]
We have use `onfido-sdk-ui` package into Angular project, and npm complains about some `react` packages. Seems it's not broken anything. 

I'm wonder maybe those dependencies should be in `devDeps` instead?

![1561113342038](https://user-images.githubusercontent.com/6387897/59917302-49d8e800-942a-11e9-8b15-6d91fe801075.jpg)

**Comment by ctrlaltdylan** [comment]
I had this same issue as well and I manually added the react dependencies to our `package.json`.

**Comment by kopijunkie** [comment]
Some of the external libraries used in the SDK have peer dependencies. NPM used to automatically install package peer dependencies, but as of version 3 any peer dependencies need to be manually installed.

**Comment by rfreitas** [comment]
@artem-galas They should be as dev dependencies, since everything gets bundled in at compile time. However, in the latest development we have actually made them proper dependencies (not peer dependencies). This means the warning should disappear and the package.json will reflect reality.

The PR in question: https://github.com/onfido/onfido-sdk-ui/pull/698

**Comment by kopijunkie** [comment]
@artem-galas FYI we have released 5.3.0 today which includes the change mentioned. 

I will close this for now but feel free to re-open if it is still an issue.

**Comment by matheo** [comment]
@artem-galas I'm having issues with change detection.

We created an observable to stream the onModalRequestClose, onComplete and onError listeners,
but after we complete the Identity Verification the change detection (buttons are not refreshing)
and even the router is misbehaving (on mobile devices).

Have you had issues like those? Do you use NgZone?
thanks in advance for any tips
