### ISSUE TITLE
window.devToolsExtension is obsolete for Redux Dev Tools

### ISSUE THREAD

**Issue by martajedrecka** [onfido/onfido-sdk-ui#708]
on `onfido-sdk-ui/src/core/store/store.js`

```
const store = createStore(reducer,
  window.devToolsExtension ? window.devToolsExtension() : undefined
)
```

starting from v2.7, window.devToolsExtension was renamed to `window.__REDUX_DEVTOOLS_EXTENSION__ / window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
`
[https://github.com/zalmoxisus/redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension)

**Comment by kopijunkie** [comment]
Hi @martajedrecka 

Thank you for raising this. It is something we've picked up on also and it will be updated in an upcoming release.

**Comment by kopijunkie** [comment]
Keeping the ticket open as a reminder to update you when it's out. :)

**Comment by kopijunkie** [comment]
@martajedrecka FYI 5.3.0 was released today with the update to use the latest Redux Dev Tools extension name.

I will close this ticket now that it's been updated in the SDK.
