### ISSUE TITLE
Images with Glare for Onfido-sdk-ui for web

### ISSUE THREAD

**Issue by zohaib10** [onfido/onfido-sdk-ui#715]
I have integrated the onfido sdk into my react application. Our QA team has found out that if we upload images with glare we get an error saying 'glare detected' but the UI still lets the user proceed. This results in a response from Onfido with blank/undefined document_bank & document_front ids. I can catch this once the user comes out of the onfido flow. But I wan't to know if there is some option that restricts the user from proceeding? if 'glare' has been detected in an image that they upload.

**Comment by stefaniacardenas** [comment]
Hi @zohaib10, this has been fixed in [version 5.2.1](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.2.1). I would advice you to upgrade to the latest version 5.2.2.
