### ISSUE TITLE
Broken background UI

### ISSUE THREAD

**Issue by RoyRewire** [onfido/onfido-sdk-ui#716]
Hi, 

We are using onfido_sdk_version 5.0.0 and there seems to be a UI issue.
Along the right side and the bottom side there is a shaded area.
This issue acquires on a web view of 885 X 892, every time.
![Screen Shot 2019-06-30 at 18 17 58](https://user-images.githubusercontent.com/50297370/60398836-79dc6580-9b65-11e9-8f76-56d9e9ae97b7.png)

Thank you,
Roy

**Comment by stefaniacardenas** [comment]
Hi @RoyRewire, this has been fixed in [version 5.2.2 (latest)](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.2.2). Upgrading will solve the UI issue.
