### ISSUE TITLE
Misleading UI on allow camera step

### ISSUE THREAD

**Issue by alonp99** [onfido/onfido-sdk-ui#717]
Hi Guys, FYI:

Our analytics services show clearly that the most dead/rage click comes for the camera access step

![image (2)](https://user-images.githubusercontent.com/8467965/60430213-6da7e500-9c05-11e9-9f73-12e079be26d0.png)
![image (3)](https://user-images.githubusercontent.com/8467965/60430217-73052f80-9c05-11e9-8037-9b96d766576e.png)

**Comment by stefaniacardenas** [comment]
Hi @alonp99, this is a very valuable information. I will pass it over to our UX team and we will try to improve the experience. Many thanks!

**Comment by stefaniacardenas** [comment]
Hi @alonp99, our UX team was already aware of the issue and they have already implemented a new design to improve the experience. We will keep this issue open and let you know when the new UI will be released.

**Comment by alonp99** [comment]
Hi @stefaniacardenas, Happy to help.
Do you have some indication when it will be fixed?

**Comment by stefaniacardenas** [comment]
Hi @alonp99, we are implementing the new design for this screen in the current sprint, therefore the change will be available in the next release or the one after.

**Comment by stefaniacardenas** [comment]
Hi @alonp99, this issue has been fixed in release [5.3.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.3.0). We think that the new design will offer a better user experience. I will close this issue for now but please feel free to reopen if you have any further suggestions.
