### ISSUE TITLE
Running npm install fails completely because of bad wpt integrity hash

### ISSUE THREAD

**Issue by thedanwoods** [onfido/onfido-sdk-ui#726]
There's a problem with the integrity hash for the Woopra `wpt` package in `package-lock.json`. It causes `npm install` to die and it's causing our builds to fail.

To replicate, clone the repo and do a clean install:

```
$ sudo npm cache clean -f
$ git clone https://github.com/onfido/onfido-sdk-ui
$ cd onfido-sdk-ui
$ npm ci
```

### Result

```
npm WARN tarball tarball data for wpt@https://github.com/Woopra/js-client-tracker/archive/v5.1.19.tar.gz (sha512-RIk7xHxKztd58T642fISQehy6Ht5CuVbrkxuj8zjeMxpVoyQhFREIiCzqeXtRahH+/XzuAVaIFR+L4nUG7lggw==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for wpt@https://github.com/Woopra/js-client-tracker/archive/v5.1.19.tar.gz (sha512-RIk7xHxKztd58T642fISQehy6Ht5CuVbrkxuj8zjeMxpVoyQhFREIiCzqeXtRahH+/XzuAVaIFR+L4nUG7lggw==) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting wpt@https://github.com/Woopra/js-client-tracker/archive/v5.1.19.tar.gz:
npm ERR! Verification failed while extracting wpt@https://github.com/Woopra/js-client-tracker/archive/v5.1.19.tar.gz:
npm ERR! sha512-RIk7xHxKztd58T642fISQehy6Ht5CuVbrkxuj8zjeMxpVoyQhFREIiCzqeXtRahH+/XzuAVaIFR+L4nUG7lggw== integrity checksum failed when using sha512: wanted sha512-RIk7xHxKztd58T642fISQehy6Ht5CuVbrkxuj8zjeMxpVoyQhFREIiCzqeXtRahH+/XzuAVaIFR+L4nUG7lggw== but got sha512-hVv+NyLVpiUI3FDb8hc6dfLmBPo+ZaCbx1dKr+8MqpQZXYjQ3lca2QuYbuLlWWtu953TrrsrqOx2uGe/46rkcg==. (99852 bytes)
```

We think it's caused by referencing a github archive tarball, which is ephemeral. Github tarballs are prone to integrity errors because github may generate different tarball files from the same content. npm will then generate a different integrity hash.

It might be better to inline `wpt` into the build rather than relying on an external tarball which might fail.

If you're installing from a stale npm cache in your build it's likely you won't see this error, but you'll get it as soon as you refresh your cache.

**Comment by rfreitas** [comment]
We are planning to release a patch this week. Sorry for the inconvenience. 🙏 

In the meantime have you been able to find any workaround @thedanwoods ?

**Comment by thedanwoods** [comment]
We've got it to build by manually editing the `wpt` hash in our `package-lock.json` to

```
"integrity": "sha512-hVv+NyLVpiUI3FDb8hc6dfLmBPo+ZaCbx1dKr+8MqpQZXYjQ3lca2QuYbuLlWWtu953TrrsrqOx2uGe/46rkcg==",
```

Although it works for now, it isn't a good idea and we're expecting it to break again at any moment.

**Comment by rfreitas** [comment]
Cool, thanks for the (temporary) workaround!

**Comment by irot** [comment]
For anyone else stumbling into this thread with the same error, downgrading one patch version fixed our builds (from 5.2.2 to 5.2.1 at the time of writing).

**Comment by stefaniacardenas** [comment]
Hi, we've just released a fix for this issue in version `5.2.3`. Please let me know if it works as expected and I will close this issue.
Changelog [here](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.2.3)

**Comment by rfreitas** [comment]
Just to clarify, we have removed the tarball installation. At the same time this dependency has been moved to a dev dependency, since this code is actually bundled at compile time. The implication of this last point is that as a client/developer you won't be downloading this dependency, only contributors will have to.

**Comment by thedanwoods** [comment]
Thanks! This seems to work.

**Comment by rfreitas** [comment]
great :)
