### ISSUE TITLE
Translation fails for "Look over your %{side} shoulder"

### ISSUE THREAD

**Issue by JessicaML** [onfido/onfido-sdk-ui#738]
I added the onfido translation keys, but the string "Look over your %{side} shoulder" does not pick up the variable `side` and treats it as a string.

**Comment by stefaniacardenas** [comment]
Hi @JessicaML, which version of the SDK are you using?

**Comment by afkatja** [comment]
Hi @stefaniacardenas , we're using v5.0.0 of the js SDK

**Comment by stefaniacardenas** [comment]
Hi @JessicaML and @afkatja,
I've created a [JSFiddle](https://jsfiddle.net/a5druz7v/) and I can see that the feature is working as expected. 
How are you passing the strings? Have you included the "right" and "left" keys to replace the `side` variable?
