### ISSUE TITLE
iOS Safari asks for selfie (picture) instead of video

### ISSUE THREAD

**Issue by josephan** [onfido/onfido-sdk-ui#754]
Onfido SDK Version: `5.2.2`
Device Model: `iPhone X`
OS Version: `iOS 12.4`
Browser: `Safari 12.1`
Onfido Config:
```javascript
Onfido.init({
  token: "...",
  containerId: "onfido-mount",
  steps: [
    "document",
    { type: "face", options: { requestedVariant: "video" } }
  ],
  onComplete: () => {
    // omitted for brevity
  }
})
```

When a user reaches the Facial Similarity step, we expect the user be prompted to take a video but was prompted to take a picture instead.

#### Screenshot
![Image from iOS](https://user-images.githubusercontent.com/8878596/61891108-edf4f980-aed6-11e9-8d55-b51f8548ae03.png)

**Comment by josephan** [comment]
It was working as expected on the following Android device:
Device Model: `OnePlus 3`
OS: `Android 9; OxygenOS 9.0.4`
Browser Version: `Chrome 75.0.3770.143`

**Comment by stefaniacardenas** [comment]
Hi, unfortunately iOS does not support video recording because there is no support for MediaRecorder API. For cases like this, we fallback to selfie capture. You should be able to take a picture with the camera inside the browser if permission have been granted. I hope this helps.

**Comment by josephan** [comment]
@stefaniacardenas in that case would you recommend changing the `required_reports` of a `check` dynamically based on the user's device/browser?
For example:
```ruby
def required_reports
  variant = logic_on_user_device? ? "standard" : "video"
  [
    {name: "document"},
    {name: "facial_similarity", variant: variant} 
  ]
end
```

**Comment by stefaniacardenas** [comment]
Hi @josephan, please find my answers below.
>In that case, would we have to updaterequired_reports dynamically based on the user's device/browser before creating a check?

Yes, you will have to initiate the check dynamically using variant returned within the `onComplete` callback. Please refer to this part of the [documentation](https://github.com/onfido/onfido-sdk-ui#handling-callbacks). 

>We tell users to use a supported web browser like chrome or firefox.

That would definitely help with user drop off, so if you have the chance to do that, please feel free to add that tip within your application. Please bear in mind that we already have in place a series of fallbacks to try to fulfil your requested variant. For example, when the `video` variant is requested and the user is using a desktop browser where taking a video or a selfie is not possible, we will force the user to use their mobile phone via our built-in SMS feature. Once on their mobile browser, we will again try to fulfil the video variant first, and if that's not possible we will fallback to selfie. 
We hope that the next versions of Safari on iOS will support video recording.
Please let me know if you have any other question.

**Comment by stefaniacardenas** [comment]
I will close this issue. Feel free to get in touch if you have any other questions or suggestions.
