### ISSUE TITLE
React-Boilerplate Production build failed

### ISSUE THREAD

**Issue by dhavalsoni2001** [onfido/onfido-sdk-ui#757]
I am using onfido with React- Boilerplate and **ant** design. I was facing the following error when I generate the production build. After lots of investigation, I find out that it occurs because of this plugin. I am getting below error when I try to run production build.

> @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
`Uncaught RangeError: Maximum call stack size exceeded`

Here I am attaching the screenshot for the same where babel/polyfill has been called recursively.
![Screenshot 2019-07-30 at 12 43 42 PM](https://user-images.githubusercontent.com/11704436/62108458-b798ef00-b2c7-11e9-934f-428822587e4c.png)

**Comment by rfreitas** [comment]
Hi @dhavalsoni2001 ,

what is the sdk version you are using?

We are not actually using the babel polyfill, so this error might not be related to our sdk. Can you create a build without our sdk and see if the issue still persists?
For context, we are using babel runtime with the option that transpiles JS apis to library calls, so no polyfill.

**Comment by dhavalsoni2001** [comment]
I had built app without onfido ask and it:s working perfectly fine.

**Comment by rfreitas** [comment]
How of curiosity if you import the file under `dist`. do you also get the same error?

**Comment by dhavalsoni2001** [comment]
@rfreitas @kopijunkie I have directly added CDN of `dist` folder into index.html and it's working perfectly fine.

**Comment by stefaniacardenas** [comment]
Hi @dhavalsoni2001, we have just fixed some issues related with importing the `onfido-sdk-ui` library. Please upgrade to [5.3.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.3.0) (latest) and let me know if it fix the problem. Thank you
