### ISSUE TITLE
Camera permission broken for selfie (working for all other cases) 

### ISSUE THREAD

**Issue by rrigoni** [onfido/onfido-sdk-ui#774]
We are facing an issue with the Onfido Web Sdk embedded in a webview in an Android app. 
The app has camera permission granted. 

1 - Camera works just fine to take front of ID
2 - Camera works just fine to take the back of the ID 
3 - Camera permission warning fails in the next step to take the Selfie 
4 - When clicking in "Enable Camera" it finally shows the error page with no camera access warning. 

LIbrary version: https://assets.onfido.com/web-sdk-releases/5.2.3/onfido.min.js

Android Version 9
Android Device: Galaxy S8

**Sdk Config**
````
this.onfidoSdk = Onfido.init({
            useModal: false,
            isModalOpen: false,
            language: 'en',
            options: {
                forceCrossDevice: true,
                documentTypes: {
                    passport: true,
                    driving_licence: true,
                    national_identity_card: true
                }
            },
            token: this.onfidoToken,
            containerId: 'onfido-mount',
            onComplete: (data: any) => {
                // do stuff
            },
            steps: [
                'document',
                'face'
            ]
        })
````

Screenshots: 

1st screen:
![1](https://user-images.githubusercontent.com/1388133/63716086-8c001a80-c81b-11e9-957a-335f3363d6fa.png)

Back of the document taken (in the camera screen):
![2](https://user-images.githubusercontent.com/1388133/63780697-ee5e2700-c8be-11e9-89e4-9f1a81234b33.png)

Back of the doc taken
![3](https://user-images.githubusercontent.com/1388133/63780719-f5853500-c8be-11e9-8010-25ad5ed22b74.png)

Permission note: 
![4](https://user-images.githubusercontent.com/1388133/63716129-9cb09080-c81b-11e9-83c4-7a9394d81974.png)

Error page: 
![5](https://user-images.githubusercontent.com/1388133/63716136-a0dcae00-c81b-11e9-8a16-7afcd5f721e5.png)

**Comment by stefaniacardenas** [comment]
Hi @rrigoni, 
Yes, it might be related to the fact that you are using an iframe to render the SDK. Are you using `https` in the iframe? Note that `getUserMedia` can only work on secure origin.
I've personally never tried to embed the SDK in an Android app using a webview before so I'm not sure how well they interact. Are you able to display errors from the console?
There might be other hints there.

**Comment by stefaniacardenas** [comment]
Hi @rrigoni,
>I'm guessing your sdk is using the camera in two different ways, because the camera works for taking document's pictures but fails to collect the live photo.

That's correct. The `document` steps uses the native camera mode. That means that when you click on "Take photo" you are using the camera app on your phone. In some browsers that might allow the user to select an image from their gallery if they want to.

The `face` step instead, embeds the camera inside the browser. The browser requests permissions to the user via `getUserMedia`, then takes a video or photo depending on the variant you've requested.

Some of our customers have strict requirements for which their users should not be allowed to upload images from the gallery, therefore we want to enforce the usage of browser embedded camera for selfie captures.

From a quick google search, it looks like other people had problems accessing cameras from a  webview. Please check out the answers within this [StackOverflow thread](https://stackoverflow.com/questions/30857229/i-want-to-use-the-getusermedia-in-android-lollipop-5-0-webview) as they might be helpful.
Also, here is an [example project](https://github.com/marcusbelcher/android-getUserMedia-test) that uses `getUserMedia` in a webview.

Please let me know if any of those solutions work.

**Comment by VidStaric** [comment]
Hi, I ran into this problem as well, similarly to @rrigoni case Onfido SDK was included in a larger widget as part of their KYC flow. 

The solution to this is to override WebChromeClient's `onShowFileChooser ` which is trigged by the `<input type="file" name="file" accept="image/*" capture>` and similar which the `document` step uses. 

```
 @Override
public boolean onShowFileChooser(WebView webView, ValueCallback<Uri[]> filePathCallback, FileChooserParams fileChooserParams) {
    //start the ACTION_IMAGE_CAPTURE intent and save the reference to filePathCallback
 }

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
     // call filePathCallback.onReceiveValue() with the provided file URI's
}
```

**Comment by stefaniacardenas** [comment]
Hi @VidStaric, thanks for suggesting a solution. Did you both manage to complete the integration? We don't currently support webview integrations officially, but feel free to share any insight about your integration experience or suggest any changes that might improve it.

**Comment by stefaniacardenas** [comment]
I will close this issue as we don't actively support the SDK when used in an iframe.

**Comment by wink** [comment]
+1 on this issue. We are seeing the same problem with Android users when running the Onfido SDK within another webview widget. Please support webviews.
