### ISSUE TITLE
Selfie taken but not uploaded

### ISSUE THREAD

**Issue by antoinelame** [onfido/onfido-sdk-ui#790]
# Description

We use Onfido to get `document` and `facial similarity` reports.

From the back-end of our application, we noticed that sometimes, no check is performed because we get this response from your API: 

> _You must provide a live photo to be able to proceed with this check_.

That's surprising because we force our users to upload a selfie and the check is only triggered by our back-end after the `onComplete` callback of the SDK.

I checked and indeed, I can see that the identity card pictures are uploaded and attached to the applicant ID, but there is no live photo.

We use fullstory, so I can replay the sessions of our users and also watch the requests sent by the browser. I can see that even if the users complete the whole KYC flow, only the request sending the identity card to your API (`POST https://api.onfido.com/v2/documents`) is sent. There is no request sending the selfie (`POST https://api.onfido.com/v2/live_photos`).

This bugs occurs for a minority of our users, but not insignificant.

Thanks for your help!

# Context
Version: `^5.2.1`

Configuration:
```
{
  token,
  containerId: 'onfido-mount',
  steps: [
    {
      type: 'document',
      options: {
        documentTypes: {
          passport: false,
          driving_licence: false,
          national_identity_card: true,
        },
      },
    },
    {
      type: 'face',
      options: {
        uploadFallback: false,
      },
    },
  ],
  onComplete: async (message, submessage) => {
     // we call our server to perform a check...
  },
}
```

**Comment by ramprasad-parajuli** [comment]
Hi, @antoinelame Thank you for your message. 
Could you please provide us with the applicant ID for which you experienced the error? Also, it would be helpful if you could provide us with a link to your implementation for us to replicate the issue from our end and investigate the issue further.
I look forward to hearing from you soon.
Thanks!!

**Comment by antoinelame** [comment]
Hello @ramprasad-parajuli,

Thank for your response.

Here are the last applicant IDs who faced this problem: `4402f94f-9654-4a72-bb30-bc9dfff1a48b`, `c128dade-7dd2-4567-ab7f-f94c19f8c485`, `d8283324-ad53-44e7-bf76-ce9233cfba5e`, `28121c2d-f332-464f-a6ed-33273c24d6ce`. We have around 15 cases per day.

I sent you by email the link of our staging environment so you can try and see our front-end code.

**Comment by antoinelame** [comment]
Hello @ramprasad-parajuli,

Thank for your response.

I sent you by email the last applicant IDs who faced this problem and the link of our staging environment so you can try and see our front-end code.

**Comment by stefaniacardenas** [comment]
Will close this issue as resolved via our internal tech support team.
