### ISSUE TITLE
Two events triggered on file upload in IE

### ISSUE THREAD

**Issue by stojaobradovic** [onfido/onfido-sdk-ui#803]
We use onfido UI components for the verification process in our application. In **IE 11** which is supported by Onfido, once the file gets uploaded, the console error appears. 

![1 PNG](https://user-images.githubusercontent.com/38106798/65769536-11852c00-e134-11e9-9c6f-0a0404b363fc.png)

We believe that the error is occurring in `onfido.min.js`.

In `handleChange` function, the line: `r.input && r.props.onChange(r.input.files[0]), e.currentTarget.value = ""` is being executed twice when the file is uploaded. We believe that the second event fired is the cause of the mentioned error.
In other browsers (Chrome, Firefox, Edge) on file upload, the mentioned line is executed only once.

Also, it is possible that this second triggered event is causing an error in one of the scripts for tracking since multiple `Script error`s are appearing and cluttering our Raygun channel. Logs for this `Script error`s have a call to _https://www.woopra.com/track/ping_ in their stacktrace.

We noticed errors appearing in all versions we used (2.7.0 and later).

Steps to reproduce: 

- begin verification process
- go to _Verify your identity_ overlay
- chose any of the options for document types
- click on _Upload file_ button
- chose document
- click _Select_ button

Thank you for your help!

**Comment by stefaniacardenas** [comment]
Hi @stojaobradovic, thank you for reporting the issue. I was able to reproduce it on IE11 and I have added a ticket in our backlog to fix it. I will let you know when a fix will go live. Many thanks

**Comment by kopijunkie** [comment]
Hi @stojaobradovic 
We've released [5.8.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.8.0) recently which includes the PR that fixes the issue you reported. 
I'll close this for now, but feel free to re-open if you are still facing this issue.
