### ISSUE TITLE
Custom scheme as referrer

### ISSUE THREAD

**Issue by RSchumacher13** [onfido/onfido-sdk-ui#808]
Would you consider allowing custom schemes as referrers for your web SDK? When using the Web SDK in an ionic webapp, the ionic:// custom scheme is needed.

Something like:
```
curl https://api.onfido.com/v2/sdk_token \
  -H 'Authorization: Token token=api_sandbox.oiehwehrewhtjkjehtkjwht' \
  -F 'applicant_id=roerueyrouiweuyruioyeruyweiru' \
  -F 'referrer=ionic://localhost/*'
```

**Comment by ramprasad-parajuli** [comment]
@RSchumacher13 We will be looking into your request to consider allowing customer schemes as Referrers in our Web SDK in the future.

**Comment by MatthewPringle** [comment]
Can we please get this integrated into the SDK, Cordova I believe doesnt send a referrer and this screws up integration.

**Comment by stefaniacardenas** [comment]
I will close this issue as we are not currently supporting Cordova. We have a ticket in our backlog to explore the possibility of introducing WebView support.
