### ISSUE TITLE
Implement additional callbacks

### ISSUE THREAD

**Issue by akrasnoshchok** [onfido/onfido-sdk-ui#829]
Would be great if you could implement some additional callbacks, like:
- onDocumentUploaded
- onFaceUploaded

So we can submit applicant checks in advance to save some time.

**Comment by ctrlaltdylan** [comment]
I was just about to create this same issue. We would like to implement additional callbacks so we can enrich our tracking on Onfido UI related events.

Would the Onfido team consider this in the roadmap or be open to a PR request?

**Comment by stefaniacardenas** [comment]
Hi, thanks for raising this issue. I will discuss this feature with the team and get back to you. Many thanks.

**Comment by stefaniacardenas** [comment]
Hi, this feature has been added in version 5.8.0. You can now track the user's journey through the verification process via a dispatched event. For more details, please check out [this part of the documentation](https://github.com/onfido/onfido-sdk-ui#user-analytics). I will now close this issue.
