### ISSUE TITLE
Data object passed by onComplete will overwrite document key

### ISSUE THREAD

**Issue by ravinpatel** [onfido/onfido-sdk-ui#854]
Hi,
When using both the `passport` and `poa` steps, the latter will overwrite the first in the data object passed from the onComplete callback. it will be great to get both back so I can use both their IDs. Currently, I only get the credit card statement back not the passport.

my init config:
```
init({
      token: 'token',
      containerId: 'onfido-mount',
      onComplete: (data) => {
        console.log('everything is complete', data)
      },
      steps: [
        {
          type: 'welcome',
          options: {
            title: 'Welcome to GetGround',
            descriptions: ['please follow instructions to submit your documents', 'it will only take a couple minutes']
          }
        },
        'document',
        'poa',
        'face',
        'complete'
      ]
    })
```

and im using : "onfido-sdk-ui": "^5.5.0",

**Comment by kopijunkie** [comment]
Hi @ravinpatel 

The POA step cannot be used in conjunction with the ID document (`passport` in your case) step as part of a single SDK flow. You would need to treat the POA and ID document as separate flows by tearing down the first then initialising the SDK with the other document that you want submitted.

Let me know if you need any further assistance with this.

**Comment by ravinpatel** [comment]
Hi,

Thanks for your quick reply and your advice.
