### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by ravinpatel** [onfido/onfido-sdk-ui#859]
Hi,

I am using Gatsby in my project which renders in the pipeline without the DOM. When I run build I come across this error `navigator is not defined` as a window is needed to use navigator. It is only when I import `init` method into my container that it breaks the build. 

my import:
`import { init } from 'onfido-sdk-ui'`

Thanks in advance!

**Comment by ravinpatel** [comment]
anyone having the same issue this is my work around:

```
componentDidMount() {
if(typeof window !== 'undefined') {
          import('onfido-sdk-ui').then(({init}) => {
            init({
              token: token,
              containerId: 'onfido-mount',
              onComplete: () => {},
              steps: [
                {
                  type: 'welcome',
                  options: {
                    title: 'Welcome',
                },
                'document',
                'poa',
                'face',
                'complete'
              ]
            })
          })
        }
   }
```

**Comment by stefaniacardenas** [comment]
Hi @ravinpatel, I'm glad you found a solution. Thank you so much for sharing your findings. I will create a ticket to add a section in the documentation to support developers integrating the SDK in Gatsby.js or Next.js, where this issue is present. I will close this issue now. Cheers.

**Comment by BenCrinion-IW** [comment]
Hi, 

We're having the same issue and React is deprecating the lifecycle events mentioned in the workaround. I couldn't find any documentation around Gatsby.js or Next.js in this repo or the developer docs on the Onfido website. Is there a better workaround taking the new React lifecycle into account? 

Thanks
Ben
