### ISSUE TITLE
Ability to force video variant for face capture step

### ISSUE THREAD

**Issue by Wabantti** [onfido/onfido-sdk-ui#860]
When trying to use the video variant for facial similarity checks, it can fall back to the standard variant if the SDK is unable to record video as is stated in the documentation.

Is there a way to "force" video variant so that if it is not supported the user can not complete the flow and instead gets "not supported" message perhaps with instructions on how to get it working. Currently we are only able to see if the user was pushed to standard variant using the `onComplete` callback which means that user has already completed the entire flow for nothing.

**Comment by Gorbyy** [comment]
Hi @Wabantti 

Unfortunately it is not possible at the moment to force the video variant and not fallback to the standard variant. We are considering this as a future feature but at the moment we cannot provide ETAs for when it will be implemented.
We have one suggestion though: you could try to see if MediaRecorder API (https://caniuse.com/#feat=mediarecorder) is supported by a particular browser, and implement your own logic and user messaging before entering the SDK flow if video recording is not supported.

Best regards

**Comment by Wabantti** [comment]
Thank you for you response @Gorbyy 

We are in fact already doing what you suggest. We check MediaRecorder API availability and also some specific functions in case of incomplete support (for example safari has MediaRecorder as an experimental feature but video does still not work). This issue can still happen after this check if the user starts the process on supported browser but later switches to the mobile flow where the mobile device is unable to take video.

But it is good to hear this is something you are considering.
