### ISSUE TITLE
Upload selfie instead of using camera

### ISSUE THREAD

**Issue by lhew** [onfido/onfido-sdk-ui#863]
Hi all, 

I'm building an app that opens an In-app browser. But since `WKWebkit` doesn't support `getUserMedia`, it's not possible to perform the `face` step inside the app. Is there any way to upload a selfie instead of send the user outside the app?

**Comment by stefaniacardenas** [comment]
Hi @lhew, we don't currently support the SDK within webviews. One of our clients posted a solution for a similar problem in [this thread ](https://github.com/onfido/onfido-sdk-ui/issues/774#issuecomment-537375809). Not sure if your issue can leverage the same solution but it could point you in the right direction. I will discuss with the team the possibility of introducing webview support but for now, I cannot provide much help I'm afraid.

**Comment by stefaniacardenas** [comment]
Hi @lhew, any update on this? Did you manage to use the answer in the other thread to get unblocked? I will close this issue for now but it would be good to know how you went about solving this.
