### ISSUE TITLE
Add an ability to disable external tracking software

### ISSUE THREAD

**Issue by desfero** [onfido/onfido-sdk-ui#884]
**Background**
Setting restrictive CSP policies is a common pattern in today's software industry and by integrating external sdk into frontend i expect to add as minimum as possible new rules to be always on the safe side.

At the moment there are no options to disable external tracking (woopra.com) therefore we got a ton of logs in the console related to CSP blocking a resource:

![image](https://user-images.githubusercontent.com/7031578/70795232-a399e980-1d9f-11ea-9779-2b4da7961c53.png)

Also if possible would be good to analyze the codebase and move all external url calls under `onfido.com` (for e.g. flags should not be dependent on the github.io (https://lipis.github.io/flag-icon-css/flags)

Thanks 😊

**Comment by stefaniacardenas** [comment]
Hi @desfero, thanks for reporting this issue. Disabling tracking is on our roadmap. I will let you know when this feature is released. 
>Also if possible would be good to analyze the codebase and move all external url calls under onfido.com (for e.g. flags should not be dependent on the github.io (https://lipis.github.io/flag-icon-css/flags)

This is a good point. I will discuss it with the team.

Many thanks

**Comment by kopijunkie** [comment]
Hi @desfero 
FYI we have released version 5.8.0 recently which adds the option to disabled analytics with the `disableAnalytics` option when initialising the SDK.

**Comment by desfero** [comment]
@kopijunkie thanks a lot, closing the issue.
