### ISSUE TITLE
Video recording not supported in Firefox 71

### ISSUE THREAD

**Issue by pablobm** [onfido/onfido-sdk-ui#891]
The `video` variant of the `face` step doesn't work on Firefox 71. I can confirm this problem doesn't exist in Firefox 70.

Reproduction:

1. Use Firefox 71 (current version at the time of writing).
2. Visit this JSFiddle: https://jsfiddle.net/real_ate/xvy8aqwt/1/ 
3. Go through the flow by manually updating documents (instead of using the SMS/smartphone flow).
4. At the video step, give the browser permission to record video and audio.
5. Press the record button on the Onfido widget.

At this point, I get the "video problems?" alert on the widget:

![camera-problems-dialog](https://user-images.githubusercontent.com/36066/71892383-ac809f80-3140-11ea-8c8d-146269c63324.png)

If I check the browser console, I see the following messages and errors:

```
onfido_sdk_version 5.6.0
video/webm;codecs=vp9 is not Supported
NotSupportedError: An audio track cannot be recorded: video/webm;codecs=vp8 indicates an unsupported codec
```

![console-errors](https://user-images.githubusercontent.com/36066/71892402-b99d8e80-3140-11ea-8ab3-3ba60bc250d1.png)

This problem is exacerbated in version 5.5.0 of the SDK (which we use) as its interface emphasizes the mobile flow much less, and more users are likely to go through the upload+record flow on desktop.

**Comment by stefaniacardenas** [comment]
Hi @pablobm, thanks for reporting this issue. I was able to reproduce it. I will add a ticket to our backlog and post any updates regarding the state of this issue here.

**Comment by evmorov** [comment]
For FF >= 71 you should use 'video/webm;codecs=vp8,opus'.

**Comment by pablobm** [comment]
Something else worth mentioning here is that this failure doesn't trigger the `onError` handler. This is actually documented (the readme lists which errors are caught), but might be unexpected to some.

**Comment by afkatja** [comment]
> Something else worth mentioning here is that this failure doesn't trigger the `onError` handler. This is actually documented (the readme lists which errors are caught), but might be unexpected to some.

Could you point us where in the documentation we can find this and, more importantly, @stefaniacardenas how do we handle the error until it's fixed?

**Comment by pablobm** [comment]
Sure, I'm referring to this bit of the readme:

> - **`onError {Function} optional`**
> 
>     Callback that fires when one an error occurs. The callback returns the following errors types:
>     - `exception`
>       This type will be returned for the following errors:
>       - Timeout and server errors
>       - Authorization
>       - Invalid token

**Comment by ramprasad-parajuli** [comment]
@pablobm The issue has been fixed in the new version of the web SDK we made today - https://github.com/onfido/onfido-sdk-ui/blob/master/CHANGELOG.md#580---2020-03-19.
