### ISSUE TITLE
http://www.woopra.com

### ISSUE THREAD

**Issue by MatthewPringle** [onfido/onfido-sdk-ui#901]
Lets either remove woopra or at least get a version of woopra that connects over HTTPS

I am tired of getting these messages, the app works over HTTPS and as such I cannot allow http in the CSP and so it will always just generate a ton of errors

{
  "csp-report": {
    "document-uri": "http://localhost:4200/status",
    "referrer": "http://localhost:4200/status",
    "effective-directive": "script-src",
    "blocked-uri": "http://www.woopra.com",
  }
}

**Comment by MatthewPringle** [comment]
In fact I would think it would be better if we could disable your tracking in the SDK.

This should be something the client should opt into rather than you just tracking everyone in the background.

**Comment by Gorbyy** [comment]
Hi @MatthewPringle 

Thank you for your feedback! That is something we have on our roadmap. We previously discussed this in here - https://github.com/onfido/onfido-sdk-ui/issues/884 - and we will let you know when this feature is released.

Cheers
