### ISSUE TITLE
The Share Link screen defaults to QR code. How do I make it default to phone number? 

### ISSUE THREAD

**Issue by zohaib10** [onfido/onfido-sdk-ui#903]
### Version info:
- Onfido SDK :- latest

### Integration configuration: 
Followed the web sdk doc. Initialized the script using the init function with options of the steps needed.

**Comment by stefaniacardenas** [comment]
Hi @zohaib10, thank you for flagging this issue. Currently, there isn't a way of using the SMS feature as default. Another customer has requested a similar behaviour in this PR #900. We are in the process of evaluating this change within the team and once we have agreed on the actions to take, I will follow up on this ticket. Many thanks

**Comment by stefaniacardenas** [comment]
Hi @zohaib10, we are evaluating this change as a possible mid-term feature, as there are a few business implications that we need to consider before introducing this change. I will close this issue for now but you can still discuss your use case with your account manager if you consider this a critical feature.
