### ISSUE TITLE
Safari Issue - Allow camera access - Enable Camera button alignment

### ISSUE THREAD

**Issue by benjam23** [onfido/onfido-sdk-ui#905]
We have found a bug when using Safari on a mobile (iPhone) and via desktop (iMac & MacBook) carrying out the facial recognition check. On the 'Allow camera access' prompt, the 'Enable Camera' button appears far too low down the page - not aligned correctly. This problem does not appear on Chrome which is the only other browser we tested.

### What was the expected behaviour?

Allow camera access page - 'Enable camera' button should appear under blue camera with green tick icon.

### What happened instead?

The 'Enable camera' button was far down the page, not aligned correctly.

### Version info:

- Onfido SDK Latest
- OS Latest iOS & Mac OS
- Safari only
- iPhone 11 & iMac Pro (latest) & MacBook Air (latest)

### Integration configuration:

No customisations have been made to this code apart from basic colour changes. Although, it would be nice to know where to find the CSS for this stage?

### Steps to reproduce:

Using an iPhone or Mac follow the normal process.
<img width="529" alt="Screenshot 2020-01-30 at 19 37 00" src="https://user-images.githubusercontent.com/4377833/73483771-ef2c4500-4397-11ea-8244-11c49a0ea63a.png">
<img width="529" alt="Screenshot 2020-01-30 at 19 37 10" src="https://user-images.githubusercontent.com/4377833/73483781-f5222600-4397-11ea-96ce-0f9fa009b194.png">

**Comment by benjam23** [comment]
<img width="383" alt="Screenshot 2020-01-31 at 09 42 22 - censor 2" src="https://user-images.githubusercontent.com/4377833/73529367-7f0cd600-440e-11ea-91dd-ac07349c4e27.png">
<img width="383" alt="Screenshot 2020-01-31 at 09 42 30 censor 1" src="https://user-images.githubusercontent.com/4377833/73529399-88963e00-440e-11ea-8496-081322a1f3f6.png">

Issue on Safari latest version and latest iOS

**Comment by Gorbyy** [comment]
Hi @benjam23 

I believe we are also discussing this via email, so please allow me to close this issue and maintain communications over the email thread.

Cheers
