### ISSUE TITLE
Unsupported Browser / Video

### ISSUE THREAD

**Issue by MatthewPringle** [onfido/onfido-sdk-ui#914]
### What was the expected behaviour?

The browser should be detected correctly

### What happened instead?

The browser is not detected correctly and a misleading message is shown

### Version info:

- 5.7.0
- iOS 13
- Cordova InAppBrowser
- iPhone X
- Node
- Cordova / Ember

### Info:

Our client was told that Onfido would work with Cordova but having installed the JS UI SDK we found that the API would not talk to the device because of the referrer field not being set when using Cordova.

We then tried using InAppBrowser to display the SDK hosted on a server, in a webview. This works fine and we can access the camera, upload images etc...

But! When enabling video the SDK must do browser checks, and it seems that even though I am using iOS 13 on an iPhone X using a webview, the SDK is detecting an out of date version of Safari.

Is the browser detection wrong?

![Screenshot 2020-02-06 at 10 57 18](https://user-images.githubusercontent.com/368800/73951888-2a79c700-48f6-11ea-81dd-eceba3f7370d.png)

**Comment by stefaniacardenas** [comment]
Hi @MatthewPringle,
>Our client was told that Onfido would work with Cordova 

The Web SDK has not been tested to work with Cordova. Maybe they were referring to our mobile SDKs.
A way to get around this issue is removing the `uploadFallback: false` option or setting it to `true`, although keep in mind that this feature might allow some users to select a file from their gallery.

I hope that helps.

**Comment by MatthewPringle** [comment]
The client wants video so falling back to using the camera for images is not an option.

Can you point me to where in the code you perform the check to device if to show the video capture option / the error screen shown above.

**Comment by stefaniacardenas** [comment]
Hi @MatthewPringle,
The error is returned [here](https://github.com/onfido/onfido-sdk-ui/blob/bbdd8293ca0db70d4698e664f0b4332aeb55dee4/src/components/Capture/Face.js#L127)
and it uses this [function](https://github.com/onfido/onfido-sdk-ui/blob/master/src/components/utils/detectMobileOS.js).
Do you have repo/demo we could potentially use to try to reproduce the issue?
For now, I will create a ticket to investigate Cordova support and will update you on the outcome.

**Comment by stefaniacardenas** [comment]
Hi @MatthewPringle, are you still having this issue?

**Comment by stefaniacardenas** [comment]
Closing this issue as we don't support the SDK inside Cordova/webview.
