### ISSUE TITLE
US Visa or US residency card document types

### ISSUE THREAD

**Issue by olegakbarov** [onfido/onfido-sdk-ui#917]
How to capture US Visa or US residency card using SDK?

There're a [list of documents](https://onfido.com/supported-documents/) you accept, but SDK has only 
three options: https://github.com/onfido/onfido-sdk-ui/blob/c594c3d35bd4deeb17cf2ddeb09c89b9e8d9b60f/src/components/DocumentSelector/documentTypes.js#L16

**Comment by ramprasad-parajuli** [comment]
@olegakbarov A user could choose a passport as document_type for US Visa, and national_identity_card for US Residency card. 
Please be aware that if a user chooses Driver's License and uploads a US Visa, Onfido will classify the document as a US Visa and provide results accordingly.

**Comment by stefaniacardenas** [comment]
Hi @olegakbarov, we do not currently capture US Visa or US Residency via the SDK. We are considering adding additional document types to the Web SDK in the next quarter. I will close this issue now, I would suggest enabling feeds on our release page so you can receive a notification when a new feature goes live.

**Comment by olegakbarov** [comment]
Worth updating your docs.
