### ISSUE TITLE
Link to upload document emits a 'submit' event

### ISSUE THREAD

**Issue by pablobm** [onfido/onfido-sdk-ui#923]
### What was the expected behaviour?

I expected the component not to emit DOM events out of its own boundaries.

### What happened instead?

When clicking to upload a document (as opposed to starting a cross-device flow), a `submit` event is emitted out of the component.

This broke our flow, as we are presenting the Onfido UI inside of a `<form>` element.

### Version info:

- 5.7.0
- macOS 10.15.3 (19D76)
- Chrome 79.0.3945.130 (Official Build) (64-bit)
- Device MacBook Pro (Retina, 13-inch, Mid 2014)

### Steps to reproduce:

Reproduction at https://jsfiddle.net/pablobm/o20zutq5/7/ This is a variant of [the official demo](https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/master/demo/fiddle/), with just the HTML changed.

1. Click button "Verify Identity".
2. Select any option. Eg: "Passport".
3. Click link "or upload photo – no scans or photocopies".
4. Select a file on the file picker.
5. I get the "form was submitted" (part of my reproduction example), indicating that a `submit` event was emitted.

**Comment by stefaniacardenas** [comment]
Hi @pablobm, thanks for reporting this issue and for the example. It looks like a bug on our side. I will discuss prioritisation with the team and post any updates here.

**Comment by stefaniacardenas** [comment]
Hi @pablobm, this issue has been fixed in version [5.8.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.8.0). I will close this issue now, but feel free to reopen or comment if you have any problem.
