### ISSUE TITLE
iPad Detection Broken

### ISSUE THREAD

**Issue by MatthewPringle** [onfido/onfido-sdk-ui#928]
### What was the expected behaviour?

Detect the user is on an iPad

### What happened instead?

You are using old code which 

### Version info:

- Onfido SDK 5.7.0
- OS iOS
- Browser Safari
- Device iPad
- Node
- Framework or relevant dependencies (if applicable)

Your code here is looking for iPad but Apple no longer provides iPad in the user agent and so you will need to check for it in other ways.

https://github.com/onfido/onfido-sdk-ui/blob/master/src/components/utils/detectMobileOS.js

Some check like this..

https://qiita.com/mtdune/items/97abb9c0bd926d4c8a13

**Comment by Lechus** [comment]
any update?

**Comment by kopijunkie** [comment]
Hi @MatthewPringle,
 
Thank you for highlighting this issue. We happened to have identified the bug also and plan to release it as part of our next release. I will give you an update when it has gone out.

**Comment by KJSR1409** [comment]
@kopijunkie when do we expect for the next release cycle?

**Comment by ramprasad-parajuli** [comment]
@MatthewPringle @KJSR1409  The issue has been fixed in the new version of the web SDK we released today - https://github.com/onfido/onfido-sdk-ui/blob/master/CHANGELOG.md#580---2020-03-19.
