### ISSUE TITLE
Photo button remains disabled if clicked too soon

### ISSUE THREAD

**Issue by mradbourne** [onfido/onfido-sdk-ui#935]
### What was the expected behaviour?

The 'take photo' button on the 'Take a selfie' camera page is always operational when the camera preview has initialised.

### What happened instead?
If the 'take photo' button is pressed before the camera has initialised, the button is put into a disabled state. Once the camera has initialized, the button state remains disabled.

### Version info:
- Onfido SDK: 5.7.1
- OS: MacOS 10.15.2
- Browser:  Chrome 80.0.3987.132, Firefox 74.0b9
- Device: Macbook Pro
- Node: v13.7.0
- Framework or relevant dependencies (if applicable): N/A

### Integration configuration:
Not relevant. Issues is present in the example JSFiddle provided in the README.

#### Scenario 1 - Camera permission not yet allowed or blocked
- Navigate to the 'Take a selfie' camera page
- Wait for the browser's 'Allow camera access' prompt to appear
- Click the 'take photo' button
- Allow camera access
- Click the 'take photo' button, which does not respond

#### Scenario 2 - Camera permission already allowed
- Navigate to the 'Take a selfie' camera page
- Immediately click the 'take photo' button before the camera preview appears
- Wait for the camera preview to appear
- Click the 'take photo' button, which does not respond

### Demo:
https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/master/demo/fiddle/

**Comment by ramprasad-parajuli** [comment]
@mradbourne Thank you for flagging the issue. We will reach out to you once we have more information regarding the next steps.

**Comment by stefaniacardenas** [comment]
This issue was fixed in version 5.9.0
