### ISSUE TITLE
Dubai Users do not receive a sms link to upload from their mobile

### ISSUE THREAD

**Issue by ravinpatel** [onfido/onfido-sdk-ui#937]
Hi,

Thanks in Advance

### What was the expected behaviour?
User in Dubai clicks on Link to use their mobile to upload instead. The SMS is sent to the user's phone and they are able to take a picture on their mobile to then be uploaded on their other device.

### What happened instead?

User clicks on Link and there are no changes to the client also no SMS is sent to their phone.

We also received this error in our Sentry logs: 
`null is not an object (evaluating 'r.linkText.focus')`

### Version info:

- Onfido SDK: 5.5.0
- OS: OSX 10.15
- Browser: Safari
- Device: IPad
- Node: 11.13.0
- Framework or relevant dependencies (if applicable): React

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

```
init({
              token: res.data.onfido_token,
              containerId: 'onfido-mount',
              onComplete: () => {
                confirmOnfido(userID).then((res) => {
                  res.status === 200 && navigate('/onboarding')
                })
              },
              steps: [
                {
                  type: 'welcome',
                  options: {
                    title: 'Identity Verification',
                    descriptions: ['Please follow instructions to submit your documents,', 'it will only take a couple minutes']
                  }
                },
                {
                  type: 'document',
                  options: {
                    documentTypes: {
                      passport: true,
                      driving_licence: false,
                      national_identity_card: false
                    }
                  }
                },
                {
                  type: 'poa',
                  options: {
                    country: 'SGP'
                  }
                },
                'face',
                'complete'
              ]
            })
```

### Steps to reproduce:

User:
- Uploads his document
- Uploads his POA
- Attempts to take picture of face.
- Shows blue banner asking to use link to use mobile instead.

**Comment by ramprasad-parajuli** [comment]
@ravinpatel When you mentioned above that "User clicks on Link and there are no changes to the client", did the user see anything on the screen or were they able to click on the link and there was no change?

**Comment by stefaniacardenas** [comment]
Hi, unfortunately `poa` cannot be used in conjunction with the `document` and `face` steps. As quoted in the documentation
>The Proof of Address document capture is currently a BETA feature, and it cannot be used in conjunction with the document and face steps as part of a single SDK flow.

You can initialise the SDK with the `poa` step only and initialise it again with the `document` and `face` steps, once you receive the onComplete callback.
