### ISSUE TITLE
Edge 18 "TypeError: Invalid argument" when selecting the document type

### ISSUE THREAD

**Issue by tlaak** [onfido/onfido-sdk-ui#950]
### What was the expected behaviour?

Clicking Passport or Driving licence buttons on the "Select the type of document you would like to upload" step should lead to the next step where user can take a new photo or upload a photo of their id.

### What happened instead?

An error happens with the following output in the console (we have Sentry handling uncaught exceptions but this doesn't really contain useful information):

```
[SENTRY] TypeError: Invalid argument
eval code (2371) (1,352322)

SCRIPT5022: SCRIPT5022: The error you provided does not contain a stack trace.
[pagename] (1,356154)
```

In local development version, an error page shows up containing the following information:

```
Error
The error you provided does not contain a stack trace.

Call Stack
 S
  undefined:1:356154
 V
  undefined:1:360468
 Anonymous function
  undefined:1:360908
 Anonymous function
  undefined:1:361265
 a
  undefined:1:351686
```

### Version info:

- Onfido SDK: 5.7.1
- OS: Windows 10 running in a VM
- Browser: Edge 18
- Node: 12.12.0
- Framework or relevant dependencies (if applicable): React 16.13.0, TypeScript 3.8.3

### Code snippet:

We don't have customisations for other than error handling, but none of those are triggered. 

```
steps: [
          {
            type: 'document',
            options: {
              documentTypes: {
                passport: true,
                driving_licence: true,
                national_identity_card: false,
              },
            },
          },
          {
            type: 'face',
            options: {
              requestedVariant: 'video',
              uploadFallback: false,
            },
          },
          'complete',
        ],
```

### Demo:

Unfortunately it's not possible to share a public demo.

It works as expected in major browsers but breaks on Edge 18.

**Comment by kopijunkie** [comment]
Hi @tlaak 

I've tried to reproduce the error you're seeing with Edge 18 on Windows 10 on a VM by modifying our [JSfiddle](https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/master/demo/fiddle/) demo with the configuration you've provided but was able to complete the flow as expected. 

Would it be possible to share the full configuration that you are using to initialise the SDK so that I can try to look into it further?

**Comment by tlaak** [comment]
Here's the content of a click handler which launches the Onfido flow. Obviously it is hard to say whether the compiled JS output contains something not supported by Edge. We are using TypeScript with Babel and Webpack.

```
const launchOnfidoModal = async () => {
setOnfidoActive(true);
    try {
      const { data } = await createJwt({
        first_name: firstName,
        last_name: lastName,
        smsNumber: mobilePhone,
        email,
      });

      const onfido = Onfido.init({
        token: data.token,
        containerId: 'onfido-mount',
        isModalOpen: true,
        useModal: true,
        steps: [
          {
            type: 'document',
            options: {
              documentTypes: {
                passport: true,
                driving_licence: true,
                national_identity_card: false,
              },
            },
          },
          {
            type: 'face',
            options: {
              requestedVariant: 'video',
              uploadFallback: false,
            },
          },
          'complete',
        ],
        onModalRequestClose: () => {
          onfido.setOptions({ isModalOpen: false });
          setOnfidoActive(false);
        },
        onComplete: async (onfidoUploadResponse: OnfidoUploadResponse) => {
          customLogger({
            message: '...',
            metadata: onfidoUploadResponse,
          });
          onfido.setOptions({ isModalOpen: false });
          setOnfidoActive(false);
          checkApplicant(onfidoUploadResponse);
        },
        onError: (error: OnfidoError) => {
          customLogger({
            message: `...`,
            metadata: error,
          });
          history.push('/error');
        },
      });
    } catch (error) {
      customLogger({
        message: `...`,
        metadata: error.response,
      });
      history.push('/error');
    }
};
```

**Comment by tlaak** [comment]
Mind you that the [JS Fiddle demo](https://jsfiddle.net/gh/get/library/pure/onfido/onfido-sdk-ui/tree/master/demo/fiddle/) doesn't work in my VM either. It doesn't crash in the same way, but after choosing the document type I don't get any content.

Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763

<img width="1415" alt="Screenshot 2020-03-26 at 15 42 21" src="https://user-images.githubusercontent.com/1674055/77666166-8072fe80-6f78-11ea-85b1-41039b1761ae.png">

**Comment by kopijunkie** [comment]
@tlaak Sorry for the delay in replying to you. What VM were you using? I was using Parallels Desktop when trying to reproduce earlier. Have also checked via Browserstack today and it renders fine for EdgeHTML18.

**Comment by tlaak** [comment]
@kopijunkie No worries!

It's also Parallels Desktop 15.1.2 and Windows 10 with latest updates applied.

Our QA could not replicate this in the staging environment so it might as well be caused by something in my local VM environment.

**Comment by kopijunkie** [comment]
@tlaak Thanks for the update. I'll close this ticket then.
