### ISSUE TITLE
Unable to upload / capture documents when completing the flow from mobile browser. 

### ISSUE THREAD

**Issue by jordantroberts** [onfido/onfido-sdk-ui#956]
### What was the expected behaviour?

Expected to be able to upload / capture documents and complete the flow on a mobile browser. 

### What happened instead?

When starting the flow from the mobile browser (both Chrome and Safari), I am able to successfully select which document I'd like to upload. After that, there is no option to either upload a picture or take a picture. I also cannot scroll down. This is a screenshot: 

![Image from iOS](https://user-images.githubusercontent.com/46907218/77157208-d0ddee00-6a98-11ea-9979-d07e4e61d60f.jpg) 

### Version info:

- Onfido SDK 5.6.0
- Browser - Safari 13
- Device - iPhone 11 

### Integration configuration:
```
 steps: [{
              type: 'document',
              options: {
                 forceCrossDevice: true
              }
            },
             'face',
           ],
```

### Steps to reproduce:

-  Begin verification process on mobile browser
-  Choose any of the options for document types 

Thanks for your help :)

**Comment by ramprasad-parajuli** [comment]
@jordantroberts I tried to test the web SDK (test app) on an iPhone on safari 13 and I was able to complete the workflow successfully.
Could you please provide a link to your integration/implementation here or email us at api@onfido.com, so that we could test it and try to reproduce the error?

**Comment by jordantroberts** [comment]
Thanks for replying @ramprasad-parajuli - was your zoom set at 100% for your iPhone on Safari 13 for it to work?

**Comment by ramprasad-parajuli** [comment]
Hi @jordantroberts, I tried to reproduce it on an iPhone X and iPhone 8 on safari 13.

**Comment by stefaniacardenas** [comment]
Hi @jordantroberts, I was also unable to reproduce this issue. Is there any chance you could provide a JSFiddle example or a private link to your implementation? I suspect the issue might be due to the styling on the parent tag. Many thanks

**Comment by jordantroberts** [comment]
Hi @stefaniacardenas and @ramprasad-parajuli - sorry for my delayed reply to this, I was waiting to see whether one of my colleagues was able to fix this. It turns out it was indeed an issue with the styling. Sorry for this, I will close the issue, and thank you for your time.
