### ISSUE TITLE
Face step uploadFallback:true not working as expected

### ISSUE THREAD

**Issue by ctrlaltdylan** [onfido/onfido-sdk-ui#959]
### What was the expected behaviour?

We have an internal dashboard for handling cases when users are having issues completing ID verification checks via the Onfido UI SDK hosted on our main site.

The will send us photos of their documents and selfies. This internal dashboard allows our Trust & Security team to upload checks on behalf of these users that are experiencing problems with the SDK.

We utilize the `uploadFallback` option in order for these Trust & Security agents to upload the photos on behalf of our customers.

However, our agents are not able to use the latest Onfido SDK because the face step doesn't respect the `uploadFallback: true` option

### What happened instead?

As a Trust & Security team member
Given the `uploadFallback` option is set to `true` on both the face & document steps
When I start an ID check and upload document photos
I expect to be able to upload face photos

The screen we get instead after disabling camera access:

![Screen Shot 2020-03-25 at 12 26 26 PM](https://user-images.githubusercontent.com/2694734/77561776-880da700-6e95-11ea-9978-7a23b9b60800.png)

Please detail what the actual behaviour was

### Version info:

- Onfido SDK - 5.7.1
- OS - Mac
- Browser - Chrome
- Device - Macbook Pro

### Integration configuration:

```
export default function wizardOptions(user) {
  return {
    language: {
      language: 'en',
      locale: 'en',
      phrases: {
        welcome: {
          next_button: 'Next',
        },
        capture: {
          driving_licence: {
            front: {
              instructions:
                'Upload front of license from your computer. Please use a .jpg, .jpeg, or .png file.',
            },
            back: {
              instructions:
                'Upload back of license from your computer. Please use a .jpg, .jpeg, or .png file.',
            },
          },
          passport: {
            front: {
              instructions:
                'Upload passport photo page from your computer. Please use a .jpg, .jpeg or .png file.',
            },
          },
          face: {
            title:
              'Please take a picture showing your face. For the best results, remove anything that might cover your face such as sunglasses or hats.',
            instructions:
              'Please take a picture showing your face. For the best results, remove anything that might cover your face such as sunglasses or hats.',
          },
        },
        confirm: {
          face: {
            standard: {
              title: 'Check your photo',
              message:
                'Make sure your photo clearly shows your face without anything covering it such as sunglasses or a hat.',
            },
          },
        },
      },
      mobilePhrases: {
        'capture.face.instructions':
          'Please take a picture showing your face. For the best results, remove anything that might cover your face such as sunglasses or hats.',
        'capture.driving_licence.front.instructions':
          "Please take a picture of the front of your driver's license. Be sure the picture is clear and glare free for the best results.",
        'capture.driving_licence.back.instructions':
          "Please take a picture of the back of your driver's license. Be sure the picture is clear and glare free for the best results.",
        'capture.passport.instructions':
          'Please take a picture of your passport. Be sure the picture is clear and glare free for the best results.',
      },
    },
    smsNumberCountryCode: 'US',
    steps: [
      {
        type: 'welcome',
        options: {
          title: `Manually Submit ID Verification on behalf of ${user.full_name}`,
          descriptions: [
            'You can submit the customer\'s photos of their ID document and selfie here for them.',
            'This tool should be used when the customer is unable to submit these documents on their own',
            'It will accept Drivers Licenses, Passports and National ID Cards'
          ],
        },
      },
      {
        type: 'document',
        options: {
          uploadFallback: true,
          initialCrossDeviceDeliveryOption: 'sms',
          documentTypes: {
            passport: true,
            driving_licence: true,
            national_identity_card: true,
          },
        },
      },
      {
        type: 'face',
        options: {
          requestedVariant: 'standard',
          uploadFallback: true,
        },
      },
    ],
  };
}

```

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan, by default the SDK will always try to use the camera if present. The `uploadFallback` option is `true` by default, so adding that configuration for the document and face step won't change the default behaviour of the SDK. We only show the uploader screen if the device has no camera or the camera does not work. I hope this helps

**Comment by ctrlaltdylan** [comment]
Before today we were able to upload photos via a normal file upload
regardless of the camera settings on our MacBooks.

We need to be able to submit checks on behalf of users, this could be an
API change I'm not certain because we tried both the 5.7.1 and the 3.1.0
versions of the UI SDK with the same results.

**Comment by stefaniacardenas** [comment]
Which version were you using before? The latest versions of SDK are designed in a way that enforce submitting a live photo, not a photo taken at another time, as this can lead to fraud attempts.
Have you considered calling [Onfido API ](https://documentation.onfido.com/#upload-live-photo) directly? The agents could use Postman which has a nice UI to upload the photos.
Additionally, you could also use the Onfido dashboard where you can just create a new check and upload the images.

**Comment by ctrlaltdylan** [comment]
We were using 3.1.0 on our internal dashboard application yesterday. But even after we’ve reverted the upgrade from 5.7.1 back to 3.1.0 the SDK hosted on our internal dashboard still forces camera use during facial similarity checks instead of allowing a file update with the ‘uploadFallback: true’ option enabled.

Our agents are not developers. They don’t have the VPN access nor the experience with the database tools to look up a given customer’s Onfido Applicant ID and upload images with postman outside of our normal dashboard. 

Even the Onfido dashboard does not allow you to upload selfie photos. When you attempt to select “Manual Upload” the the Facial Similarity report unselects my choice automatically. This prevents us from manually uploading selfies even through a manual check on the Onfido dash.

http://g.recordit.co/ecEWJi37W7.gif <http://g.recordit.co/ecEWJi37W7.gif>





We’re glad that you’re considering the age of the photo during ID verification and feedback when this happens, however our customer base doesn’t have 100% success with using the SDK and we need a way to support them. We would appreciate the ability to make those decisions ourselves and give us back the option to upload images.

**Comment by stefaniacardenas** [comment]
That's strange because version 3.1.0 uses live photo and `uploadFallback` is true by default. A way to get around that would be using  `useWebcam: false` for your internal SDK, on version `3.1.0`. Please not that `useWebcam: false` was a private feature and has been removed it in newer versions.

**Comment by ctrlaltdylan** [comment]
@stefaniacardenas THANK YOU. This option worked for us. Thank you for sharing, we'll work on perhaps making a custom component to upload docs & selfies outside of the SDK so we can keep in step with the v3 API change.
