### ISSUE TITLE
Handling unknown document types

### ISSUE THREAD

**Issue by michaelcoughlan** [onfido/onfido-sdk-ui#965]
Apologies as this isn’t necessarily an issue with the way the SDK works but it could be a feature request.

I saw an issue raised in February about US Visas and choosing a passport to account for this. As the Onfido API accepts a document type of unknown, this unknown document I’d like to capture would be, for example a birth certificate. Is there a certain path I should follow in the SDK to best categorise this type of document?

**Comment by ramprasad-parajuli** [comment]
@michaelcoughlan Web SDK is configured to accept the driving license, National Identity card, and passports. With that said, you could upload a birth certificate by selecting, for example, the National Identity card as a document type, if you are going to create a Right to Work report on the backend (Birth Certificate is accepted as a document for Right to Work reports). The reason for selecting any document type is because the Onfido Algorithms will classify the document independently of the document_type that was selected while uploading the document through the SDKs.

I hope the above suggestion makes sense. Please do let me know if you have any follow-up questions or concerns.

**Comment by michaelcoughlan** [comment]
@ramprasad-parajuli I see what you mean thank you! A guess a follow up question from that would be do you know if there's a way I can make the SDK only take a photo of one side rather than two? Since, for example, national identity card wants a 2 sided capture?

**Comment by ramprasad-parajuli** [comment]
@michaelcoughlan Sorry for the delay. Unfortunately, there is no wat to force the SDK to take only one side of the national identity card. What you could do is you could upload a birth certificate by selecting, passport as a document type as it will only ask you to take the photo once.

**Comment by stefaniacardenas** [comment]
Hi @michaelcoughlan, the SDK is designed to capture only 3 types of documents (passport, national id card and driving license). If you need to capture other documents you will have to implement your own solution. We are currently in the process of introducing additional document types but for now I would only use the web SDK to capture the passport, national id card and driving license. I hope it helps.

**Comment by aprilpay** [comment]
Hi @stefaniacardenas, does the SDK support only 4 types of documents now? (passport, national id card, driving license, and residence permit)? I've tried other documentTypes listed under Canada's region and only the four mentioned above worked so I would like to verify if that's the case :(

**Comment by stefaniacardenas** [comment]
Hi @aprilpay,
Yes, that is correct. Only four documents are supported at the moment.
What types were you expecting to capture?

**Comment by aprilpay** [comment]
Thank you for your prompt response @stefaniacardenas! I would like to capture document types Indigenous Card, Proof of Citizenship, Service ID Card, and Visa

**Comment by stefaniacardenas** [comment]
Hi @aprilpay, we are planning to introduce new document types towards the end of Q2 that will be country specific. So I believe that the document types you are planning to capture will be available around late June/July. I hope this helps.

**Comment by adityat90** [comment]
Sorry to comment on an old thread, but is there an update here?
I've been trying to find references to indigenous cards in the SDK, but haven't been able to.
What document_type am I supposed to send for an Indigenous Card?

**Comment by warrenseine** [comment]
Hello @adityat90, I'm not sure about the support in the SDK, but the document type for indigenous cards is `indigenous_card`. You should probably contact customer support directly for an up-to-date answer.
