### ISSUE TITLE
Upload file and take picture options on mobile?

### ISSUE THREAD

**Issue by ravinpatel** [onfido/onfido-sdk-ui#967]
Hi,

I was wondering if we could configure to allow the user to be able to pick between taking a picture or uploading their document on mobile. I can see there is a `uploadFallback` which I believe is designed if there are problems taking a live photo or any other type of error but could we have this as an option for the user to choose?

Thanks in advance,

Ravin

**Comment by andra-radu** [comment]
Hi @ravinpatel,

`uploadFallback` is true by default and it means that if a user that cannot take a live photo using the embedded camera capture (so the camera that you see embedded in the browser using getUserMedia API) when they are on mobile they will be able to use their native camera as a fallback. 
If the users are using browsers that allow selecting a picture from their gallery (for example Firefox) they will also be able to select and upload an image from the gallery.
If you would like to restrict users  to upload from the camera gallery, therefore, you can set uploadFallback to false. More details about `uploadFallback` can be found [here](https://github.com/onfido/onfido-sdk-ui/blob/master/README.md).

I hope that helps.

**Comment by ravinpatel** [comment]
Hi @andra-radu 

Thanks for your response, what I was asking if it is possible to offer options for the user to choose between taking a picture using their native camera or uploading document.

Thanks

**Comment by andra-radu** [comment]
Hi @ravinpatel,

The option 'offered' will depend on user's phone. Some phones will allow users to select from the gallery and others won't. As I've mentioned before, if users are using browsers that allow selecting a picture from their gallery (for example Firefox) they will also be able to select and upload an image from the gallery. If you would like to restrict users to upload from the camera gallery, therefore, you can set uploadFallback to false. 
Please let me know if you need any further info.

**Comment by stefaniacardenas** [comment]
I will close this issue for inactivity. Feel free to reopen if you have any other question.
