### ISSUE TITLE
Blank screen on the 'document' step

### ISSUE THREAD

**Issue by ravinpatel** [onfido/onfido-sdk-ui#979]
### What was the expected behaviour?
The users native camera is meant to open and allow them to take a picture of their document.

### What happened instead?
The user reports they see a blank screen when the camera tries to open. Here is the email from the user:

<img width="1103" alt="Screenshot 2020-04-28 at 12 29 28" src="https://user-images.githubusercontent.com/14273533/80482333-f8ec2700-894b-11ea-96a5-2959716847c5.png">

### Version info:

- Onfido SDK: 5.5.0
- OS: IOS
- Browser: Safari
- Device: IPhone
- Node
- Framework or relevant dependencies (if applicable)

![image (1) (1)](https://user-images.githubusercontent.com/14273533/80481668-cdb50800-894a-11ea-9559-edf4bca5d0cb.png)

### Integration configuration:

```
import('onfido-sdk-ui').then(({ init }) => {
            init({
              token: res.data.onfido_token,
              containerId: 'onfido-mount',
              onComplete: () => {
                confirmOnfido(userID).then((res) => {
                  res.status === 200 && navigate('/onboarding')
                })
              },
              onError: (err) => {
                window.Sentry.captureException(err);
              },
              steps: [
                {
                  type: 'welcome',
                  options: {
                    title: 'Identity Verification',
                    descriptions: ['Please follow instructions to submit your documents,', 'it will only take a couple minutes']
                  }
                },
                {
                  type: 'document',
                  options: {
                    documentTypes: {
                      passport: true,
                      driving_licence: false,
                      national_identity_card: false
                    }
                  }
                },
                {
                  type: 'poa',
                  options: {
                    country: 'SGP'
                  }
                },
                'face',
                'complete'
              ]
            })
          })
        }
      }
    })
```

### Steps to reproduce:

The initial step of taking a picture of their document ( The user tried to take a picture of a UAE passport)

Thanks in advance!

**Comment by ravinpatel** [comment]
We have contact with the user so please don't hesitate if there are any other details needed, thanks

**Comment by kopijunkie** [comment]
Thank you for raising this issue @ravinpatel 

I was unable to replicate it in Safari on an iPhone running on iOS 13.3.1. Only thing I can think of is to ask the user to check if camera permission has not been disabled in the phone's settings.  If it is possible for the user to provide a video of their steps leading to the issue happening that could provide more insight for us to help solve this.

**Comment by ravinpatel** [comment]
Updated to version `5.9.0`

**Comment by misrab** [comment]
This is the code we're using, experiencing the same issue. User is on Windows 10, using Chrome.

Anything we're doing wrong in the code?

```
export class IdCheck extends Component {

  async componentDidMount() {
    const { showLoader, hideLoader } = this.props
    if (this.props.userID) {
      showLoader()
      await this.setupOnfido(this.props.userID, this.props.userCountry)
      hideLoader()
    }
  }

  async componentDidUpdate(prevProps) {
    if (!prevProps.userID && this.props.userID) {
      this.props.showLoader()
      this.props.clearFormErrors()
      await this.setupOnfido(this.props.userID, this.props.userCountry)
      this.props.hideLoader()
    }
  }

  setupOnfido = async (userID, userCountry) => {
    const { createOnfidoJWT, t, confirmOnfido, setFormErrors } = this.props
    await createOnfidoJWT(userID).then(res => {
      if (res.status < 200 || 300 < res.status) {
        setFormErrors(t('onBoarding.idCheck.error.unavailable'))
      } else {
        if (typeof window !== 'undefined') {
          import('onfido-sdk-ui').then(({ init }) => {
            init({
              token: res.data.onfido_token,
              containerId: 'onfido-mount',
              onComplete: () => {
                confirmOnfido(userID).then((res) => {
                  res.status === 200 && navigate('/onboarding')
                })
              },
              onError: (err) => {
                window.Sentry.captureException(err);
              },
              steps: [
                {
                  type: 'welcome',
                  options: {
                    title: 'Identity Verification',
                    descriptions: ['Please follow instructions to submit your documents,', 'it will only take a couple minutes']
                  }
                },
                {
                  type: 'document',
                  options: {
                    documentTypes: {
                      passport: true,
                      driving_licence: false,
                      national_identity_card: false
                    }
                  }
                },
                {
                  type: 'poa',
                  options: {
                    country: 'SGP'
                  }
                },
                'face',
                'complete'
              ]
            })
          })
        }
      }
    })
  }
```

**Comment by stefaniacardenas** [comment]
Hi @misrab, we are currently investigating this issue. Just as an FYI unrelated to the issue above, I can see that you are using `poa` together with the `document` and `face` step which is not advisable.  The `poa` should be used as a standalone flow.
Will follow up on the blank screen issues as we make progress.

**Comment by ravinpatel** [comment]
Hi @stefaniacardenas, Thanks for your reply why is it not advisable to use all those steps in one flow? what errors could it cause?

**Comment by stefaniacardenas** [comment]
The Proof of Address feature is experimental and has currently only been tested as a standalone flow. There could be possible issues such as step mismatch when using the cross device feature.

**Comment by stefaniacardenas** [comment]
Hi, are you still facing this issue after upgrading to the latest version of the SDK?

**Comment by stefaniacardenas** [comment]
I will close this issue for inactivity but feel free to reopen if you are still experiencing this.
