### ISSUE TITLE
Passing options to 'document' step does not seem to work

### ISSUE THREAD

**Issue by ghinch** [onfido/onfido-sdk-ui#99]
I am passing a step like:

`{type: "document", options: {"title": "My own title", "hint": "My hint"}}`

When the page renders, the default copy still shows.

I would also like to be able to configure which types of documents are allowed, but this does not seem possible.

**Comment by rfreitas** [comment]
Hi Greg,

To way to override the title is actually this way:
```
options: { captureTitle: 'This is the title that shows in the webcam',
                 uploadTitle: 'This is the title that shows if it's uploading instead'
}
```

However, the feature to override copy was an added hack and as consequence there are flaws, for example not all copy can be overriden at the moment. The `hint` that you want to override is one of those cases, since the copy is actually hardcoded in the component.

**Comment by rfreitas** [comment]
We will be looking to bring in a refactor that will allow to override all copy.

**Comment by ghinch** [comment]
Okay. What about being able to configure which type of document is allowed? For reference, our AML policy requires that we ask certain customers for a copy of both a driving license AND a passport. I would like to be able to have two steps, asking for one document in each.

**Comment by rfreitas** [comment]
At the moment it's not possible. But we are in fact looking into bringing the possibility of having more than one step to capture documents, so we will consider this use case as well.

**Comment by runawaycoin** [comment]
Hi, can we change the default copy yet? as mentioned in the second post above.

**Comment by rfreitas** [comment]
Hey @runawaycoin,
To clarify, you want to change the copy or have two steps that each request a different document type? If both, which copy do you want to change?

**Comment by runawaycoin** [comment]
hi @rfreitas,
like you mentioned before, the copy that is shown before the user clicks to upload a file.

And also like you said - it would be nice to have the copy related to the document selected - ie "please upload a photo of your main passport page" and "please upload a photo of your driving licence"

**Comment by rfreitas** [comment]
do you want to update the copy for localization purposes? or for UX improvements?

In terms of creating specific copy for each document type, this is something we are considering.

pinging @seewah, the product manager

**Comment by rfreitas** [comment]
Localization is also on the road map, but not yet possible.

**Comment by seewah** [comment]
Hi I can see a few topics being discussed here. let me try and summarise and respond to individual items

- support for multiple documents
  - this is being explored at the moment. However, would like to understand better your requirements. Do you want Onfido to verify both documents. We have not really come across the case where two ID documents are required for compliance purposes. Would it be easier to discuss this over email. Ping me an email at "seewah dot cheng at onfido dot com"
- as mentioned, localisation work is happening in Q4
  - this would in theory allow you to specify your own strings across all the screens
- the title of the document capture screen
  - better screen title and general navigation improvement is something we are actually looking at this next few sprints. Regarding the title copy change as suggested, we can look at prioritising this smaller scope of work. We will keep you posted

**Comment by runawaycoin** [comment]
Sorry for the confusion - whats planed will be great and no i'm not asking to be able to submit two different documents in one go.

**Comment by seewah** [comment]
Great. we will keep you posted

**Comment by rfreitas** [comment]
Most features have been released at this point. Closing this issue.
