### ISSUE TITLE
Unable to take selfie using Chrome

### ISSUE THREAD

**Issue by e-birch** [onfido/onfido-sdk-ui#997]
### What was the expected behaviour?

Users are able to take a selfie during the "Take a selfie" step using Google Chrome browser.

### What happened instead?

Users are presented with the "You must allow camera access screen". Upon clicking the "Enable camera" button, users are presented with the "Camera access is denied" screen, even when camera access has explicitly been granted for the site.

### Version info:

- Onfido SDK version 5.9.0
- Issue present on MacOS (Chrome version 81.0.4044.138), Ubuntu 18 (Chrome version 80.0.3987.149), Android 7 (Chrome version 81.0.4044.138)
- Issue cannot be reproduced on Firefox or Safari browsers

`DOMException: Permission denied object`  message displayed in console, but no other output given.

**Comment by stefaniacardenas** [comment]
Hi @e-birch, are you still seeing this issue? Does Chrome have camera permission at OS level?

**Comment by stefaniacardenas** [comment]
Hi @e-birch, I will close this issue for inactivity. Feel free to reopen if you are still experiencing this problem.
